### ISSUE TITLE
Reconnect issues

### ISSUE THREAD

**Issue by dynamix** [aerospike/aerospike-client-go#100]
Hey guys,

After we run into a lot of trouble with our current production aerospike cluster and the go client we started to test some basic (reconnect) case. The first test was - can the client handle a simple single node restart gracefully. Sadly that does not seem to be the case. 

https://github.com/aerospike/aerospike-client-go/blob/96b4289bd745ac8c3df7c0c3bf1a2f1fd933abf5/cluster.go#L538-L543

len(nodesToRemove) is one and len(nodes) is one as well, therefor the node is node removed. I guess the statement should just check for the negative but not the zero case.

Going to look into the other cases tomorrow ...

Ciao,
Martin

**Comment by khaf** [comment]
This issue was fixed. Feel free to file new issues as new tickets.
