### ISSUE TITLE
Reconnect issues II

### ISSUE THREAD

**Issue by dynamix** [aerospike/aerospike-client-go#101]
Hey again,

the second issue we saw happens with a multi node cluster (three nodes). In case the connection to the cluster is lost (all nodes, or two nodes) the client never removes these due to the check in https://github.com/aerospike/aerospike-client-go/blob/master/cluster.go#L447 . I'm sure there was a reason for this check but if Refresh() only works for one node this cause a lot of trouble. Every command will try to use the dead nodes because IsActive still returns true (if the partitions is on one of these nodes) and every connection will timeout. If LimitConnectionsToQueueSize is not set to true and the timeout is not super low, that basically kills a system that has a lot of load (syscall piling up faster than they timeout). 

(As a side note - what we did at some point before finding this issue, was to increase the number of allowed client connection in as itself (proto-fd-max). That lead to the next issue because of the heartbeat fd limit https://github.com/aerospike/aerospike-server/blob/master/as/src/fabric/hb.c#L141, we started to see a lot of these https://github.com/aerospike/aerospike-server/blob/master/as/src/fabric/hb.c#L1447 which made the heartbeat unreliable)

Ciao,
Martin

**Comment by khaf** [comment]
Just to help me better understand the problem: Is this an edge case? This means the connection is lost RIGHT after the hand shake, right? Otherwise the node will always be removed (at least after the newest v1.8.0 release).

**Comment by dynamix** [comment]
Hi,

edge case in the sense that it only happens in a three node cluster : yes. I will give it a try with 1.8.0 later today and check if it still happens.

Ciao,
Martin

**Comment by khaf** [comment]
Thanks Martin. I'll be releasing a new client early next week and will have the fix in that release if I get some feedback.

**Comment by khaf** [comment]
Martin, since I haven't heard back from you regarding this issue, I'll go ahead and close it. Please feel free to file new tickets in case you encounter new issues.
