### ISSUE TITLE
Have DropIndex work similarly to CreateIndex

### ISSUE THREAD

**Issue by gdm85** [aerospike/aerospike-client-go#102]
I noticed that CreateIndex will actually create a task, and then nodes are polled until they all agree upon the completion.

However, currently if one issues a drop index command through this client library and instantly tries to create it, gets an error:
```
Index already exists
```

This is probably because the operation is still in progress; can we have a similar behavior to CreateIndex where there is some polling going on until the drop is acknowledged to be effective?

**Comment by khaf** [comment]
Thanks for the suggestion. I'll look into it and will change the behavior if possible.

**Comment by gdm85** [comment]
I can try to arrange a PR if you like

**Comment by GeertJohan** [comment]
Would be nice to have this feature indeed.

**Comment by khaf** [comment]
This would require an API change, so I changed it so that it will block until the index is dropped completely. The old behavior is still possible via `go client.DropIndex(...)`

**Comment by gdm85** [comment]
I see it's done in bc65f626c6f06e11ae9aeab8eeb9df11fd255265, very nice, thanks!
