### ISSUE TITLE
PutObject and updates

### ISSUE THREAD

**Issue by ClanStyles** [aerospike/aerospike-client-go#103]
What's the proper way to use PutObject with a WritePolicy to update the record instead of creating a new and overwriting it?

**Comment by khaf** [comment]
This behavior is controlled via `WritePolicy.RecordExistsAction`, which by default either creates, or merges the provided bins. Since all attributes of a struct are serialized each time via `PutObject`, this amounts to overwriting the object in the db.

What is it that you are trying to do instead?

**Comment by ClanStyles** [comment]
I'm trying to do exactly that. I have a record that needs to be merged (old data kept, new data saved).

**Comment by khaf** [comment]
Then the default behavior should already work as you expect.

**Comment by ClanStyles** [comment]
It doesn't.

```
func (a AeroRequestRepo) Save(p Request) error {
	key, err := aerospike.NewKey("ads", "requests", p.URL)
	if err != nil {
		return err
	}

	return a.client.PutObject(nil, key, &p)
}
```

It seems to overwrite the whole record given the key. (You can tell by the Created timestamp and a few  other bins.

**Comment by khaf** [comment]
The library cannot tell which fields have been *changed*. It serializes the while struct (attribute-by-attribute), and sends them to the db. All the fields in the record with those attribute names will be changed to the new values.

But I understand that is how all other libraries -including SQL - work as well, no?
