### ISSUE TITLE
Versioning of this package

### ISSUE THREAD

**Issue by GeertJohan** [aerospike/aerospike-client-go#104]
I noticed some breaking changes (see http://labix.org/gopkg.in) were made for #79.

I think that it's generally good to vendor packages to a project so that upstream breaking changes don't break local code. However, when a Go package provides versioning through gopkg.in, it is expected that breaking changes are not made on minor version updates. i.e.: v1.x (`gopkg.in/aerospike/aerospike-client-go.v1`) must never break the exported API.

Would it be possible to buffer breaking changes in a branch and release/apply them once in a while as part of a new major release? This will require users of this package through `gopkg.in` to manually update their import paths to the new major, at which point they expect having to update their code.

An other option could be to drop the gopkg.in advertisement from the README, and instead strongly advise to vendor this package because breaking changes can be released in a minor release. This will give maintainers more freedom in rapidly updating this package, including breaking changes. When users have to update their code on each minor release that's generally not very nice, but it could be a good case here because the package is still relatively young, and Go 1.5 introduced better vendoring support. Most important thing here is that it is advertised properly.

**Comment by khaf** [comment]
You are right. Will try to follow semantic versioning principles in the future.
