### ISSUE TITLE
Large List FindFrom backwards

### ISSUE THREAD

**Issue by sdac** [aerospike/aerospike-client-go#109]
Is there currently any way of doing the opposite of FindFrom?

If I have a set of keys [256, 512, 1024, 2048, 4096], FindFrom(1024, 3) gives me [1024,2048,4096], and that is good. But how can I, starting from 1024, find 512 and 256?

I must be missing something because this seems like a most trivial feature and large lists aren't very useful if we can't navigate in them easily.

Perhaps letting FindFrom accept negative values could be one solution. I.e. FindFrom(1024, -3) would give me [1024, 512, 256].

**Comment by khaf** [comment]
Unfortunately this feature is not available with large lists. Have you tried our new List API via the operate method? The negative values for count work there.

**Comment by sdac** [comment]
No, lists are unfortunately too limiting. We are using Large Lists as isolated key-value databases and they grow large. They are accessed and modified often and independently of the containing row.

Is the requested feature not available simply because it hasn't been implemented, or because limitations in the algorithm used for storage prevents traversing the list in that direction?

**Comment by khaf** [comment]
It hasn't been implemented yet, though it is not clear to me if there has been a technical reason involved. I'll see if it is possible to implement it. No promises :)

**Comment by khaf** [comment]
This use-case should be supported by CDT lists now.
