### ISSUE TITLE
GetObject panics when provided with an interface{}

### ISSUE THREAD

**Issue by faizanrashid** [aerospike/aerospike-client-go#110]
I'm trying to do a client.GetObject call but it keeps panicking.

Is this not allowed? Shouldn't the library decode the record and store it in the record variable?
What i'm running:
```
    var record interface{}
    err := dvClient.GetObject(nil, key, record)
    fmt.Println(record, err)
```

Error:
```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/reflect/value.go:1633 +0x8c
github.com/aerospike/aerospike-client-go.(*SyncMap).mappingExists(0x827f40, 0x0, 0x0, 0x0, 0x40d5a9)
	/apps/go/src/github.com/aerospike/aerospike-client-go/marshal.go:178 +0x42
github.com/aerospike/aerospike-client-go.cacheObjectTags(0x0, 0x0, 0x0)
	/apps/go/src/github.com/aerospike/aerospike-client-go/marshal.go:205 +0x6b
github.com/aerospike/aerospike-client-go.(*Client).GetObject(0xc20803af00, 0xc2080528c0, 0xc208056410, 0x0, 0x0, 0x0, 0x0)
	/apps/go/src/github.com/aerospike/aerospike-client-go/client.go:310 +0xb4
main.main()
	/root/get.go:39 +0x34c

goroutine 7 [runnable]:
github.com/aerospike/aerospike-client-go.(*Cluster).clusterBoss(0xc208000c60, 0xc208056000)
	/apps/go/src/github.com/aerospike/aerospike-client-go/cluster.go:105
created by github.com/aerospike/aerospike-client-go.NewCluster
	/apps/go/src/github.com/aerospike/aerospike-client-go/cluster.go:97 +0x61b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

**Comment by khaf** [comment]
`GetObject` method assumes you are passing in a pre-allocated struct and tries to fill it up based on the attribute names and tags. If you want your data as a map, you can do that via a normal `Get` call.

**Comment by faizanrashid** [comment]
Okay that makes sense. i was just using that as a test and found it weird that it panicked.
So I decided to create a struct with an attribute name and tags corresponding to the bin names:

```
type tagged struct {
    search map[string]interface{} `as:"s"`
}
```
But this didn't return me what I expected:
```
    record := &tagged{}
    err = dvClient.GetObject(nil, key, record)
    fmt.Println(record, err)
```
returned:
```
&{<nil>}
```
When doing a regular get returns:
```
{user set [224 65 221 254 215 167 8 247 139 94 116 168 152 183 60 164 232 50 250 118] 730a1968-7dfd-11e3-8d99-00259035cb2a} map[s:map[meta:map[_sa_15479:map[stm:_sa_15479 stp:meta dsi: dc:chango ts:1453734001 count:6]]]]
```

Do i need to create another structure to map the attribute names within the map stored in the bin and have the appropriate tags for it to work? Also can I create a struct and only have tags for 1 or 2 bins? Or do I need to create it to define the whole record?

Thank you!

**Comment by khaf** [comment]
The reason is that your search attribute is not exported (doesn't begin with a capital letter). As a result it is not visible to the library.

You can selectively tag any attributes you like. If an attribute is not tagged, it will require the bin name to be exactly the same (case-sensitive). The attribute of course should begin with a capital letter as per Go rules.

**Comment by faizanrashid** [comment]
ah that makes perfect sense. Silly mistake :)
Thank you for the very quick feedback!
