### ISSUE TITLE
Client.Execute() for UDF is not persisting key with policy.SendKey=true

### ISSUE THREAD

**Issue by felipejfc** [aerospike/aerospike-client-go#111]
Hi, I have this snippet:

```
WritePolicy := aerospike.NewWritePolicy(0,0)
WritePolicy.SendKey = true

_, err = client.Execute(WritePolicy, key, "package", "method", aerospike.NewValue(record.x), aerospike.NewValue(record.y), aerospike.NewValue(record.z))

```
the lua code of the method has

```
function insert_session(r, x, y, z)
...
...
  if aerospike:exists(r) then
    aerospike:update(r)
  else
    aerospike:create(r)
  end

```

And when The UDF creates or update the record it is not storing the key with the record, at least I can't see it with select * from mynamespace.mycollection...

**Comment by khaf** [comment]
This looks like a server-side bug. I'll get back to you after further investigation tomorrow.

**Comment by khaf** [comment]
This turned out to be a client-side bug. Fixed on the master.
