### ISSUE TITLE
Use different error messages on different kinds of timeout

### ISSUE THREAD

**Issue by wellle** [aerospike/aerospike-client-go#113]
We just noticed a slightly misleading error message in `command.go`, where it says
>"command execution timed out."

when it actually just exceeded the max number of configured retries. (While we didn't even have any timeout set, that's what confused us).

You might consider using a different error message like "exceeded number of retries" or something like that in that case.

**Comment by khaf** [comment]
Thanks for your report. Will do on next release.

**Comment by khaf** [comment]
Fixed on master.

**Comment by wellle** [comment]
Thanks :+1:
