### ISSUE TITLE
Weird problems with anonymous structs

### ISSUE THREAD

**Issue by zippoxer** [aerospike/aerospike-client-go#114]
I cache this GeocodeResponse type:

```
type GeocodeResult struct {
	FormattedAddress string `json:"formatted_address"`
	Geometry         struct {
		Bounds struct {
			Northeast GeocodePoint
			Southwest GeocodePoint
		}
		Location     GeocodePoint
		LocationType string `json:"location_type"`
	}
	Types []string
}

type GeocodeResponse struct {
	Status       string
	ErrorMessage string `json:"error_message"`
	Results      []GeocodeResult
}
```

After every cache of GeocodeResponse with PutObject, the client struct used in the cache will retrieve cached entries without error, but the returned struct from GetObject would be empty.

GetObject before PutObject works fine, only after one PutObject, all following GetObject calls return an zero-value struct, but no error.

Once I defined types for the anonymous structs and included them in GeocodeResult, this problem has gone away.

**Comment by khaf** [comment]
Do you mean you pool this struct? Did you check if the record was correctly created in the database?

**Comment by zippoxer** [comment]
I don't know what pooling a struct means. This is a bug with the library's PutObject/GetObject and anonymous structs. No other functions are used.

I'll try preparing a self-containing reproducer and send it for you anyone to try.

**Comment by khaf** [comment]
A small code snippet would greatly help to pin point the bug. Thank you for your help.
I'm preparing a minor release for next week, and will include the fix for this issue if we can find it.

**Comment by zippoxer** [comment]
@khaf 

Of course, glad to help :)

I realized I wasn't explaining myself clearly since I didn't understand the problem well enough.

So, I made a self-containing reproducer that explains it:

```
package main

import (
	"log"

	"github.com/aerospike/aerospike-client-go"
)

type A struct {
	X string
	Y struct{ Z int }
}

func main() {
	c, err := aerospike.NewClient("localhost", 3000)
	if err != nil {
		log.Fatal(err)
	}

	a := A{
		X: "first",
		Y: struct{ Z int }{Z: 3},
	}

	// Put key 1.
	key, err := aerospike.NewKey("c21", "anon", 1)
	if err != nil {
		log.Fatal(err)
	}
	err = c.PutObject(nil, key, &a)
	if err != nil {
		log.Fatal(err)
	}

	// Get key 1.
	key, err = aerospike.NewKey("c21", "anon", 1)
	if err != nil {
		log.Fatal(err)
	}
	var result A
	err = c.GetObject(nil, key, &result)
	if err != nil {
		log.Fatal(err)
	}

	// Get returns a zero value of A:
	log.Printf("result: %#v", result)
	
	// This test works fine if:
	
	// 1. You don't make a Put operation before the Get, or create a new
	// client only for the Get operation. 
	
	// 2. Remove the anonymous struct field Y in type A. Anonymous
	// structs are the cause of this issue. 
}

```

**Comment by zippoxer** [comment]
@khaf 

Hey, I fixed the problem. Would you check [my pull request](https://github.com/aerospike/aerospike-client-go/pull/115)?

**Comment by khaf** [comment]
I was just checking in the exact fix myself! I'll merge yours though. Thanks!

**Comment by zippoxer** [comment]
@khaf 

Hehe, sorry I was too late.

It's a pretty obvious fix then, that's great ;-)

**Comment by khaf** [comment]
Merged your PR. Fix is in master.
