### ISSUE TITLE
 Error code (215) not available yet

### ISSUE THREAD

**Issue by figoxu** [aerospike/aerospike-client-go#119]
There are some logs in our production enviourment  as follow:
`2016/02/29 14:01:42 [sendLoop] send err Error code (215) not available yet - please file an issue on github. `
What is the error code 215 means ? How do i slove that problem ?

The client version is    c67926037f43193e75b809cef583ed99b2d3b10b
![a000](https://cloud.githubusercontent.com/assets/10055828/13415539/96916a2e-df96-11e5-996b-2f475602caf2.png)

The server version is 3.6.0

**Comment by figoxu** [comment]
I found that topic on the aerospike forum .
https://discuss.aerospike.com/t/error-code-215/1903/6
It said that  trid (transaction id) must be different .
How do i set the transaction id  when i use go driver ?

**Comment by khaf** [comment]
Thank you for your report. I guess you reuse the same statement without changing the `TaskId`. In that case, please set the `Statement.TaskId` to a new random number before passing that statement to a scan/query, e.g:

```go
stmt.TaskId = uint64(rand.Int63())
client.Query(policy, stmt)
```

I'll have to think how it is best to do it in the client itself.

**Comment by figoxu** [comment]
- In our source code, All of the statement are local variable in the function .All of the statement are create by method "as.NewStatement(NS_PUSH, SET_DV)"
- Does the "xornd.Int64()" is  trust worthy In a distributed environment ?
- Does the TaskId has the range limit ? If have some limit ,please tell me . thank u.
- What do u think  the code `stmt.TaskId = time.Now().UnixNano()+rand.Int63()` in a distributed environment should be okay ?

**Comment by khaf** [comment]
1. Should be ok. 
2. Until now we haven't noticed that the random number generator may have problems on a distributed environment. I just tried to create a duplicate for a billion (1e9) numbers and was unable to. There is a special case that if some of your distributed applications start at the same time down to nano seconds, you may experience some duplicates. That is highly unlikely though.
3. TaskId doesn't have a range limit. It should be a unsigned long (uint64)
4. RNG already has a notion of time built into it, so *theoretically* there should be no need to do that. You can of course try to see if it works in your case.

There is also a case that I hadn't originally considered in the code, regarding low precision clocks when the RNG pool is allocated. In such a case, you may experience duplicates. I'll commit a patch to the master in a moment to make sure that won't happen as well.

**Comment by khaf** [comment]
Please update your client to latest from master to see if you see any improvements.

**Comment by khaf** [comment]
Are you still encountering this problem?

I'm releasing a new client today and would like to include the fix in, in case there was a bug in client code.

**Comment by khaf** [comment]
I'm going ahead and closing this issue. Feel free to open a new ticket in case you encounter further issues.
