### ISSUE TITLE
read tcp i/o timeout

### ISSUE THREAD

**Issue by deviantmk** [aerospike/aerospike-client-go#121]
Hi
Some description:
I am running write only *for loops from 2 servers on a cluster with two nodes.
After a while in the console a few errors pop up, periodically every few minutes

read tcp 10.2.12.11:49294->10.2.17.141:3000: i/o timeout
read tcp 10.2.12.11:49296->10.2.17.141:3000: i/o timeout
read tcp 10.2.12.11:47514->10.2.10.151:3000: i/o timeout
read tcp 10.2.12.11:47524->10.2.10.151:3000: i/o timeout
read tcp 10.2.12.11:49316->10.2.17.141:3000: i/o timeout
read tcp 10.2.12.11:49306->10.2.17.141:3000: i/o timeout
read tcp 10.2.12.11:49320->10.2.17.141:3000: i/o timeout
read tcp 10.2.12.11:49322->10.2.17.141:3000: i/o timeout

Do you have any idea why would these show up?
if needed i can provide access to all servers

**Comment by khaf** [comment]
Am I correct to assume you're ingesting data into Aerospike?

Would you provide a bit of information regarding the nature of this data, and its average size?

The client library reads back server response regarding the sent data, and also tends to the cluster status in intervals.

Depending on server load, some of these may timeout. What is the timeout you are using?

**Comment by deviantmk** [comment]
Thats correct i was just testing the insert load

As i said before i just run a *for loop from two server

```
  for i := 0; i < 1000000; i++ {
    
      key, err := as.NewKey("test", "diskset", "mykey" + strconv.Itoa(i))
      if err != nil {
        log.Println(err)
      }

      bin := as.NewBin("mybin", "myvalue " + strconv.Itoa(i))

      err = client.PutBins(policy, key, bin)

      if err != nil {
        log.Println(err)
      }
  }
```

I use 50ms as latency policy but i monitor the latency and it the load is around 50 on 1 ms and 0 on 8ms

I will observe some more but i doubt its the the size or the data
i was thinking of a leak or max conn limit reached, but the admin shows only 15 conn per node so i doubt its that either

**Comment by khaf** [comment]
This seems too slow to me. `ops/sec` is way too low,  and `>1ms` latency values are too high (should be ~ 1%).

Are you confident that your network setup is working as expected? (In case you are testing on the cloud, can you provide some info regarding which service you're using?)

**Comment by deviantmk** [comment]
you are right it was just a virtual server with 2g mem and 2 vcpu, plus it was a disk namespace
on a dedicated server (4core cpu, 8gb mem)

```
network SDD DISK
slice-to (sec)      1      8     64  ops/sec
-------------- ------ ------ ------ --------
00:25:43    10   1.12   0.01   0.00   4200.1
00:25:53    10   1.32   0.02   0.00   4162.7
00:26:03    10   0.84   0.02   0.00   4203.2
00:26:13    10   0.93   0.02   0.00   4206.2
00:26:23    10   0.98   0.00   0.00   4201.3
00:26:33    10   1.18   0.00   0.00   4199.7
00:26:43    10   0.76   0.01   0.00   4255.7
00:26:53    10   1.09   0.03   0.00   4194.6
```

```
MEMORY
slice-to (sec)      1      8     64  ops/sec
-------------- ------ ------ ------ --------
02:48:15    10   0.66   0.00   0.00   5419.6
02:48:25    10   0.66   0.00   0.00   5426.8
02:48:35    10   0.68   0.00   0.00   5430.0
02:48:45    10   0.53   0.00   0.00   5404.4
02:48:55    10   0.55   0.00   0.00   5429.6
02:49:05    10   0.54   0.00   0.00   5399.6
```

is this result good?

**Comment by deviantmk** [comment]
since this error didn't show up again i am closing the issue

**Comment by khaf** [comment]
Please feel free to file new issues in case you encounter problems.
