### ISSUE TITLE
empty map could not be extracted from DB

### ISSUE THREAD

**Issue by onokonem** [aerospike/aerospike-client-go#122]
panic message

```
error: hash of unhashable type []interface {}
```

panicking code:

```
github.com/aerospike/aerospike-client-go/unpacker.go:111
```

**Comment by khaf** [comment]
Looks like you happen to have an array as map key. Is that right? Apparently Go doesn't support that.

**Comment by onokonem** [comment]
> Looks like you happen to have an array as map key

looks like you did not read the subject :)

this is a result of reading empty map from DB. empty as a `{}`

the other interesting thing how this empty map get to DB initially. I've added a map with `[]byte` used as keys. looks like such keys arу silently ignored on write.

**Comment by khaf** [comment]
Oops, You're right I didn't notice the title. You just found an edge case!

While maps and slices are not supported as map keys in go, bounded arrays are, though they are not easily supported in reflection package (only in Go 1.5 do you get such support, and in my experience it is tricky to use). Our `msgpack` implementation depends on such support for map keys.

I fixed this issue for bounded byte arrays (`[...]byte`), and the library will now panic if maps, slices and bounded arrays of any type other than `byte` are passed to it.

The library will now need go1.5+.

**Comment by khaf** [comment]
Fix is in master. Please let me know if it works for you.

**Comment by onokonem** [comment]
sorry I did not check this yet. and it is very unlikely I will be able to test this any time soon :(

sorry for delay with answer also - we have a project released in 2 weeks :)

**Comment by khaf** [comment]
No Problem, thanks for your response. I'll close this issue then. 

Feel free to file new issues (or continue this thread later) in case you encounter new issues.
