### ISSUE TITLE
node auto discovery

### ISSUE THREAD

**Issue by deviantmk** [aerospike/aerospike-client-go#123]
Hello

I was trying to figure out how the node auto discovery works.
Could you point me to the file and the line where that happens so i can wrap my head around it

thanks

**Comment by khaf** [comment]
Hi, have a look at tend method in cluster.go, and follow the calls from there.

Let me know in case you need more clarification.

**Comment by deviantmk** [comment]
i cant figure out where the other nodes are returned by the aerospike server

**Comment by khaf** [comment]
Each node advertises other visible nodes in its `services` property via an `info` command. Then the client constructs a list of nodes from combining and interpreting those nodes as the cluster.

**Comment by deviantmk** [comment]
thanks a bunch @khaf :thumbsup:
