### ISSUE TITLE
EOF and hanging client

### ISSUE THREAD

**Issue by alicebob** [aerospike/aerospike-client-go#125]
This is a bit tricky to reproduce, but stopping and starting a bunch of AS deamons in a particular order I manage to get 'EOF' errors, and a hanging Go client.
I run this test client in a terminal: https://gist.github.com/alicebob/ed1ac1c1f192481cb819
Go client is the most recent on Go 1.6, AS server is 3.7.5, on virtualboxes.

I start 2 AS daemons, on different virtual machines. The client is running and gives no errors (AMC reports about 3K writes/sec). 
Then I add and remove a 3rd server (slowly). Client is still running happily, no errors. AMC is also happy, it reports two noded up and one down, as it should.
The I add and remove a 4th server, and the client gives me:

> i: 331000
> client.Put: EOF
> i: 332000
[hangs]

Sometimes there are more EOFs before it hangs.

Restarting the client (the AS servers are still as they were, which is the first two servers are online) gives EOFs again:

> $ go run asb.go 
> i: 0
> client.Put: EOF
> i: 1000
> i: 2000
> client.Put: EOF
> i: 3000
> client.Put: EOF
> i: 4000
> [long timeout]
> client.Put: EOF
> client.Put: EOF
> i: 5000
> client.Put: EOF
> i: 6000
> client.Put: EOF
> client.Put: EOF
> client.Put: EOF
> [long timeout, maybe hangs]
etcetera

Where do these EOF errors come from? Why are they persistent between client runs?

**Comment by khaf** [comment]
Hi, thanks for your very helpful report.

The reason the client hangs is that you don't have a timeout set for your `writePolicy`. Set `writePolicy = 50 * time.Millisecond` and the client won't hang anymore. (I don't have a clear idea of exactly why the client ends up listening to the socket indefinitely yet - looks like some packets are dropped but the socket is not closed)

The `EOF` errors are the result of connections being dropped in the middle of data transmission (when you stop the server). All of this looks like normal behavior.

To further investigate, you can add:
```go
asl.Logger.SetLevel(asl.INFO)
```
to your code to see the internal client logs.

Let me know in case you notice other erratic behavior.

**Comment by alicebob** [comment]
Thanks for the reply, I'll try the timeouts.

The EOF still looked dodgy, since I stopped restarting the AS servers, so things should be stable. I tracked the EOF down to `parseResult()` in command.go:1053, which is weird, because the `Write()` just before works fine (on the same socket).

**Comment by khaf** [comment]
The reason it hangs is that it waits for the server response for the write operation (to see if the transaction went through or not), but for some strange reason, it doesn't get enough bytes back. Since there is no timeout and - again strangely - the connection is not dropped, it hangs in there indefinitely.

Dodgy indeed.

**Comment by alicebob** [comment]
It gets 0 bytes back actually; it looks like the server closes the connection. But this all only happens after the restart dance I described above.

**Comment by khaf** [comment]
That's how it happens: The client expects N bytes, it doesn't get as many (0 is the same), and in the absence of any timeouts, it doesn't get any errors back from the socket (should get an EOF). So it waits - or loops - indefinitely.

If you set a timeout, it will kick in eventually and break the infinite loop.

**Comment by alicebob** [comment]
The timeout fixes the hanging (as expected), but it also seem to fix the EOF errors. Which I find surprising, but it works. If I manage to reproduce it later I'll be back :)

Maybe you can add the `writePolicy.Timeout = ...` to example/simple.go? It's the one I used as a base for the test.

Thanks!

**Comment by khaf** [comment]
No problem. Thanks for your suggestion, will take care of the examples.
