### ISSUE TITLE
cannot use (type string) as type aerospike.Value in argument to lmap.Put

### ISSUE THREAD

**Issue by foliodev** [aerospike/aerospike-client-go#13]
It seems the lmap.Put wont accept my key and value as it is expecting aerospike.Value as type but when i try asserting the type into aerospike.Value, it wont accept it as well. lmap.PutMap works fine

**Comment by ktmighty14** [comment]
I'm kinda having the same problem, i cant write a collection of geojson data.
are there any ways??!??
`package main

import (
	"encoding/json"
	"fmt"
	"github.com/aerospike/aerospike-client-go/go.geojson"
	"github.com/onsi/ginkgo"


	"log"
	"github.com/onsi/gomega"
	_ "strings"

	as "github.com/aerospike/aerospike-client-go"
	shared "github.com/aerospike/aerospike-client-go/examples/shared"
)

type itemdata [][]geojson.FeatureCollection
func main() {
	runRecord_Entry(shared.Client)

	log.Println("\t \t Application ran successfully GrandMaster")
}

func runRecord_Entry(client *as.Client) {


	// define a client to connect to

	client, err := as.NewClient("127.0.0.1",3000)
	PanicOnError(err)

	ginkgo.It("To load the data", func() {


	// The Data
	var points itemdata

	json.Unmarshal([]byte{
			`{
			"type": "FeatureCollection",
			"features": [
				{
					"type": "Feature",
					"geometry" : {
						"type" : "Point",
						"coordinates": [13.009318762,80.003157854]
					},
					"properties" : {
						"name" :"Work shop",
						"demand":"49589",
						"capacity":"4231"
					}
				},
				{
					"type": "Feature",
					"geometry" : {
						"type" : "Point",
						"coordinates": [13.00961276, 80.003422154]
					},
					"properties" : {
						"name" :"main block",
						"demand":"247859",
						"capacity":"2974"
					}
				},
				{
					"type": "Feature",
					"geometry" : {
						"type" : "Point",
						"coordinates": [13.009318762,80.003157854]
					},
					"properties" : {
						"name" :"Work shop",
						"demand":"49589",
						"capacity":"4231"
					}
				},
				{
					"type": "Feature",
					"geometry" : {
						"type" : "Point",
						"coordinates": [13.00961276, 80.003422154]
					},
					"properties" : {
						"name" :"main block",
						"demand":"247859",
						"capacity":"2974"
					}
				}
			]
			}`}, &points)

		// define some bins
		count := 0
		for i, ptsb := range points {

			key, _ := as.NewKey("test", "testset", i)
			bin := as.NewBin("vada", as.NewGeoJSONValue(ptsb))
			err := client.PutBins(shared.WritePolicy, key, bin)
			

			gomega.Expect(err).ToNot(gomega.HaveOccurred())
			shared.PanicOnError(err)

			
			gomega.Expect(count).To(gomega.Equal(4))
		}

		// queries only work on indices

		client.DropIndex(shared.WritePolicy, "test", "testset", "my_geo_inex_hu")
		client.CreateIndex(shared.WritePolicy, "test", "testset","ma_geo_index","gjsn","as.GEO2DSPHERE")


	})
	fmt.Println("\t \t \t \t The records are wriiten !!")

}

func runOptimal_Location(client *as.Client){}

func PanicOnError(err error){
	if err != nil{
		panic(err)
	}
}
`

**Comment by khaf** [comment]
Your question is unrelated to this issue. Please file a new issue so that I can answer it there.
