### ISSUE TITLE
Node discovery from seed does not work when using UseServicesAlternate

### ISSUE THREAD

**Issue by fuzzycow** [aerospike/aerospike-client-go#131]
I believe that node discovery from seed addresses does not work with UseServicesAlternate.

The reason could be:
*  node.Refresh() will fetch ETHER "services" OR "services-alternate", depending on UseServicesAlternate flag, and store just one of those in infoMap. 
* node.addFriends(infoMap) will only check the "services" in infoMap. 
I think with UseServicesAlternate==true  addFriends(infoMap) should check "services-alternate" in infoMap.

**Comment by khaf** [comment]
Thanks. Will have a look and fix in the next release.

**Comment by khaf** [comment]
Fix is the master. Let me know in case you encounter other issues.

**Comment by fuzzycow** [comment]
Thank you! The fix resolved the issue.
