### ISSUE TITLE
QueryObjects results in empty object

### ISSUE THREAD

**Issue by k0r8i** [aerospike/aerospike-client-go#133]
Hi there!
I try to run a QueryObjects-call on a secondary index "i" which is correclty set (checked with aql).
When setting bins with PutBins(...) followed by calling QueryObjects, returned chan ptrs result in empty objects. Somehow bins don't get marshaled as expected.
I did prepare a tiny sample function which should describe the problem in detail:

```
type TestStrct struct {
	ID  int64  `as:"i"`
	Key string `as:"k"`
}
```

```
func (this *s) Test() {

	BIN_KEY := "k"
	BIN_ID := "i"
	KEY := "someKey"
	this.Key, _ = as.NewKey(this.Namespace, this.SetName, KEY)
	//Procedure succeeds
	if err := this.Client.PutBins(nil, this.Key, as.NewBin(BIN_ID, 1), as.NewBin(BIN_KEY, KEY)); err != nil {
		panic(err)
	}

	r, err := this.Client.Get(nil, this.Key, BIN_ID, BIN_KEY)
	if err != nil {
		panic(err)
	}
	log.Print("Just bins: ", r.Bins)

	st := as.NewStatement(this.Namespace, this.SetName)
	st.Addfilter(as.NewEqualFilter(BIN_ID, 1))
	ch := make(chan *TestStrct, 10)

	this.Client.QueryObjects(nil, st, ch)
	for v := range ch {
		log.Print("Querying objects: ", *v)
	}

	o := &TestStrct{}
	if err := this.Client.GetObject(nil, this.Key, o); err != nil {
		panic(err)
	}
	log.Print("Simple getObject-call: ", *o)

	ch = make(chan *TestStrct, 10)
	this.Client.QueryObjects(nil, st, ch)
	for v := range ch {
		log.Print("Querying objects again: ", *v)
	}

}

```
It prints:
2016/06/18 17:01:16 Just bins: map[k:someKey i:1]
2016/06/18 17:01:16 Querying objects: {0 }
2016/06/18 17:01:16 Simple getObject-call: {1 someKey}
2016/06/18 17:01:16 Querying objects again: {1 someKey}

I'd expect to get a valid object with first QueryObjects(...)-call as well.
It seems like some sort of syncMap-issue to me since - after using getObject,
the same QueryObject(...)-query returns all expected values.
Any hints?

Cheers
Korbi

**Comment by k0r8i** [comment]
... just a quick-and-dirty solution I came up with:
client.go, approx. line 1115 ->
```
func (clnt *Client) QueryObjects(policy *QueryPolicy, statement *Statement, objChan interface{}) (*Recordset, error) {
	policy = clnt.getUsableQueryPolicy(policy)
	x := reflect.New(reflect.ValueOf(objChan).Type().Elem().Elem())
	cacheObjectTags(indirect(x))
	nodes := clnt.cluster.GetNodes()
	if len(nodes) == 0 {
		return nil, NewAerospikeError(SERVER_NOT_AVAILABLE, "Query failed because cluster is empty.")
	}
```

**Comment by khaf** [comment]
Hi! Thanks for finding the bug and a solution. I took a bit of a different route to resolve it though.

The fix is in master. Feel free to close the issue, or report back any other issues you encounter.

Cheers,
K.

**Comment by k0r8i** [comment]
Grrreat! Thanks for the quick fix!

Cheers
Korbi
