### ISSUE TITLE
Marshalling of BinMap to JSON fails

### ISSUE THREAD

**Issue by ameykpatil** [aerospike/aerospike-client-go#134]
I have data in my aerospike which is like -  
```javascript
{
    "posts": [
      {
        "authUid": "222-tw",
        "text": "Hey yo",
        "images": [
          {
            "high": "https://c5740aedb0-1600.png",
            "small": "https://11e6-964c-f395740aedb0-320.png",
            "guid": "635c0e79-892b-438e-a012-78235c0da37d",
            "medium": "https://7854-481eb7f0-41a9-11e6-964c-f395740aedb0-640.png"
          }
        ],
        "_id": "5779f5e70616362133b3605a",
        "createdAt": 1467610599432,
        "createdBy": "9d4614b1-9751-41a0-a954-3c42e0ff7854"
      }
    ]
  } 
```

But when I fetch the data & try to marshal the bins, 
```go
spikeKey, _ := as.NewKey("test", "test_set", key)
rec, _ := cli.Get(nil, spikeKey)
jsonRec, e := json.Marshal(rec.Bins)
```
It is giving me error as
`json: unsupported type: map[interface {}]interface {}`

As per docs type of BinMap is `map[string]interface{}`
https://godoc.org/github.com/aerospike/aerospike-client-go#BinMap

**Comment by khaf** [comment]
What you have in your record is a couple of arrays of maps (`posts` and `images`); maps in a record can have any key type, and are not restricted to `string` keys. As a result, the client returns them as `map[interface{}]interface{}`.

You have two ways to work around this problem:

1. The easy way: convert the `binMap` to strict `map[string]interface{}`. This is slow and memory intensive, but may work well for an app that is not supposed to be very high-perf.
2. Make a new type and implement the [`Marshaler`](https://golang.org/pkg/encoding/json/#Marshaler) interface for it:
```go
type MyType BinMap

// implement marshaller
func (mt *MyType) MarshalJSON() ([]byte, error) {
...
}

spikeKey, _ := as.NewKey("test", "test_set", key)
rec, _ := cli.Get(nil, spikeKey)
jsonRec, e := json.Marshal(MyType(rec.Bins))
```

**Comment by khaf** [comment]
You can also use tagged structs and `GetObject()` to retrieve the data.

**Comment by ameykpatil** [comment]
For the ones that might have similar issue, I just wrote a function which will traverse through `BinMap` & recursively converting `map[string]interface{}`, `map[interface{}]interface{}` & `[]interface{}`
P.S. This might be inefficient solution.
