### ISSUE TITLE
Will the policy AS_POLICY_REPLICA_ANY be supported ?

### ISSUE THREAD

**Issue by absolute8511** [aerospike/aerospike-client-go#137]
I saw the replica policy  `AS_POLICY_REPLICA_ANY` has already been supported in c client and Java client for a long time. Is there any policy in golang SDK?

Thanks.

**Comment by khaf** [comment]
Not yet, but coming soon (ETA: under 2 weeks)

**Comment by absolute8511** [comment]
That will  be great! Thanks

**Comment by khaf** [comment]
You can now use `ClientPolicy.RequestProleReplicas` and `Policy.ReplicaPolicy` in `v1.17.0`.
