### ISSUE TITLE
Problems with running record UDFs on secondary index

### ISSUE THREAD

**Issue by blind-oracle** [aerospike/aerospike-client-go#140]
I have a set with an indexed (numeric) bin, queries on that bin work fine, i'm getting correct results.

However, if i'm trying to run UDF against this set (ExecuteUDF) with an EqualFilter in statement that filters by this bin - i'm getting strange results. It seems that the server is running UDF not only against the records that match query, but on some(?) others too (i'm passing a bin value as an argument to UDF and checking it against rec["bin"] for equality). PK-based UDF query (Execute) seem to work fine, however.

AQL does not have the ability to execute UDFs against secondary index, only on PK or whole set scan, so i can't check that.

Am i doing something wrong? Thanks in advance.

Go 1.6.2. Go aerospike client is latest github version, Aerospike is latest 3.9.0.1

**Comment by khaf** [comment]
You aren't doing anything wrong, things should work as expected.

Are you able to share a short code snippet that can reproduce the issue?

**Comment by khaf** [comment]
I can't reproduce this. It will execute on age == 20, and set that field to -1 if it wasn't as expected. You can check the results via aql.

How many nodes do you have? Do you have migrations going on when running your code? Have you tried to rebuild your index to see if the problem goes away? (Don't do this on production systems without consulting the documentation)

Here's my snippet.

```go
package main

import (
	"fmt"
	"log"
	"math/rand"
	"runtime"

	as "github.com/aerospike/aerospike-client-go"
)

var client *as.Client

const udfBody = `function testFunc1(rec, val)
   if rec['age'] ~= val then
	   	info('Didnt match...')

	   	rec['age'] = -1
	   	aerospike:update(rec)
	end
end`

func main() {
	runtime.GOMAXPROCS(runtime.NumCPU())

	fmt.Println("Connecting...")

	var err error
	client, err = as.NewClient("ubvm", 3000)
	if err != nil {
		log.Fatalf("Error creating aerospike client: %+v\n", err)
	}

	regTask, err := client.RegisterUDF(nil, []byte(udfBody), "udfEcho.lua", as.LUA)
	if err != nil {
		panic(err)
	}
	// wait until UDF is created
	err = <-regTask.OnComplete()
	if err != nil {
		panic(err)
	}

	put(1e4)
	query()

	fmt.Println("done.")
}

func put(times int) {
	for i := 0; i < times; i++ {
		key, _ := as.NewKey("test", "test", i)
		err := client.Put(nil, key, as.BinMap{"name": "K", "age": 20 + rand.Intn(10)})
		if err != nil {
			log.Println(err)
		}
	}
}

func query() {
	stmt := as.NewStatement("test", "test")
	stmt.Addfilter(as.NewEqualFilter("age", 20))
	championSet, err := client.ExecuteUDF(nil, stmt, "udfEcho", "testFunc1", as.NewValue(20))
	if err != nil {
		log.Printf("Error ExecuteUDF: %+v\n", err)
	}

	err = <-championSet.OnComplete()
	if err != nil {
		log.Printf("Error ExecuteUDF: %+v\n", err)
	}

}
```

**Comment by blind-oracle** [comment]
Well, it seems i have some strange problems. I think that the problem lies in int64 type and large number that i use,

I've slightly modified your example to match my namespace and changed the types to int64:
```
package main

import (
    "fmt"
    "log"
    "math/rand"
    "runtime"
    
    as "github.com/aerospike/aerospike-client-go"
)

const (
    VALUE = 0xFFFFFFEFFFFF
)

var client *as.Client

const udfBody = `function testFunc1(rec, val)
   if rec['age'] ~= val then
        info('Didnt match: ' .. tostring(val) .. ' vs. ' .. rec['age'])

        rec['age'] = -1
        aerospike:update(rec)
    end
end`

func main() {
    runtime.GOMAXPROCS(runtime.NumCPU())

    fmt.Println("Connecting...")

    var err error
    client, err = as.NewClient("10.1.241.91", 3000)
    if err != nil {
        log.Fatalf("Error creating aerospike client: %+v\n", err)
    }

    regTask, err := client.RegisterUDF(nil, []byte(udfBody), "udfEcho.lua", as.LUA)
    if err != nil {
        panic(err)
    }
    
    // wait until UDF is created
    err = <-regTask.OnComplete()
    if err != nil {
        panic(err)
    }

    put(1e4)
    query()

    fmt.Println("done")
}

func put(times int) {
    for i := 0; i < times; i++ {
        key, _ := as.NewKey("onlinedb", "test", i)
        err := client.Put(as.NewWritePolicy(0, 60), key, as.BinMap{"name": "K", "age": int64(VALUE + rand.Intn(100))})

        if err != nil {
            log.Println(err)
        }
    }
}

func query() {
    stmt := as.NewStatement("onlinedb", "test")
    stmt.Addfilter(as.NewEqualFilter("age", int64(VALUE)))
    championSet, err := client.ExecuteUDF(nil, stmt, "udfEcho", "testFunc1", as.NewValue(int64(VALUE)))
    if err != nil {
        log.Printf("Error ExecuteUDF: %+v\n", err)
    }
    
    err = <-championSet.OnComplete()
    if err != nil {
        log.Printf("Error ExecuteUDF: %+v\n", err)
    }
}
```

And after running the program in the logs on the nodes i get this:
```
Jul 26 2016 19:48:19 GMT: INFO (udf): ([C]:-1) Didnt match: 2.8147497566208e+14 vs. 2.8147497566217e+14
Jul 26 2016 19:48:19 GMT: INFO (udf): ([C]:-1) Didnt match: 2.8147497566208e+14 vs. 2.8147497566217e+14
Jul 26 2016 19:48:19 GMT: INFO (udf): ([C]:-1) Didnt match: 2.8147497566208e+14 vs. 2.814749756621e+14
Jul 26 2016 19:48:19 GMT: INFO (udf): ([C]:-1) Didnt match: 2.8147497566208e+14 vs. 2.8147497566211e+14
Jul 26 2016 19:48:19 GMT: INFO (udf): ([C]:-1) Didnt match: 2.8147497566208e+14 vs. 2.8147497566211e+14
Jul 26 2016 19:48:19 GMT: INFO (udf): ([C]:-1) Didnt match: 2.8147497566208e+14 vs. 2.8147497566217e+14
Jul 26 2016 19:48:19 GMT: INFO (udf): ([C]:-1) Didnt match: 2.8147497566208e+14 vs. 2.8147497566217e+14
```
With 0xFFFFFFDFFFFF as VALUE it works fine :)

After this i've gone out and read about LUA's internal number representation, which is a float actually :(
And i have to use special objects ( to handle int64s. Is it possible with Aerospike's LUA to pass real int64 to LUA and work with it?

**Comment by blind-oracle** [comment]
Well, i'm taking my question back - it seems that i've not read the Lua & Aerospike limitations chapter thoroughly - passing full 64-bit integers isn't possible now, sad

**Comment by khaf** [comment]
That is correct unfortunately, it is not possible to work with 64bit integers in Lua 5.1. But you may be able to use [bytes API](http://www.aerospike.com/docs/udf/api/bytes.html) instead.

**Comment by blind-oracle** [comment]
Thanks, i'll give it a try.
I need an indexed type, so it should be int or string as far as i understand.

PS:
1. Is there anything i can do about the error "Error code (115) not available yet - please file an issue on github" from client in response to ExecuteUDF()? Should i open another issue for it?

2. And last question - as far as i understand it isn't possible to return values from UDFs when running them with ExecuteUDF()?

**Comment by khaf** [comment]
What I meant was that you keep your data as is, but work with them in UDF as byte values instead of direct int64 value.

No need for a new issue, thanks for reporting the missing error code.

That is correct. You need `QueryAggregate` for that, but then you won't be able to update data in that case.
