### ISSUE TITLE
Making never expiring records

### ISSUE THREAD

**Issue by cheriksoft** [aerospike/aerospike-client-go#141]
I'm writing records, which never expire. In the bottom of this official manual page - http://www.aerospike.com/docs/client/go/usage/kvs/write.html it's clearly stated that I have to set `writePolicy.Expiration = -1` for infinite TTL. But doing such, I get a compilation error `constant -1 overflows uint32`. Obviously, there is an error either in manual or in Aerospike client.

**Comment by khaf** [comment]
You are right, docs need to be fixed.

Set it to `math.MaxUint32`
