### ISSUE TITLE
Failed to connect to host(s)

### ISSUE THREAD

**Issue by davidhendi** [aerospike/aerospike-client-go#144]
i get the following error when trying to connect to aerospike running on localhost: 
     Failed to connect to host(s): [localhost:3000]; error: Failed to connect to host(s): [localhost:3000]. The network connection(s) to cluster nodes may have timed out, or the cluster may be in a state of flux."

If i use the local host IP (127.0.0.1) i don't get this error. the problem seems to be the "net.LookupHost(host.Name)" function inside "func (ndv *nodeValidator) setAliases(host *Host) error" returns 3 results [::1 fe80::1%lo0 127.0.0.1].  The client then tries to connect to "::1:3000" and fails as ipV6 is not enabled. 

Given the multiple results, the client should either try each connection until it finds one it can connect to, or use IPV4 as the default.

**Comment by khaf** [comment]
Thanks for your report. Will look into it and fix it in the next release.

**Comment by khaf** [comment]
The fix is in master. Please don't hesitate to file newer issues in case you encounter other problems.
