### ISSUE TITLE
Cannot insert GeoJSON data 

### ISSUE THREAD

**Issue by DasAng** [aerospike/aerospike-client-go#145]
I'm trying to insert GeoJSON data in the form of lattitude and longitude but it looks like the feature is not supported?

````
func panicOnError(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {

client, err := NewClient("localhost", 3000)
panicOnError(err)

key, err := NewKey("test", "aerospike", "key")
panicOnError(err)

geo := NewGeoJSONValue("{'type':'Point', 'coordinates': [55.6728087,12.557570400000031]}")
bin := NewBin("geobin",geo)
err = client.PutBins(nil,key,bin)
panicOnError(err)

}
````

I get the following error when calling `client.PutBins`

`Error code (160) not available yet - please file an issue on github.`

Am I doing something wrong here or is this not yet supported?

**Comment by DasAng** [comment]
Im running the latest Aerospike server 3.9.1.1. So Geospatial should be supported by the server. I have tried to use the NodeJS client library against the server and it inserted the data without issue. So maybe this is not possible with this Go library? Or maybe the way I am inserting is not correct?

**Comment by khaf** [comment]
That error code means you are trying to insert an invalid GeoJson string. Please check your string and make sure it is the same as the one in Nodejs example.

I'll include the proper error strng message in the next release.

**Comment by khaf** [comment]
this is how your string should look like:

```go
geo := NewGeoJSONValue("{\"type\":\"Point\", \"coordinates\": [55.6728087,12.557570400000031]}")
```

**Comment by DasAng** [comment]
Thanks I just realized that too. Thanks for your quick reply :).
