### ISSUE TITLE
Add a vet mode to test for suboptimal usage

### ISSUE THREAD

**Issue by wellle** [aerospike/aerospike-client-go#146]
As discussed it would be nice to have a way to set up the client in tests so that it would complain if it recognizes that it's used in a way that could be improved by implementing certain interfaces for example.

And it could be done in multiple modes:
1. Do nothing (default)
2. Log about problems
3. Panic on every problem (hard mode)

Thank you!

**Comment by khaf** [comment]
The new release takes care of this. I'll follow up tomorrow regarding other changes.
