### ISSUE TITLE
GetObject not working

### ISSUE THREAD

**Issue by blitzprog** [aerospike/aerospike-client-go#148]
I populated the database via the node.js aerospike client and tried to read a single record in Go.

This works:
```go
record, _ := client.Get(nil, key)
log(record.Bins["id"])
```

This doesn't work:
```go
type User struct {
	id int
}

user := &User{}
client.GetObject(nil, key, user)
log(user.id)
```

`user.id` is always 0. The `error` return value is `nil`. The object has more bins than just `id` but I expected this to work anyway (else it'd be a very restricted feature). Adding `as:"id"` doesn't change the outcome.

Am I doing something wrong?

**Comment by blitzprog** [comment]
Nevermind, I'm coming from node.js and didn't know that lowercase/uppercase for field names was significant for reflection in Go.

In case anyone else stumbles here, I fixed it by changing the struct field to:
```go
ID          int    `as:"id"`
```

This is not really DRY but I guess there's no way around it.

**Comment by khaf** [comment]
It's not just reflection, since it also indicates if the field is public or private outside of its own package. Since reflection is outside of that package, it cannot access that field by design.
