### ISSUE TITLE
Configurable tag in marshal.go

### ISSUE THREAD

**Issue by blitzprog** [aerospike/aerospike-client-go#149]
Currently `aerospikeTag` is defined as a constant in `marshal.go`.

I would guess that most people who serialize their data into the database keep the same attribute names as in their JSON output for the REST API. Therefore it makes sense to let aerospike use the already defined json tags from a DRY perspective.

Would it be possible to add a function like `SetTag("json")` to overwrite the default tag?

**Comment by khaf** [comment]
Good idea! Let me think about a bit before including it in the lib.

Feedback from others is welcome.

**Comment by khaf** [comment]
The change is released.

**Comment by blitzprog** [comment]
Confirmed it's working, thank you very much @khaf !

**Comment by khaf** [comment]
No problem :)
