### ISSUE TITLE
ttl=MaxUint32 in db turns into values about 0xf329be2d in Expiration

### ISSUE THREAD

**Issue by powerman** [aerospike/aerospike-client-go#150]
Such (about 0xf329be2d) value is returned by TTL(0), see https://github.com/aerospike/aerospike-client-go/blob/master/types/epoc.go#L13 - probably it should handle argument==0 as special case and returns MaxUint32.

**Comment by khaf** [comment]
Thanks for your report. I'll fix it for the next release.
