### ISSUE TITLE
Some Question About : AggregateFunction in   "aerospike-client-go"

### ISSUE THREAD

**Issue by figoxu** [aerospike/aerospike-client-go#154]
Same Lua Code   
Same parameter
Excecute In Different Environment. One Environment Is  "aql" ,Another Environment is "aerospike-client-go"
The Result Is Deferent

![aqlclient](https://cloud.githubusercontent.com/assets/10055828/20341870/07a7116a-ac23-11e6-9ebe-471b76975b89.png)

The Same Script In Aql ,Result Always Same.
But In  "aerospike-client-go" . Result Always Different .
There Is Any Problem With My Source Code ?
golang code is 

```go
stm.SetAggregateFunction("figo", "figoSample", []as.Value{as.NewValue(getTimeTick(dayInt))}, true);

rs, err := ac.Query(nil, stm);

for res := range rs.Results() {

	if res.Err != nil {

		fmt.Println("res.Err", res.Err)

	} else {

		bins := res.Record.Bins["SUCCESS"]

		log.Println("@bins:", bins)

	}

}
```

lua code is 

```lua
function figoSample(s,lastTime)

        local function filter(record)

                local mt=0

                if record.mt ~=nil then

                        mt = record.mt

                end

                return mt > lastTime

        end

        function mapper(rec)

            return 1

        end

        local function reducer(v1, v2)

            return v1 + v2

        end

        return s :filter(filter) : map(mapper) : reduce(reducer)

end
```

**Comment by khaf** [comment]
Yes, you are using `Query` method instead of `QueryAggregate`. Aggregation has a pipeline on client-side as well.

```go
rs, err := client.QueryAggregate(nil, stm, "figo", "figoSample", getTimeTick(dayInt))
```

Please let me know how it goes.

**Comment by figoxu** [comment]
Thanks .  As Your Advice , It Works Fine .
![testresult](https://cloud.githubusercontent.com/assets/10055828/20378206/86d92642-accf-11e6-98bb-57c0bc4b3516.png)

**Comment by figoxu** [comment]
As I User  QueryAggregate  API 
'

rs, err := client.QueryAggregate(nil, stm, "figo", "figoSample", getTimeTick(dayInt))

'
,It Cause The Error As Following

![error](https://cloud.githubusercontent.com/assets/10055828/20379694/9751f996-acd8-11e6-823e-4e95fb2c566e.png)


But ,As I Write The Code In An  Strange Way , It  Can Works By The Following Code :
'

	rs, err := ac.Query(nil, stm)

	ac.QueryAggregate(nil,stm,figoSample,getTimeTick(dayInt))


'


![testresult](https://cloud.githubusercontent.com/assets/10055828/20378206/86d92642-accf-11e6-98bb-57c0bc4b3516.png)

**Comment by khaf** [comment]
You second example doesn't run in an strange way. You are reading the results of the `Query` method, and disregard the results of the `QueryAggregate`.

Aerospike Aggregation works as follows:
- The Filter and Map phase and single step of Reduction is done on the server-side.
- The results per each partition are sent to the client, and the rest of the reductions are done on client side.

This implies that you need to have our lua functions on both server and client side.

To do this, you need to have a directory in your app called e.g `udf`,  put the `figo.lua` in that dir, and then:

```go
	// Set LuaPath (where you have have your UDF functions)
	luaPath, _ := os.Getwd()
	luaPath += "/udf/"
	as.SetLuaPath(luaPath) // this line tells the client library where your lua files are on client-side
```

Now you will be able to use your first example and you won't get any errors.

**Comment by figoxu** [comment]
As Your Advice , My Question Was Solved  .  Thanks
