### ISSUE TITLE
Missing BatchGetObject function

### ISSUE THREAD

**Issue by blitzprog** [aerospike/aerospike-client-go#155]
There is a little inconsistency because we have Get & GetObject but there is no equivalent for BatchGet. Would it be possible to implement this to improve the consistency of the Aerospike Go API?

**Comment by khaf** [comment]
Yes, I'll put it on my list, though it will take some time to materialize.

**Comment by nctusdk** [comment]
+1, looking for the same API but missing.

**Comment by venilnoronha** [comment]
I'm kinda new here, but I wanted to give it a shot. Could you give me some direction as to what's to be done?

Thanks!

**Comment by khaf** [comment]
Sorry for the wait. The API is in the master now.

**Comment by blitzprog** [comment]
Thank you!

I just wanted to try the new function but I'm getting the following compile time error:
```
Cache.go:28: cannot use myObjects (type []*MyObject) as type []interface {} in argument to client.BatchGetObjects
```

I also found this wiki page which describes the problem:
https://github.com/golang/go/wiki/InterfaceSlice

How is the function supposed to be used?

**Comment by blitzprog** [comment]
I managed to get it to work but the solution (1 object slice + 1 pointer slice + 1 interface slice) seems very weird:

https://github.com/aerogo/aerospike/blob/master/Database.go#L144-L181

I think the API could be improved by making it `interface{}` instead of `[]interface{}`.

**Comment by khaf** [comment]
Sorry Eduard, I just saw your question. You can always find the usage of function in the tests.

In this case, the reason the method requires `[]interface{}` instead of `interface{}` is that in that case we'd need to use reflection inside the library to traverse that array.
