### ISSUE TITLE
Expose Error and ErrorCode

### ISSUE THREAD

**Issue by bpaquet** [aerospike/aerospike-client-go#157]
Expose error and ErrorCode const to allow a better error handling in client. The only current solution I found is something like ``err.Error() == 'Hot key'``, which is not very efficient and reliable.

**Comment by bpaquet** [comment]
I can do something like ``err.(types.AerospikeError).ResultCode()``, but it is still not very lean.

**Comment by khaf** [comment]
In go, it is idiomatic to do this:

```go
import ast "github.com/aerospike/aerospike-client-go/types"

...

if aerr, ok := err.(ast.AerospikeError); ok {
   switch aerr.ResultType() {
       case ast.HOT_KEY: ...
   }
}
```
