### ISSUE TITLE
Is this library support connection pooling?

### ISSUE THREAD

**Issue by kokizzu** [aerospike/aerospike-client-go#158]
For example if i have 5000 connections/web requests per second, and each one need to check aerospike for the session, would it be a bottleneck just like redis?

**Comment by kokizzu** [comment]
Nevermind, I should read the "best practice" part of the documentation :3

> Use only one Client object in your application — Client objects pool connections and synchronize their inner functionality. They are goroutine friendly. Use only one Client object in your application and pass it around.

**Comment by khaf** [comment]
I'm curious, what do you mean by redis becoming the bottleneck? Does it not pool the connections?

**Comment by kokizzu** [comment]
Hi, it does, but still 70% of the runtime comes on syscal when redis client creating connection

http://stackoverflow.com/questions/40784070/how-to-profile-golang-web-app-server
