### ISSUE TITLE
Result of ScanAll doesn't return user key

### ISSUE THREAD

**Issue by zean00** [aerospike/aerospike-client-go#160]
Hi,

I'm using `ScanAll` and iterate through the result set, but when I try to access the key through
`res.Record.Key.Value().String()`
it's resulting nil reference and causing panic

If I just print out the `res.Record.Key` it seems like the userkey is missing
```adex:unprocessed::11 81 9d 58 e0 72 68 5a 63 38 08 77 ce aa dc f7 ce cd 6a bc ```

Compared to the output from `Get` directly, the key would show
```adex:unprocessed:detikinet.438.1456.350.130:11 81 9d 58 e0 72 68 5a 63 38 08 77 ce aa dc f7 ce cd 6a bc ```

**Comment by khaf** [comment]
You mean you have stored the key via `WritePolicy.SendKey` when putting the record in, and while fetching using `Get` it shows up and the same exact key does not return its original user key during `Scan`?

This behavior is tested in https://github.com/aerospike/aerospike-client-go/blob/master/scan_test.go#L53 for most possible situations.

If it definitely doesn't work in your case, could you please give me a bit more information about your server build, edition and config, and maybe provide a code snippet that reproduces the issue?

**Comment by zean00** [comment]
Hi,

It's work, I miss the `WritePolicy.SendKey` when saving the record. I don't know why this behaviour is not enabled by default, but I think you should write it somewhere to explain this behaviour and how to turn it on / off . Put it on sample / test is fine , but at least you should tell where we should look for it (this is confusing for someone new with aerospike) 

Thanks anyway.

**Comment by khaf** [comment]
Aerospike is all about sheer performance, so every byte that we put on the wire counts, and we let users to decide.

Thanks for your feedback, I'll definitely improve the documentation to reflect your suggestions.
