### ISSUE TITLE
some questions about Aggregation function

### ISSUE THREAD

**Issue by zhaijian** [aerospike/aerospike-client-go#162]
we use a  3 nodes aerospike cluster in LAN.
i want to count active user (day,week and month) by Aggregation function.
when the number of the objects less then 1 Million,the stat is ok and quick,
but if the numbers large then 1 Million,It took about 10s and the stat info is wrong!(both day/week/month active user is 0,but is not)
this is my lua script:

       function statUser(s,tick,tp)
		local function filter(record)
			return (record.tp == tp) and (record.ignore ~= 1)
		end
		local function addValues(statMap,record)
			if statMap['au'] == null then
				statMap['au'] = 0
			end
			statMap['au'] = statMap['au'] + 1
			if record.mt == null then
				return statMap
			end
			if record.mt > (tick-60*60*24*1000) then
				if statMap['dau'] == null then
					statMap['dau'] = 0
				end
				statMap['dau'] = statMap['dau'] + 1
			end
			if record.mt > (tick-60*60*24*1000*7) then
				if statMap['wau'] == null then
					statMap['wau'] = 0
				end
				statMap['wau'] = statMap['wau'] + 1
			end
			if record.mt > (tick-60*60*24*1000*30) then
				if statMap['mau'] == null then
					statMap['mau'] = 0
				end
				statMap['mau'] = statMap['mau'] + 1
			end
			return statMap
		end
		local function statMerge(a,b)
                        return a+b
                end
		local function reduceValues(a,b)
			return map.merge(a,b,statMerge)
		end
		return s : filter(filter) : aggregate(map(), addValues) : reduce(reduceValues)
	end

this is my golang code:

        stm := as.NewStatement(NS_PUSH, SET_DV)
	stm.Addfilter(as.NewEqualFilter("app", app))
	rs, err := ac.QueryAggregate(nil, stm, LUA_NAME, "statUser", tick, tp)
	if err != nil {
		return nil, err
	}
	r := <-rs.Results()
	if r == nil {
		return nil, fmt.Errorf("not found %s ", app)
	}
	if r.Err != nil {
		return nil, r.Err
	}

	bins, ok := r.Record.Bins["SUCCESS"].(map[interface{}]interface{})
	if !ok {
		return nil, errors.New("find_dv_by_tp_err: aerospike query err")
	}

	activeUser := &ActiveUser{}
	activeUser.Au = parseInt(bins["au"])
	activeUser.Dau = parseInt(bins["dau"])
	activeUser.Wau = parseInt(bins["wau"])
	activeUser.Mau = parseInt(bins["mau"])

**Comment by khaf** [comment]
I can't reproduce this. Are you sure you are passing the right arguments to the udf function?

Here's the improved Lua function I'm using (you can copy/paste yours, no difference):

```lua
function statUser(s,tick,tp)

	local dus = 60*60*24*1000
	local wus = dus*7
	local mus = dus*30

	local function filter(record)
		return (record.tp == tp) and (record.ignore ~= 1)
	end

	local function addValues(statMap,record)
		statMap['au'] = (statMap['au'] or 0) + 1

		if record.mt == null then
			return statMap
		end

		if record.mt > (tick-dus) then
			statMap['dau'] = (statMap['dau'] or 0) + 1
		end

		if record.mt > (tick-wus) then
			statMap['wau'] = (statMap['wau'] or 0)+ 1
		end

		if record.mt > (tick-mus) then
			statMap['mau'] = (statMap['mau'] or 0) + 1
		end

		return statMap
	end

	local function statMerge(a,b)
        return a+b
    end

	local function reduceValues(a,b)
		return map.merge(a,b,statMerge)
	end

	return s : filter(filter) : aggregate(map(), addValues) : reduce(reduceValues)

end
```

```go
package main

import (
	"errors"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"os"
	"sync"
	"time"

	. "github.com/aerospike/aerospike-client-go"
)

// flag information
var host = flag.String("h", "127.0.0.1", "Aerospike server seed hostnames or IP addresses")
var port = flag.Int("p", 3000, "Aerospike server seed hostname or IP address port number.")
var namespace = flag.String("n", "test", "Aerospike namespace.")
var set = flag.String("s", "testset", "Aerospike set name.")
var recordCount = flag.Int("rc", 2000000, "Test Record Count")
var skipPut = flag.Bool("skip", false, "Skip generating test data")
var tick = flag.Int("tick", int(time.Now().Unix()), "tick")

func main() {
	flag.Parse()
	log.SetOutput(os.Stdout)
	// log.SetFlags(0)

	// connect to the host
	client, err := NewClientWithPolicy(nil, *host, *port)
	if err != nil {
		log.Fatalln(err.Error())
	}

	defer client.Close()

	// Set LuaPath
	luaPath, _ := os.Getwd()
	luaPath += "/"
	SetLuaPath(luaPath)

	const LUA_NAME = "agg_test"
	rt, err := client.RegisterUDFFromFile(nil, luaPath+LUA_NAME+".lua", LUA_NAME+".lua", LUA)
	if err != nil {
		log.Fatalln(err.Error())
	}

	<-rt.OnComplete()

	// irt, err := client.CreateIndex(nil, *namespace, *set, *namespace+*set+"app", "app", STRING)
	// if err != nil {
	// 	log.Fatalln(err.Error())
	// }

	// <-irt.OnComplete()

	log.Println("Registered the UDF...")

	if !*skipPut {
		rc := *recordCount / 10
		wg := sync.WaitGroup{}
		wg.Add(10)
		for i := 0; i < 10; i++ {
			go put(&wg, client, i*rc, rc, "my_app")
		}
		wg.Wait()
		log.Println("Put all records...")
	}

	stm := NewStatement(*namespace, *set)
	stm.Addfilter(NewEqualFilter("app", "my_app"))

	tp := 1
	log.Println("tick:", *tick)

	log.Println("Aggregation beginning...")
	begin := time.Now()
	rs, err := client.QueryAggregate(nil, stm, LUA_NAME, "statUser", *tick, tp)
	if err != nil {
		log.Fatal("1 ", err)
	}

	r := <-rs.Results()
	log.Println("Aggregation took:", time.Since(begin))
	if r.Err != nil {
		log.Fatal("2 ", r.Err)
	}

	bins, ok := r.Record.Bins["SUCCESS"].(map[interface{}]interface{})
	if !ok {
		log.Fatal(errors.New("find_dv_by_tp_err: aerospike query err"))
	}

	log.Println("Aggregation Results:")
	for k, v := range bins {
		log.Printf("\t%s\t:\t%d", k, int64(v.(float64)))
	}

}

func put(wg *sync.WaitGroup, client *Client, from, keyCount int, app string) {
	defer wg.Done()

	tm := time.Now().Unix()
	keyCount += from
	var lapp string
	for i := from; i <= keyCount; i++ {
		key, _ := NewKey(*namespace, *set, i)

		lapp = app
		if rand.Int31n(10) > 5 {
			lapp = "something_else"
		}

		client.Put(nil, key, BinMap{
			"app":    lapp,
			"tp":     1,
			"ignore": 0,
			"mt":     tm - rand.Int63n(60*60*24*1000*30*2),
		})

		if i%10000 == 0 {
			fmt.Println("Records put:", i)
		}
	}
}
```

Results:

Go: (Don't run on production server, will create records)
```shell
$ go run agg.go -h ubvm -s 127.0.0.1 -rc 2000000 -tick 1480590965
2016/12/01 13:14:39 Registered the UDF...
2016/12/01 13:14:39 tick: 1480590965
2016/12/01 13:14:39 Aggregation beginning...
2016/12/01 13:14:42 Aggregation took: 3.5127314s
2016/12/01 13:14:42 Aggregation Results:
2016/12/01 13:14:42 	wau	:	140439
2016/12/01 13:14:42 	au	:	1199679
2016/12/01 13:14:42 	dau	:	20062
2016/12/01 13:14:42 	mau	:	599977
```

aql:
```shell
aql> SET TIMEOUT=10000
aql> AGGREGATE agg_test.statUser(1480590965, 1) ON test.agg where app='my_app'
+---------------------------------------------------------+
| statUser                                                |
+---------------------------------------------------------+
| {"mau":599977, "wau":140439, "au":1199679, "dau":20062} |
+---------------------------------------------------------+
1 row in set (3.569 secs)
```

**Comment by khaf** [comment]
On second thought, you may have a bug here in your code here:

```go
activeUser := &ActiveUser{}
activeUser.Au = parseInt(bins["au"])
activeUser.Dau = parseInt(bins["dau"])
activeUser.Wau = parseInt(bins["wau"])
activeUser.Mau = parseInt(bins["mau"])
```

the values in `bins` are `float64`. Put a `fmt.Println(bins)` to see what is in the `bins`.

**Comment by zhaijian** [comment]
the "parseInt" function has a bug,so i print bins and it works:
 
       
         begin := time.Now()
	 rs, err := ac.QueryAggregate(nil, stm, LUA_NAME, "statUser", tick, tp)
	....
       log.Println("app ", app, " tp ", tp, " aggregation took ", time.Since(begin), " bins ", bins)

this is my result:

       aggregation took  6.860783018s  bins  map[au:6.462313e+06]

about 650 Million objects took about 6.5s
Is the result optimistic?

**Comment by khaf** [comment]
That's 6,462,313 records :)

**Comment by zhaijian** [comment]
thanks :)
