### ISSUE TITLE
The master is error in go1.7.3

### ISSUE THREAD

**Issue by bjdgyc** [aerospike/aerospike-client-go#163]
go version go1.7.3 linux/amd64
exec: `go get github.com/aerospike/aerospike-client-go`
error: `github.com/aerospike/aerospike-client-go/client.go:300: undefined: newReadHeaderCommand`

**Comment by khaf** [comment]
I can't reproduce this on any Go version, linux or mac. 

Did you have an old version of the client already installed?

**Comment by bjdgyc** [comment]
linux: `CentOS Linux release 7.2.1511 (Core)`
uname: `Linux bogon 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
go version `go1.7.3.linux-amd64.tar.gz`
I have no old version.

command:
```
go get github.com/aerospike/aerospike-client-go
# github.com/aerospike/aerospike-client-go
../../../github.com/aerospike/aerospike-client-go/client.go:300: undefined: newReadHeaderCommand
```

**Comment by khaf** [comment]
This definitely works. I just installed fresh centos 6 and 7, and installed go and setup a GOPATH and then `go get`. Client installs successfully.

My guess is either you Go installation/upgrade went wrong, or there's a conflict in other settings.
