### ISSUE TITLE
The new Range(...) function implementations allocate heavily

### ISSUE THREAD

**Issue by fmstephe** [aerospike/aerospike-client-go#164]
We have implemented the new value_helper interfaces to avoid allocation from reflection.

```go
// MapIter allows to define general maps of your own type to be used in the Go client
// without the use of reflection.
type MapIter interface {
	Range(func(interface{}, interface{}) error) error
	Len() int
}
```

However, our implementation allocates twice for every map item.

```go
type customMap map[string]int

func (m customMap) Range(f func(k, v interface{}) error) error {
        for k, v := range m {
                if err := f(k, v); err != nil {  // Here both k and v escape to the heap
                        return err
                }
        }
        return nil
}
```

This is now the single biggest allocator in our system. Is there a way to work around these allocations.

**Comment by khaf** [comment]
There's no safe way of doing it. I'll have to let you do it the not so safe way.

**Comment by fmstephe** [comment]
From our perspective if you directly supported `map[string]int` we would avoid the interface and the reflective allocations. This would be very similar to the other `map[string]interface{}` support added in 1.20.0.

**Comment by khaf** [comment]
The problem is not reflection, since it is not used. Unfortunately every argument passed as an `interface{}` equals a heap allocation (needs to box the value), and currently the compiler doesn't optimize it out yet the way it does for byte slices and strings.

While adding one more type is not a big issue, in the end I'll need to make it as general as it can be to cover all possible type. 

I'll have to provide an API that is not 100% fool proof, but will give the control to the user. That change will come next week ~Tuesday-Wednesday with the next release.

**Comment by fmstephe** [comment]
That's not strictly true. There are a range of types which don't allocate when converted to interface{}. One of these types are maps. So converting a `map[string]int` to interface{} and then reverting it back produces no allocations.

https://groups.google.com/forum/#!topic/golang-nuts/Gi0fGlZFAVo

https://gist.github.com/fmstephe/f0e2fbd6a43b70a86ec08125684adfe3

While it is true that it is difficult/impossible to provide direct support for all possible types that could be passed in. I expect that `map[string]int` is common enough to warrant that treatment.

I look forward to seeing the new interface.

**Comment by khaf** [comment]
I just released the new version.

There examples in the documentation for your perusal, and I remain here to answer any questions you may have.

**Comment by khaf** [comment]
Did you get a chance to test the new API?

**Comment by fmstephe** [comment]
We are testing the new API right now. It looks good so far. Can you tell me if this is using the MapIter interface as intended?

```
type aeroTimeMapMap map[string]aeroTimeMap

func (m aeroTimeMapMap) PackMap(buf as.BufferEx) (int, error) {
        size := 0
        for key, val := range m {
                n, err := as.PackString(buf, key)
                size += n
                if err != nil {
                        return size, err
                }
                n, err = as.PackMap(buf, val)
                size += n
                if err != nil {
                        return size, err
                }
        }
        return size, nil
}

func (m aeroTimeMapMap) Len() int {
        return len(m)
}
```

I am unsure about the implementation of the Len() method in particular.

**Comment by fmstephe** [comment]
One further question, I would like to write unit tests to ensure that my implementations are working properly. Is there a good way to do that?

**Comment by khaf** [comment]
It is correct. You should implement this same interface for `aeroTimeMap` as well. Disable reflection using the switch to make sure only these interfaces are working.

Regarding the unit tests, the best way is to read and write the same (preferably very complex) data via two different client libraries to make sure the packing/unpacking code is not driver dependent.

**Comment by fmstephe** [comment]
How do we read and write using just one client without a local aerospike. I don't want to maintain two separate clients. I just want a way to ensure that the maps that I serialise can be deserialised back into their original form.

**Comment by khaf** [comment]
you need a local aerospike then. Take a look at `.travis.yml` to see how we automate it.

**Comment by fmstephe** [comment]
We implemented the new `Range(...)` interface and have seen a significant drop in allocation rates on our servers. Thanks.

**Comment by khaf** [comment]
Glad we finally found a solution to work around this issue.
