### ISSUE TITLE
refresh failed: `Info Command response was empty.`

### ISSUE THREAD

**Issue by allenluce** [aerospike/aerospike-client-go#170]
The code:

```
package main

import (
        aerospike "github.com/aerospike/aerospike-client-go"
        asl "github.com/aerospike/aerospike-client-go/logger"
)

func main() {
        asl.Logger.SetLevel(asl.WARNING)
        aerospike.NewClient("localhost", 3000)
}
```

When running, this is the output:

```
2016/12/20 12:25:52 Node `BB91F0D704C280A 127.0.0.1:3000` refresh failed: `Info Command response was empty.`
```

Seems to have started with d42ac06af. The local single-node server is running 3.8.1.

**Comment by khaf** [comment]
This is benign and won't affect the cluster discovery. Thanks for reporting it, I'll make changes so that the client won't try to attempt it on older servers.

**Comment by allenluce** [comment]
Yup, doesn't seem to have adverse effects. I'll look out for the commit, thanks!

**Comment by khaf** [comment]
This should be fixed by the latest commit in the master.

**Comment by allenluce** [comment]
Seems to be, thanks!
