### ISSUE TITLE
the userkey may be nil?

### ISSUE THREAD

**Issue by zhaijian** [aerospike/aerospike-client-go#175]
in the key.go：
        
         func (ky *Key) String() string {
                 if ky.userKey != nil {
		       return fmt.Sprintf("%s:%s:%s:%v", ky.namespace, ky.setName, ky.userKey.String(), Buffer.BytesToHexString(ky.digest))
	         }
	         return fmt.Sprintf("%s:%s::%v", ky.namespace, ky.setName, Buffer.BytesToHexString(ky.digest))
        }
 the userkey may be nil?

**Comment by khaf** [comment]
If you have got the key from the server (via query or scan), and you haven't kept the value of the key (`WritePolicy.SendKey = false`), the user key won't have a value, and only the digest will be known.

**Comment by zhaijian** [comment]
oh,i forget it
i use "NewKey" then print the key in other func: 
      fmt.Println(key.Value().String())
and it will not cause a null-pointer panic.
3q!

**Comment by khaf** [comment]
When you make the key yourself, the value is always stored in the key; so no surprises there.

**Comment by zhaijian** [comment]
ok,3q!
