### ISSUE TITLE
Error in PutBins  

### ISSUE THREAD

**Issue by chrisdavidy** [aerospike/aerospike-client-go#176]
I am using aerospike-go client to write to aeropsike...

errputbins := client.PutBins(writePolicy, key1, bin1, bin1,bin3)

Initially the insertion takes 5 -10ms and after 1-2 mins the insertion take around 1000-2000ms with intermittent 5-10 ms insertions.

Can you please suggest how i can get the insertions to 5ms even in load.

CodeSnippet:

            clientx, _ := as.NewClient("xxx.xxx.xxx.xxx", 3000)  
            key1, _ := as.NewKey(*shared.Namespace, *shared.Set, id)
            bin1 := as.NewBin("name1", value1)
            bin2 := as.NewBin("name2", value2)
            bin3 := as.NewBin("name3", value3)
            bin4 := as.NewBin("name4", value4)
            bin5 := as.NewBin("name5", value5)
            writePolicy := as.NewWritePolicy(0, 1200)
            errputbins := clientx.PutBins(writePolicy, key1, bin1, bin2,bin3,bin4,bin5)
             defer clientx.Close()
I am also seeing an error:

panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51e6d9]

goroutine 282 [running]: panic(0x756500, 0xc42000c0b0) /usr/local/go/src/runtime/panic.go:500 +0x1a1 github.com/aerospike/aerospike-client-go.(*Client).PutBins(0x0, 0xc420a1ea80, 0xc4209eaf00, 0xc421b1abd0, 0x6, 0x6, 0xc4209eaf00, 0x0) /root/work/src/github.com/aerospike/aerospike-client-go/client.go:153 +0x59

**Comment by khaf** [comment]
Are you making and releasing a connection object for each request? You should make only ONE client object and share it throughout your app. It take care of connection pooling and is goroutine friendly.

Does your issue occur with the following snippet?

```go
clientx, _ := as.NewClient("xxx.xxx.xxx.xxx", 3000)  

for i := 0; i < 1e7; i++ {
        // make a key based on i to avoid hot keys in benchmark
        key1, _ := as.NewKey(*shared.Namespace, *shared.Set,  i) 
        bin1 := as.NewBin("name1", value1)
        bin2 := as.NewBin("name2", value2)
        bin3 := as.NewBin("name3", value3)
        bin4 := as.NewBin("name4", value4)
        bin5 := as.NewBin("name5", value5)
        writePolicy := as.NewWritePolicy(0, 1200)
        errputbins := clientx.PutBins(writePolicy, key1, bin1, bin2,bin3,bin4,bin5)
}
```

**Comment by chrisdavidy** [comment]
Hello khaf, thanks for the  response.  
  I  use "defer clientx.Close()"  after putbins. Is this enough to  close the connection object? I create and close client object for every request to the page.

The app gets millions of hits per second. 
1. Can i create a client object and make it persist over multiple requests?
2. Lets say, Should i just use the client object from the  examples-> shared  ->shared.go?  and not create in the app?  

Appreciate your help.

**Comment by khaf** [comment]
1. You *MUST* create only one connection and share it between multiple requests. You do not need to close it, it should persist during the whole lifetime of your application.
2. You should define a package level client object, assign it when your application starts up, and use it afterwards.

**Comment by chrisdavidy** [comment]
Wow, brilliant. This has actually solve the error.

Now, can you please help with the write time( insertion through putbins) , i see it started  with 5ms  write time and as load increases (  when netstat -an |  wc -l    shows   30,000+   )  the write time to aerospike increases to 1000- 2000ms

**Comment by khaf** [comment]
I have to investigate this. Can you provide a working full code snippet that I can `go run` and test?

**Comment by khaf** [comment]
Are you setting a timeout in your policies? There are various factors included in this:

1. Number of connections inside the connection pool. This is set when connecting to the cluster in  `ClientPolicy.ConnectionQueueSize`. Increase this number for better performance.
2. `Policy.Timeout` is set to `0` by default, and may exhaust system resources with stale connections. Set a reasonable Timeout for all your operations.
3. `Policy.SleepBetweenRetries` determines the time to sleep before the next retry for a failed operation. This value is set to a very conservative number by default. Set it to a reasonable number based on your use case.

 Hope this helps.
