### ISSUE TITLE
Exponential backoff for BasePolicy

### ISSUE THREAD

**Issue by echlebek** [aerospike/aerospike-client-go#177]
Hi there,

I see that retry logic is supported by the client, but not exponential backoff. I was wondering if there was any particular reason that exponential backoff is not implemented?

Would Aerospike be receptive to a PR implementing an exponential backoff policy?

**Comment by khaf** [comment]
Hi Eric, we just haven't thought of it really.

PRs are very welcome, but we may need to take our time before merge.

Thanks,
