### ISSUE TITLE
Embedded structs in aerospike-go library unexpected behaviour

### ISSUE THREAD

**Issue by sarathsp06** [aerospike/aerospike-client-go#180]
Here is the problem explained : http://stackoverflow.com/q/41931030/1898494

**Problem**

Need to add set of common fields to all the sets ,ie CreatedAt,UpdtedAt,DeletedAt etc. For the same I have created a struct and embed that with all the set structs. I need the Fields of the common structure saved in the set as fields of the given record

Sample Code

```go
type Table struct {
   CreatedAt time.Time
   UpdatedAt time.Time
   DeletedAt time.Time
}

type Account struct {
   Table
   Name string
   Status bool
   .....
}
```
For the above mentioned struct Account.I expect the record stored with bin names

```
CreatedAt,UpdatedAt,DeletedAt,Name,Status.....
```
But when the records are stored bin names are
```
Table,Name,Status...
```
Where Table would be a map with key values

Is it possible to achieve the expected behaviour ? if so how?

**Comment by sarathsp06** [comment]
Any comments on this ??

**Comment by khaf** [comment]
Needless to say it is not supported at this time, and I'm not sure the complexity involved to support this feature is worth the effort.

I'll keep this issue open fora while to see if there are others with similar use cases.

**Comment by sarathsp06** [comment]
@khaf makes sense. It is actually the default behavior with `encode/json` and `gorm` .  So I was expecting it as the behavior in aerospike  case also .  I can contribute if it makes sense

**Comment by khaf** [comment]
We are open to pull requests :)
