### ISSUE TITLE
QueryObjects not closing the object channel when errors

### ISSUE THREAD

**Issue by clusc** [aerospike/aerospike-client-go#181]
We noticed the object channel not closing when there's some query errors(like the set name is invalid). 

```go
resChan := make(chan *internalStruct, 10)
_, err = client.QueryObjects(nil, stmt, resChan)
if err != nil {
    fmt.Errorf("failed to execute query: %v", err)
    return
}
// resChan never closes cause the program to hang
for obj := range resChan {
    fmt.Println(obj)
}
```
Some further investigation shows it is only reproducible on a multi-node cluster. For a 3 node cluster, only 2 out of 3 nodes return error [here](https://github.com/aerospike/aerospike-client-go/blob/master/client_reflect.go#L174)(and the one that doesn't return is random), causing the [counter](https://github.com/aerospike/aerospike-client-go/blob/master/recordset.go#L223) never decrement to zero(thus the `objectChannel` never get closed). I couldn't really dig deeper. Please help. Thanks

**Comment by khaf** [comment]
I guess you are discarding the recordset, and ignoring the errors that are passed to it.

Can you verify that the following code fixes the issue?

```go
resChan := make(chan *internalStruct, 10)
rcs, err = client.QueryObjects(nil, stmt, resChan)
if err != nil {
    fmt.Errorf("failed to execute query: %v", err)
    return
}

for {
    select {
        case obj := <-resChan:
            fmt.Println(obj)
        case err := <-rcs.Errors:
            fmt.Println(error)
        default:
            if !rcs.IsActive() {
                  break
            }
    }
}
```

**Comment by clusc** [comment]
It works(you will have to break out the outer loop in the not-active case though), but I find it suboptimal comparing to the idiomatic ranging through channel approach. Plus, it is strange that the error case appear 5 times in a 3 node cluster, is it normal? If it is the only proper way to use QueryObjects, please update the documentation cause it's really not that obvious. Thanks

**Comment by clusc** [comment]
Sorry I take that back. It doesn't work on a single node cluster. The `resChan` and `rcs.Errors` channels are never closing...

**Comment by khaf** [comment]
> but I find it suboptimal comparing to the idiomatic ranging through channel approach.

If you don't check for errors, you will not know if you are getting all of the records back.

I have tried several scenarios, but I cannot reproduce this issue. Can you provide a gist that reliably reproduces the issue? The channel is either always closed after the appropriate error, or should not be checked since there is an error when calling the `QueryObjects` method.

I'd appreciate it if you could provide more info regarding your environment and your database version and config.

**Comment by clusc** [comment]
Here's the gist that I can reliably reproduce the issue: https://gist.github.com/clusc/e9705ff8f78b19321a34781445e3fd3e

It seems that regardless of error or not, the `rcs.IsActive()` was always true, thus we are trapped in an infinite loop.

Env:
```
MacOS 10.12
Docker version: 1.13.1(Server running as docker container)
Aerospike server: C-3.11.1.1
Aerospike Docker images id: sha256:11b5cd3325c398645110d498f0746a9bd2bff5b2036b436520489619cd89d660
One Aerospike server node
```
Aerospike server conf:
```
# Aerospike database configuration file.

# This stanza must come first.
service {
  user root
  group root
  paxos-single-replica-limit 1 # Number of nodes where the replica count is automatically reduced to 1.
  pidfile /var/run/aerospike/asd.pid
  service-threads 4
  transaction-queues 4
  transaction-threads-per-queue 4
  proto-fd-max 15000
}

logging {

  # Log file must be an absolute path.
  file /var/log/aerospike/aerospike.log {
    context any info
  }

  # Send log messages to stdout
  console {
    context any info
  }
}

network {
  service {
    address any
    port 3000

    # Uncomment the following to set the `access-address` parameter to the
    # IP address of the Docker host. This will the allow the server to correctly
    # publish the address which applications and other nodes in the cluster to
    # use when addressing this node.
    # access-address <IPADDR>
  }

  heartbeat {

    # mesh is used for environments that do not support multicast
    mode mesh
    port 3002

    # use asinfo -v 'tip:host=<ADDR>;port=3002' to inform cluster of
    # other mesh nodes

    interval 150
    timeout 10
  }

  fabric {
    port 3001
  }

  info {
    port 3003
  }
}

namespace foo {
  replication-factor 1
  memory-size 4G
  default-ttl 0 # 5 days, use 0 to never expire/evict.

  # storage-engine memory

  # To use file storage backing, comment out the line above and use the
  # following lines instead.
  storage-engine device {
    file /opt/aerospike/data/test.dat
    filesize 20G
    # data-in-memory true # Store data in memory in addition to file.
  }
}
```

**Comment by khaf** [comment]
Thanks for the gist. Released the fix in master.

Kindly let me know if it fixes your problem.

**Comment by clusc** [comment]
Would you mind briefly describe the issue? Is it client side only or server
side also involved? Is it GeoQuery only? I am intrigued.

**Comment by khaf** [comment]
It was client-side only. 

The errors were being put on the buffered `recordset.Errors` channel multiple times. As a result at some point it would fill up and block. This would prevent the recordset channels to close, since one or more of the deferred `signalEnd()` methods would not execute.

This issue is fixed now.

**Comment by clusc** [comment]
@khaf Pulled down the latest change and noticed the following issue(same exact gist):
* In case of error(e.g. set name is wrong), the infinite loop problem is resolved, the program exist correctly. **However**, no error is received from the `rcs.Errors` channel.
* In case of success query, I am **still** seeing infinite loop problem. The object was received from `resChan` once but the channel was not closed properly. I am receiving infinite `nil` afterward.

Please help investigate.

**Comment by khaf** [comment]
Looks like there was two mistakes on my side:
1. Had forgotten to commit the change for reflection API. That is now in `master`.
2. The test snippet is wrong. You should use any of the following snippets: (you should benchmark to which is faster for your use case)

```go
	for rcs.IsActive() {
		select {
		case obj := <-resChan:
			if obj != nil {
				fmt.Printf("%+v\n", *obj)
			}
		case err := <-rcs.Errors:
			if err != nil {
				fmt.Println("ERROR:", err)
			}
		}
	}

	// this is in case all nodes returned error without sending any data back
	for err := range rcs.Errors {
		println(err.Error())
	}
```

or

```go
	for obj := range resChan {
		fmt.Printf("%+v\n", *obj)

		// read errors without blocking
		// you could leave this to after range, but then you'd have to
		// read all the results back before finding out about the error
		select {
		case err := <-rcs.Errors:
			if err != nil {
				break
			}
		default:
		}
	}

	// this is in case all nodes returned error without sending any data back
	for err := range rcs.Errors {
		println(err.Error())
	}
```

**Comment by clusc** [comment]
Confirmed the fix now works on both success and error cases. Thanks a lot for fixing it!
