### ISSUE TITLE
Initialising client takes very long

### ISSUE THREAD

**Issue by wedi-dev** [aerospike/aerospike-client-go#183]
May be it's not common issue, but for it's very inconvinient. Cluster set to listen on 0.0.0.0 (service.address) and some interfaces were blocked by VPN. Client tried to discover all hostnames within cluster and hung up for very long time. Even when it passed through somtimes it returned nil despite key existed. Code in #182 fixed the problem. 

I make PR to consider the problem.

**Comment by khaf** [comment]
Thanks for the PR. Merged.
