### ISSUE TITLE
Writing a large number of records always times out

### ISSUE THREAD

**Issue by deepakprabhakara** [aerospike/aerospike-client-go#184]
When I try to write ~2000 records I always end up with "Aerospike Error: command execution timed out: Exceeded number of retries. See `Policy.MaxRetries`. (last error: No available connections to the node. Connection Pool was empty, and limited to certain number of connections.)". Is there an example of how to batch writes to avoid this? Or rather how many can I safely write at a time so that I can then implement the batching manually on the client.

**Comment by deepakprabhakara** [comment]
Aah https://github.com/aerospike/aerospike-client-go/blob/master/tools/benchmark/benchmark.go has some nice example. Apologies for not finding it earlier.

**Comment by khaf** [comment]
No problem. Keep in mind that batch requests are run in parallel, and as such exhaust a lot more connections. Make sure to tweak the `ClientPolicy.ConnectionQueueSize` for best performance.

**Comment by deepakprabhakara** [comment]
Thanks @khaf. How about Query methods? Do they execute in parallel or just consume 1 connection? Also is there a limit to how many connections the Aerospike server can handle?

**Comment by khaf** [comment]
In Scans and Queries, you get `Policy.ConcurrentNodes` which will determine if the request will be processed in parallel or sequentially.

Aerospike servers are limited by the number of fd limit, usually 10000 per node (which you can increase)

**Comment by deepakprabhakara** [comment]
Excellent, thank you!
