### ISSUE TITLE
Query timeout when qps is high

### ISSUE THREAD

**Issue by clusc** [aerospike/aerospike-client-go#187]
Hi,

We're observing a lot of query timeout issue when request qps is high:
```
command execution timed out: Exceeded number of retries.See `Policy.MaxRetries`. 
(last error: No available connections to the node. Connection Pool was empty, and limited to certain number of connections.)
```

The problem I think is due to the `maxRetries` parameter is fixed to 0 [here](https://github.com/aerospike/aerospike-client-go/blob/master/query_policy.go#L29). What's the reason of not having retry for queries? What's the best way to overcome this kind of error?

Thanks

**Comment by khaf** [comment]
Thanks for your report. I will release the fix on Monday.

**Comment by khaf** [comment]
Fixed and released.

**Comment by clusc** [comment]
Awesome, thank you.
