### ISSUE TITLE
Unexported *Operation.OpType and *Operation.BinName caused client breakage

### ISSUE THREAD

**Issue by echlebek** [aerospike/aerospike-client-go#193]
These were exported before, and our client was relying on them. Is there a problem with having these fields exported? If not, could they please be exported again?

API breakage occurred here:

https://github.com/aerospike/aerospike-client-go/commit/a5f4822ccef5402b18bc87bf7b729f17d34a3b85

**Comment by khaf** [comment]
It is possible to re-export them again, but changing their value would not take effect for reuse since they were caching their internal representation before.

What is your use case?

**Comment by echlebek** [comment]
We're serializing and deserializing operations. BinType and BinValue are read for serialization, and set for deserialization. This is accomplished through switching on BinType and type switching on BinValue.

This allows us to write operations to a log, put them in a queue, and so on.

**Comment by klauspost** [comment]
We (used to) read the value for instrumentation.  Alternatively a "(aerospike.Operation).OpType() OperationType" would be helpful for reding it.

**Comment by khaf** [comment]
I'll try to find a way to allow these use cases.
