### ISSUE TITLE
Is there a way to query the aerospike connection pool size?

### ISSUE THREAD

**Issue by deepakprabhakara** [aerospike/aerospike-client-go#194]
Hi @khaf,

I was wondering if there is a way to query the aerospike conenction pool size? If not, it would be very useful if you could expose some operational data (including connection pool size) as expvars?

Regards.
Deepak.

**Comment by khaf** [comment]
You are setting it up yourself in the `ClientPolicy`. Or do you mean actual open connections to each node?

**Comment by deepakprabhakara** [comment]
I mean the actual number of open connections to aerospike nodes.

**Comment by khaf** [comment]
I just released the new version. You can call the `Client.Stats()` and get a detailed count. We'll add more info there over time.

**Comment by deepakprabhakara** [comment]
That is excellent, thanks @khaf. I'll give it a try when I upgrade the lib.
