### ISSUE TITLE
Connection pool size: how to block until a connection is available (with timeout)

### ISSUE THREAD

**Issue by feliksik** [aerospike/aerospike-client-go#195]
I would like to limit the Aerospike client connection pool size, but I would rather have the client block, than [returning with a ErrConnectionPoolEmpty error](https://github.com/aerospike/aerospike-client-go/blob/39b818d3a5f57ae683ab30e2eae7fe7da4519b88/node.go#L397). 

I think this will make it easier to parallellize other parts of my application code (in particular parts that spawn many write workers to to Puts and Deletes, due to the lack of BatchPut and BatchDelete). The goroutines will then just block longer on the client, if there is contention. Does this make sense? 

Of course this is not always what you want, and there is other ways: 

* let the application implement a back-off, retrying the operation. This complicates the application, but allows for better pushback (e.g. propagating a ServerTooBusy error) by our application (e.g. a webserver to a http client)
* let the application use a pool of tokens, which is equal to client's nr of MaxConnections, so the client never return such an error. This requires fetching and returning the tokens from the pool. This complicates the application. 
* implement a wrapper around the library, doing one of the above. 
* implementing a wrapper around the library, making use of asynchronous callbacks. But this seems to be non-idiomatic. 

What is the recommended way to deal with this? I am willing to make a PR in the library, to add this as a client policy feature, but only if we agree that's a sensible path.

**Comment by khaf** [comment]
Off the top of my head you can increase the number of retries, timeout and exponential back-off in tandem to get the same effect inside the library. So the variables are:

1. `policy.MaxRetries`
2. `policy.SleepBetweenRetries`
3. `policy.SleepMultiplier`
4. `policy.Timeout`

**Comment by khaf** [comment]
I'm going to go ahead and close this issue. Feel free to continue/reopen, or file a new issue.

**Comment by feliksik** [comment]
Thanks; I think I will be able to figure something out!

**Comment by khaf** [comment]
Let us know how it goes.
