### ISSUE TITLE
Do we need SetLuaPath for RegisterUDF

### ISSUE THREAD

**Issue by BlackRabbitt** [aerospike/aerospike-client-go#196]
This is not working.
```
filename := 'luaFilter'
udfBody := GenerateUDF(request.Query) // generates udf functions based on the query.
regTask, err := client.RegisterUDF(nil, []byte(udfBody), filename+'.lua', LUA)
...
stmt := NewStatement(request.Namespace, request.Set)
recordset, err := client.QueryAggregate(nil, stmt, filename, "function_in_lua", "argument1")
...
```

But this works,
```
luaPath, _ := os.Getwd()
filename := 'luaFilter'
udfBody := GenerateUDF(request.Query)
SetLuaPath(luaPath)
err := ioutil.WriteFile(filename, []byte(udfBody), 0644)
...
regTask, err := client.RegisterUDFFromFile(nil, filename+".lua", filename+".lua", LUA)
...
stmt := NewStatement(request.Namespace, request.Set)
recordset, err := client.QueryAggregate(nil, stmt, filename, "function_in_lua", "argument1")
```

> The only difference I can see is the SetLuaPath. Otherwise every other process looks fine for me. Do I need to SetLuaPath while registering udf from string as well? I am not going to write generated udf to file for each request.

And the error I get is:
```
http: panic serving [::1]:50336: runtime error: invalid memory address or nil pointer dereference
goroutine
```

**Comment by khaf** [comment]
`QueryAggregate` needs to have the lua files on the disk. You don't need to register the UDFs everytime. Register them once, and set the luaPath so that the lua interpreter can access the files.

**Comment by BlackRabbitt** [comment]
Oh, so QueryAggregate doesnot support lua file registered from RegisterUDF()?
My project needs to apply dynamic query on dynamic fields we have. So Registering them once is not the quite right solution for me. So I am generating the lua code each time for new request and wants to register it to server before applying query. Is there any workaround for achieving this?

**Comment by khaf** [comment]
`QueryAggregate` needs the UDF on both sides (client and server), required by the lua interpreter.

If what you are doing is just to run random predicates for your query, you can use predicates on the client.

If you are using map/reduce and want to have dynamic filters, use lua's meta programming features and send the field names (or the whole predicate) to your UDF to be interpreted and then executed.

**Comment by BlackRabbitt** [comment]
But from my understanding, go-client doesnot support `PredicateFilter`. Or, at-least its not here: [aerospike_docs](http://www.aerospike.com/docs/guide/client_matrix.html)

I'll definitely try with lua's meta programming feature.

**Comment by khaf** [comment]
Unfortunately that document is out of date. Go client is kept up-to-date with all of the newest features of the server. Predicate Filters are supported, and you can see examples in the tests.
