### ISSUE TITLE
Aerospike-go-cilent: High latency and Connections stuck in CLOSE_WAIT

### ISSUE THREAD

**Issue by onlynishant** [aerospike/aerospike-client-go#198]
I am trying to run a server written in Golang which internally calls aerospike client (latest version).

Initially after server start latencies measured from the client side of aerospike were under control but after some time latencies are getting high and not coming down.

Based on my observation during high latencies, many connections from aerospike client to aerospike server are in `close_wait` state

I am using **default parameters for client policy** i.e, `ConnectionQueueSize = 256` and `LimitConnectionsToQueueSize = true`

My guess is since many connections are in `close_wait` state and we are limiting connections it is waiting for connection to close and create a new one and because of that latencies are high

If that is correct, How can we close the connections faster that are in the **close_wait** state? Otherwise, What can be the reason for this?

P.S,

1. We measured latency on aerospike server (v3.12.1.2) and it was under 1ms (using asloglatency,which is as expected)
2. No Network congestion from aerospike server side as well as aerospike client side.

**Comment by khaf** [comment]
What are the operations you are using (Get, Put, Operate, Scan, Query, UDF, etc.) and what is the timeout value you are using?

**Comment by onlynishant** [comment]
BatchGet operation. We are using all default policies.

**Comment by khaf** [comment]
The default timeout value for the policies is set to zero (no timeout). 

Could you test via a reasonably short timeout like 1 seconds? You may have some stale connections.

**Comment by onlynishant** [comment]
i have checked with 2 ms timeout but that has no effect on latency. However i haven't checked CLOSE_WAIT that time.

**Comment by khaf** [comment]
I can't reproduce this issue with my tests. Do have a code snippet handy that reproduces the issue?

**Comment by onlynishant** [comment]
i have seen it on heavy load and that too after 2-3 hours interval not always. I suspect there might be some connection leak somewhere

**Comment by onlynishant** [comment]
I am testing now with 1 second timeout and close_wait keeps increasing and when it's high (much more then established count) then i see high latency.
This is the command i am using to see count -
`netstat -nalp | grep ':3000' | grep CLOSE_WAIT | wc -l`

**Comment by khaf** [comment]
Then let's try to debug the issue methodically:
1. What's your server and client version? Enterprise or Community?
2. What is your platform?
3. What is you network topology? How many nodes? What configuration? Can you share your config file?

**Comment by onlynishant** [comment]
Please find details below - 

1. server version: 3.12.1.2 Community edition
   go aerospike client : latest (commit 287df1a369f59693f4cbadedd62fe21f9f0a3de9)
2. Server configuration:

```
# Aerospike database configuration file.
service {
  user root
  group root
  paxos-single-replica-limit 1 # Number of nodes where the replica count is automatically reduced to 1.
  pidfile /var/run/aerospike/asd.pid
  service-threads 24
  transaction-queues 24
  transaction-threads-per-queue 4
  proto-fd-max 30000
  transaction-pending-limit 0
}

logging {
  # Log file must be an absolute path.
  file /var/log/aerospike/aerospike.log {
    context any info
  }
}

network {
  service {
    address 10.56.101.184
    port 3000
    access-address 10.56.101.184
  }

  heartbeat {

    mode mesh
    port 3002

    mesh-seed-address-port 10.56.101.184 3002 
    mesh-seed-address-port 10.56.101.153 3002 
    
    # ..... followed by 11 more nodes ip


    #mesh-port 3002

    # To use unicast-mesh heartbeats, remove the 3 lines above, and see
    # aerospike_mesh.conf for alternative.

    interval 150
    timeout 10
  }

  fabric {
    address 10.56.101.184
    port 3001
  }

  info {
    port 3003
  }
}

namespace test {
  replication-factor 2
  memory-size 10G
  default-ttl 30d # 30 days, use 0 to never expire/evict.

  storage-engine memory
}

#production namespace
namespace prod {
  replication-factor 2
  memory-size 50G
  default-ttl 0 # 30 days, use 0 to never expire/evict.
  high-water-disk-pct 50 # How full may the disk become before the
                               # server begins eviction (expiring records
                               # early)
  high-water-memory-pct 60 # How full may the memory become before the
                                 # server begins eviction (expiring records
                                 # early)
  stop-writes-pct 90  # How full may the memory become before
                            # we disallow new writes
  # storage-engine memory
  storage-engine device {
    #device /dev/sdb1
    #data-in-memory false

    file /opt/aerospike/data/prod.data
    filesize 1000G # 8 times of RAM
    data-in-memory true

    #write-block-size 128K   # adjust block size to make it efficient for SSDs.
    # largwst size of any object
  }
}
```
3. Machine configuration:
   client: centos-release-7-2.1511.el7.centos.2.10.x86_64 , 32 GB RAM, 40 Core
   server: centos-release-6-7.el6.centos.12.3.x86_64, 64 GB, 24 Core
  Go version on client:  version go1.7.1 linux/amd64

4. 13 node aerospike cluster, 1.5 B master object (480GB RAM used)
     14 client machine each sending ~18-20K batch read request.

**Comment by rbotzer** [comment]
You set your [`transaction-pending-limit`](http://www.aerospike.com/docs/reference/configuration#transaction-pending-limit) down to 0. Why?

**Comment by onlynishant** [comment]
that was part of initial setup. I don't know why it is set to 0. do you think that could be the reason ?
can i dynamically change it? What should be the ideal value in my case.

**Comment by rbotzer** [comment]
You might have operations on the same record being handle by different service threads on different cores at the same time. A high degree of parallelization is a big part of how Aerospike handles a high number of requests per-second with low latency. When that happens these transactions need to be lined up, and the `transaction-pending-limit` determines how many of those operations can be pending, for example as they wait on a write operation to complete. I gave a more detailed overview for this on [stackoverflow](https://stackoverflow.com/questions/44075490/aerospike-design-request-flow-internals-resources/44338136#44338136).

If you set that config param to zero, any other operation that is trying to access the record concurrently will immediately return with a [result code](https://github.com/aerospike/aerospike-client-go/blob/master/types/result_code.go) 14 KEY_BUSY. The default setting makes those operation execute in turn, extending their latency a bit, rather than failing.

**Comment by onlynishant** [comment]
I have changed `transaction-pending-limit` to 20.

`asinfo -h localhost  -v "set-config:context=service;transaction-pending-limit=20"`

Still seeing same errors.

**Comment by rbotzer** [comment]
Right, it's unrelated, but I wanted to correct that.

**Comment by onlynishant** [comment]
Ok thanks. Please check CLOSE_WAIT issue.

**Comment by khaf** [comment]
Made draft release. Could you try the code in master and see if the issue is resolved?

**Comment by onlynishant** [comment]
I tried but still seeing CLOSE_WAIT increase over the time (~2 Hours). we have same code deployed in a different data center (client machine same config and same code base, server same config only 240G meory-size and 3 node cluster. same number of keys) where load is much lower (5K/s per client machine) and CLOSE_WAIT is usually 0 there.

**Comment by khaf** [comment]
Since the new code relies on the Go's runtime to finalize the connections, it is highly unlikely that connections are being leaked in a classic manner at least. It still doesn't rule out goroutine leaks, and that's where I'll look next.

Before I do that though, can you build your app via the `-i -a` switches to make sure all dependencies are forced to recompiled from the scratch? I have seen times that updated code wasn't detected and the older compiled code was linked to the final executable.

Other than that, how many keys are involved in your batch calls? and how many of them may not exist?

**Comment by onlynishant** [comment]
No improvement with `-i -a` flags. 
```
go clean -i app
go install -a app
```
Each batch call will have 5-7 keys and most of the time (not sure but ~80-90%) that key should be present.

**Comment by onlynishant** [comment]
I increased `BasePolicy.Timeout` to 1s and `ClientPolicy.ConnectionQueueSize` to 1024

This is my code:
```
client, err := db.NewClientWithPolicyAndHost(getASClientPolicy(), hosts...)
	if err != nil {
		glog.Error(utils.Concat(AEROSPIKE_CONNECTION_FAILURE, " : ", err.Error()))
		return nil, err
	}

	return &Aerospike{
		client:      client,
		namespace:   conf.Namespace,
		BasePolicy:  getASBasePolicy(),
		QueryPolicy: getASQueryPolicy(),
}, nil

func getASClientPolicy() *as.ClientPolicy {
	cp := as.NewClientPolicy()
	cp.ConnectionQueueSize = 1024
	//	cp.LimitConnectionsToQueueSize = true
	return cp
}

func getASBasePolicy() *as.BasePolicy {
	bp := as.NewPolicy()
	bp.Timeout = 1000 * time.Millisecond
	//	bp.ConsistencyLevel = as.CONSISTENCY_ALL
	return bp
}

func getASQueryPolicy() *as.QueryPolicy {
	qp := as.NewQueryPolicy()
	return qp
}
```

**Comment by khaf** [comment]
Unfortunately I can't reproduce the problem with any config/workload/server latency/packet-loss rate after days of debugging. This may be a result of a subtle bug somewhere.

My best guess is that some connections become stale and then the server drops them, although I have no idea how or where this can happen, and why the client wouldn't close the connection afterwards.

Two ideas for further investigation:
1. Set the client log level to debug to see if we get something helpful.
2. What is the structure of the data you read? Are there Blobs/Lists/Maps involved? How big are they?

ps. Always set the `cp.LimitConnectionsToQueueSize = true`

**Comment by khaf** [comment]
Did you manage to find the reason for this issue?

**Comment by onlynishant** [comment]
No luck yet :(

**Comment by onlynishant** [comment]
I am not seeing CLOSE_WAIT issue anymore. Not sure what fixed it but still getting these erroe frequently -

```
E0824 02:13:19.426597 23360 Aerospike.go:33] Unable to fetch from Aerospike : read tcp 10.56.101.173:35143->10.56.101.184:3000: i/o timeout
E0824 02:13:19.426077 23360 Aerospike.go:33] Unable to fetch from Aerospike : read tcp 10.56.101.173:35129->10.56.101.184:3000: i/o timeout
E0824 02:13:19.426018 23360 Aerospike.go:33] Unable to fetch from Aerospike : read tcp 10.56.101.173:35087->10.56.101.184:3000: i/o timeout
E0824 02:13:18.529825 23360 Aerospike.go:33] Unable to fetch from Aerospike : command execution timed out: Exceeded number of retries. See `Policy.MaxRetries`. (last error: No available connections to the node. Connection Pool was empty, and limited to certain number of connections.)
E0824 02:13:18.529734 23360 Aerospike.go:33] Unable to fetch from Aerospike : command execution timed out: Exceeded number of retries. See `Policy.MaxRetries`. (last error: No available connections to the node. Connection Pool was empty, and limited to certain number of connections.)
E0824 02:13:18.528703 23360 Aerospike.go:33] Unable to fetch from Aerospike : command execution timed out: Exceeded number of retries. See `Policy.MaxRetries`. (last error: No available connections to the node. Connection Pool was empty, and limited to certain number of connections.)
```

**Comment by khaf** [comment]
The timeouts are what they are; You need to check your network stack in case they look abnormal.

The connections though indicate an empty pool; Too many connections are in flight. You need a bigger connection pool. You may want to time the operations (batch in your case) and find out how long they take to finish. I'm adding new batch-index capability to the client at the moment to help streamline big batch operations. Give that a try as well after the release in a couple of weeks.

**Comment by onlynishant** [comment]
Our batch-get size is 6-8 and each operation takes ~2ms. I am trying with `ConnectionQueueSize = 2048`. Is `batch-index` different than `BatchGet`?

**Comment by khaf** [comment]
Depending on the workload it *may* be better. You'll have to benchmark for yourself when it's out.

**Comment by khaf** [comment]
Let me know if the new batch protocol release helps in this regard.
