### ISSUE TITLE
Update to v1.25.0 breaks connection to Aerospike host

### ISSUE THREAD

**Issue by wedgeV** [aerospike/aerospike-client-go#199]
Just tried to update from v1.24.0 to the latest version and found that some change in v1.25.0 makes my application fail to connect to it's Aerospike host. This is on a local dev setup with application and Aerospike running in docker.

```
Failed to connect to host(s): [aerospike.dev:3000]; error: Failed to connect to host(s): [aerospike.dev:3000]. The network connection(s) to cluster nodes may have timed out, or the cluster may be in a state of flux.
```

Reverting to v1.24.0 without any other changes allows the application connect successfully. I also verified the application container can reach Aerospike by exec-ing into it and connecting to Aerospike via telnet and subsequently seeing the connecting in the Aerospike container logs.

Using the code below to connect:

``` go
client.adapter, err = aerospike.NewClientWithPolicyAndHost(nil, hosts...)
if err != nil {
    return nil, err
}
```

**Comment by khaf** [comment]
What was the issue?
