### ISSUE TITLE
What cause the difference of performance of ScanAll and ScanNode

### ISSUE THREAD

**Issue by kof02guy** [aerospike/aerospike-client-go#203]
I used these 2 api for scanning. I have a aerospike cluster with 2 nodes. The aerospike is static and no more new records are written.
I found that the time cost by ScanNode more or less the same when I used it to scan a single node as ScanAll. Why?

**Comment by kof02guy** [comment]
Is this because that ScanAll scan 2 nodes concurrently?

**Comment by khaf** [comment]
It certainly does scan both nodes at the same time. Depending on your network latency, recod queue size and worker count and speed, you may get different results.

**Comment by kof02guy** [comment]
So how can I speed up the performance of ScanNode? I've tried to change the record queue size from 5000 to 50000 but the performance didn't change.

**Comment by khaf** [comment]
Scan jobs are scheduled a bit differently than normal transactions. The only way I see you can speed up the scans for a node a bit is to set the priority to high, and use the 'Recordset.Records' directly in a channel select.

**Comment by kof02guy** [comment]
Thanks @khaf I've set the priority as HIGH. And for the approach to fetch the scanned records I saw that the recommended way of doing it is to use Results(). So what is bad if I use Recordset.Records directly instead of using Results()?

**Comment by khaf** [comment]
Using the 'Records' channel as opposed to Results() may save you a bit of goroutine schduling in runtime, which is probably insignificant depending on your usecase. The more nodes you have, the more bandwidth you'll get from scanning in parallel.
