### ISSUE TITLE
Improve SetPredExp - make type aerospike.PredExp public?

### ISSUE THREAD

**Issue by miko** [aerospike/aerospike-client-go#205]
While playing with predicate filters, I tried to set filters according to some logic, like:
```
var preds []aerospike.PredExp;
if someCondition {
  preds=append(preds, ...)
}
if anotherCondition {
  preds=append(preds, ...)
}
stmt.SetPredExp(preds)
```
Unfortunately preds are of type aerospike.predExp (unexported), so I can not use the code above.
Is there a plan to make the typeof preds exported? In the mean time, I have created a new function to test my program:
```
func (stmt *Statement) AppendPredExp(predexp ... interface{}) error {
  for _, v :=range(predexp) {
    fmt.Println(v)
    stmt.predExps = append(stmt.predExps, v.(predExp))
  }
  return nil
}
```
so now I can call stmt.SetPredExp(); stmt.AppendPredExp(preds), but it is a hack (uses interface{})

**Comment by khaf** [comment]
Made it public in the latest release.
