### ISSUE TITLE
Iterating through records is slow

### ISSUE THREAD

**Issue by griesmey** [aerospike/aerospike-client-go#209]
I brought up an issue that I was having on the Aerospike forum.  After one of the Aerospike engineers engineers reviewed the post we found that the slowness seem to be coming from code rather than the Aerospike database itself.  Here is the post in the forum that explains my issue:
https://discuss.aerospike.com/t/iterating-through-records-is-slow/4596

**Comment by khaf** [comment]
Can you increase the size of `ScanPolicy.RecordQueueSize` and use multiple Goroutines to consume the channel to see if the performance increases?

**Comment by griesmey** [comment]
I'll try it!

**Comment by khaf** [comment]
Thanks. Looking forward to hearing back from you. I want to get to the bottom of this :)

**Comment by griesmey** [comment]
I tried it and performance got a little worse.  

This is what I tried:

Perform the query
`	//RecordQueueSize
	//  Number of records to place in queue before blocking. Records received
	//  from multiple server nodes will be placed in a queue. A separate goroutine
	//  consumes these records in parallel. If the queue is full, the producer
	//  goroutines will block until records are consumed. * Default: 5000
	RecordQueueSize = 100000

	//NumConcurrency determines how many goroutines read from the Aerospipe
	// Records channel
	NumConcurrency = 10
)

//QueryByLoc queries the aerospike db via geospatial indexes
func QueryByLoc(i *Index, p *Point, r float64) (*as.Recordset, error) {
	var err error
	rs := &as.Recordset{}

	stmt := GeoQuery(Namespace, EmbedSet, p, r)
	policy := as.NewQueryPolicy()
	policy.RecordQueueSize = RecordQueueSize
	if rs, err = i.Client.Query(policy, stmt); err != nil {
		return nil, err
	}
	return rs, err
}`

Consume the records 
`
func Digest(records <-chan *as.Result, c chan<- *as.Result) {
	for rec := range records {
		c <- rec
	}
	return
}

func ConcurrentDigest(rs <-chan *as.Result, c chan *as.Result) {
	var wg sync.WaitGroup
	wg.Add(NumConcurrency)

	for i := 0; i < NumConcurrency; i++ {
		go func() {
			Digest(rs, c)
			wg.Done()
		}()
	}
	go func() {
		wg.Wait()
		close(c)
	}()
}`

Perform some operation
`//compareAll embeddings in the Recordset with embedding vector
func CalculateTopK(rs *as.Recordset, v1 algo.Emb, k int) *algo.SearchHeap {
	items := []algo.Item{}

	start := time.Now()
	c := make(chan *as.Result)

	ConcurrentDigest(rs.Results(), c)

	for res := range c {
		// Perhaps we could do a more direct type assertion sequence
		// here instead of all of this flailing
		results := []float32{}
		for _, e := range res.Record.Bins[EmbBinKey].([]interface{}) {
			f := e.(float32)
			results = append(results, f)
		}

		v2 := algo.Emb(results)
		if len(v1) != algo.VecLen || len(v2) != algo.VecLen {
			continue
		}

		if _, ok := res.Record.Bins[JobIDBinKey]; !ok {
			continue
		}

		if jobID, ok := res.Record.Bins[JobIDBinKey].(string); ok {
			item := algo.Item{Value: jobID,
				Score: algo.CosineSim(algo.VecLen, v1, v2),
			}

			items = append(items, item)
		}
	}
	fmt.Printf("Time taken for A* Query: %d(ms)\n", time.Since(start)/1000000)`

This is all being ran on an AWS m4.large instance.  The current runtime of this is around 615ms.

**Comment by griesmey** [comment]
What do you think about my implementation of reading records concurrently from a channel.  Am I using ```RecordQueueSize``` appropriately?

**Comment by khaf** [comment]
Those channel to channel copying in goroutines are pretty slow and costly. You will get some performance boost using the same channel everywhere (using the `Records` channel directly from the `Recordset`.) instead of pouring from one to the other. Everything in the library is goroutine friendly.
