### ISSUE TITLE
Bug: ScanAllObjects only returns partial results

### ISSUE THREAD

**Issue by blitzprog** [aerospike/aerospike-client-go#213]
This works and returns all 10,000 records from the database:

```go
for obj := range scanChannel {
	fmt.Println(obj)
}
```

However, if the channel retrieval takes a substantial amount of time, it only retrieves partial results, e.g. 2,800 records.

```go
for obj := range scanChannel {
	fmt.Println(obj)
	time.Sleep(1 * time.Second)
}
```

Could it be that scan results only stay alive for a certain amount of time? If that's the case, is it possible to disable this behavior and get consistent results (always 10,000 records)?

**Comment by khaf** [comment]
It is due to the server dropping the connection to stale scans to free up resources.

**Comment by blitzprog** [comment]
@khaf Is there any way to circumvent this issue without having to store N elements in a slice where N could potentially be so big that it doesn't fit into memory?

**Comment by khaf** [comment]
You can increase the `ScanPolicy.Timeout` to a suitably big number.

**Comment by blitzprog** [comment]
Hi @khaf, thank you for your help.

I would like to mention 3 points.

1.) I'm a bit confused on this one. According to the documentation, `Timeout` is 0 by default:

![timeout](https://puu.sh/y576j/e1005d5762.png)

Or could you have meant `ServerSocketTimeout` which has a default of 10 seconds?

I will try this setup:

![scan policy](https://puu.sh/y57nI/9876ccf63c.png)

Let me know if I misunderstood something.

2.) I do not know much about Aerospike internals but it took me a **long time** to figure out why half of my records were not updating. I think a higher scan timeout by default would improve the usability of Aerospike. Do you / the Aerospike team disagree?

3.) Am I correct in assuming that the disadvantage of a high timeout is that the file descriptor limit would be reached more easily on Linux systems? I am thinking about setting it to 1 or 2 hours, hoping that I'll still be fine with these values.

**Comment by khaf** [comment]
My Bad, it's `ServerSocketTimeout`. Your config looks good and should work.

The reason for the` ServerSocketTimeout` on scans is to avoid stale connections in case client does not consume records fast enough. Since Aerospike is designed for maximum single key performance, default parameters are tuned to maximize toward that end.

I don't understand why it was difficult to find the problem. Weren't you getting the `io.EOF` errors?

**Comment by blitzprog** [comment]
Where can I catch the `io.EOF` error?

https://github.com/aerogo/aerospike/blob/master/Database.go#L132-L136
https://github.com/aerogo/aerospike/blob/master/Database.go#L158-L163

```go
channel := make(chan *User)
err := DB.Scan("User", channel)

panicOnError(err)

for user := range channel {
	fmt.Println(user.Name)
}
```

**Comment by khaf** [comment]
"RecordSet.Results()" returns an object with either the record, or an error. Even better would be to directly consume the `Records` and `Errors` channels.

**Comment by blitzprog** [comment]
I see, I might have to change the API of my Database Abstraction Layer.
Thank you for your help!
