### ISSUE TITLE
batch-index protocol for batch operations

### ISSUE THREAD

**Issue by clusc** [aerospike/aerospike-client-go#214]
Hi,

We are just being informed today that the go client is still using the old batch-direct protocol for batch operations, while debugging why the metrics are missing in our dashboard. Is there any plan to support it? 

Eric

**Comment by khaf** [comment]
I'm working on it at the moment. Hopefully will release it next week.

**Comment by clusc** [comment]
Awesome, keep us posted.

**Comment by khaf** [comment]
Released with Delay. Had to debug a particularly nasty bug.

**Comment by clusc** [comment]
Thanks, we are upgrading now.

**Comment by clusc** [comment]
@khaf We just found out that the new protocol doesn't return the key's set name(`rec.Key.SetName()` is nil), even if we set the sendKey write policy to true already(we always do). Setting `BatchPolicy.UserBatchDirect = true` returns the setname successfully. Is this the intended behavior? We have some logic that relies on setname() to be present unfortunately.

**Comment by khaf** [comment]
While that behavior is intended and as designed, I've introduced a workaround to support your use-case. Update your code to the latest master.

Let me know how it goes.

**Comment by clusc** [comment]
@khaf confirmed the latest master works, thanks a lot! Can we have a new release anytime soon?

**Comment by khaf** [comment]
Anything in the master is reliable and well tested. Releases are just milestones we designate a version number to.
