### ISSUE TITLE
Setting TTL to -2 while updating an object

### ISSUE THREAD

**Issue by shiv6146** [aerospike/aerospike-client-go#215]
Newer versions of Aerospike now support setting ttl -2 to not affect its ttl while updation as per [doc](https://www.aerospike.com/docs/operations/manage/storage#setting-time-to-live-ttl-for-data-expiration) Is this supported?

**Comment by rbotzer** [comment]
Aerospike CE and EE from release 3.10.1 on up support this. The client needs to be working with a server whose version includes this feature.

**Comment by shiv6146** [comment]
@rbotzer My Aerospike server version is 3.14. But go aerospike client does not allow me to set -2 for expiration in its write policy. Any known workaround for this?

**Comment by shiv6146** [comment]
Assigning TTLDontExpire to policy.Expiration worked

**Comment by khaf** [comment]
The value you are looking for is `TTLDontUpdate`

**Comment by sarathsp06** [comment]
[https://github.com/aerospike/aerospike-client-go/blob/dcec4388c832b931227afe511b7f047c6b1b53ce/write_policy.go#L25](TTLDontUpdate)
