### ISSUE TITLE
Invalid Message Issue

### ISSUE THREAD

**Issue by kof02guy** [aerospike/aerospike-client-go#217]
Hi, team
Recently I've sometimes got this error in our online service using aerospike:
`Invalid Message Header: Expected version to be 2, but got 0`

It seems that the 'validateHeader' fails when 'parseResult'. I noticed that the headers are generated and manipulated within 'aerospike-client-go'.

I have several questions:
Is 'PutBins' thread safe? If the content of binMap is changed during the execution of 'PutBins', will the Invalid Message Header be triggered?
What can I do to identify the reason of this error?

Thanks in advance.

**Comment by khaf** [comment]
The message headers are coming from the server, so this means for whatever reason, invalid/scrambled messages are received by the go client. There are a few reasons why this could happen.

What is the transaction types you are sending to the server? (Read/Write/Batch/Query/Scan/UDF/etc)

What version of the client are you using?

**Comment by kof02guy** [comment]
Hi, @khaf 
I was using Write and got this error. Does the header come from the server when I use Write?
I was using version v1.27.0

**Comment by khaf** [comment]
This seems like a one off issue due to parsing and data residue in the connection. Let us know if it happens again.
