### ISSUE TITLE
High Performance impact while fetching bins of type map

### ISSUE THREAD

**Issue by raghuteja** [aerospike/aerospike-client-go#221]
I generated a flame graph for my Golang process to figure out bottlenecks, Below is the screenshot of aerospike batch query. As you see, the majority of time is taken during parsing the map (i.e, unpackMap function). 

I am calling batch query like this `client.BatchGet(batchPolicy, asKeys)`

Is there any alternative way to call batch query to make this step efficiently?

<img width="1201" alt="screen shot 2018-01-17 at 15 28 31" src="https://user-images.githubusercontent.com/2473294/35036753-566249be-fb9b-11e7-9a25-a6cd2b91d964.png">

**Comment by khaf** [comment]
It's not the unpacking itself that is slow, but allocating the map on the heap. I'll have to investigate a bit to see if it can be done more efficiently.

How big are your maps? (e.g: How many elements, type of those elements, nested maps, nested lists, etc.)

**Comment by raghuteja** [comment]
Size of batch: 6-8
Total number of sets: 6-8
Total Number of bins per set which is map: 1-2
Number of Elements in map: 1-200
Type of map: map[int]int (Not nested)

**Comment by khaf** [comment]
There does not seem to be anything that we can do here. Allocating maps, and then boxing all the values inside `interface{}` is memory intensive.
