### ISSUE TITLE
AerospikeError needs a bit more documentation

### ISSUE THREAD

**Issue by fillest** [aerospike/aerospike-client-go#222]
I've wanted to check `Operate()` error result for `Element exists` error and had to figure out the type of `err`, to search through the source, to recall the upcasting (got `err.ResultCode undefined` first):
```go
err.(astypes.AerospikeError).ResultCode() == astypes.FAIL_ELEMENT_EXISTS
```
Would be great if that would be documented in https://godoc.org/github.com/aerospike/aerospike-client-go
I've just found https://www.aerospike.com/docs/client/go/usage/error.html but I forgot to check it out first at all because godoc is more convenient. And error code symbols (at least their location) are not there.

**Comment by khaf** [comment]
Makes sense. I'll add it for the next release of the client.

**Comment by khaf** [comment]
Fixed in the latest release. Thanks for your report.
