### ISSUE TITLE
Panic in v1.32.0 

### ISSUE THREAD

**Issue by Hamper** [aerospike/aerospike-client-go#228]
Version 1.32.0
Sometime panics in logs: 
```
 panic: runtime error: index out of range
 goroutine 105 [running]:
 .../vendor/github.com/aerospike/aerospike-client-go.partitionMap.merge(0xc428b8b9b0, 0xc428b8b8c0)
 #011/.../go/src/.../vendor/github.com/aerospike/aerospike-client-go/partitions.go:95 +0x6fb
 .../vendor/github.com/aerospike/aerospike-client-go.(*Cluster).tend(0xc420142280, 0x0, 0x0)
 #011/.../go/src/.../vendor/github.com/aerospike/aerospike-client-go/cluster.go:355 +0x6f3
 .../vendor/github.com/aerospike/aerospike-client-go.(*Cluster).waitTillStabilized.func1(0xc420142280, 0xc4202065a0, 0xc428b7e6f8)
 #011/.../go/src/.../vendor/github.com/aerospike/aerospike-client-go/cluster.go:445 +0x5c
 created by .../vendor/github.com/aerospike/aerospike-client-go.(*Cluster).waitTillStabilized
 #011/.../go/src/.../vendor/github.com/aerospike/aerospike-client-go/cluster.go:442 +0xa7
```

**Comment by khaf** [comment]
Thanks for your report. The fix is in master now. Feel free to close this issue if the issue was resolved.

**Comment by clusc** [comment]
I understand, but I think it warrants a patch release if it fix critical issue.

**Comment by khaf** [comment]
Releases in the Go client are just random tags. I hold every code push to the master to the same quality standard. I can tag it if you want, but there will be no effect to the end user.

I also want to wait for a couple of days to make sure the fix resolves the reported issue conclusively before putting it in the `CHANGELOG`.

**Comment by khaf** [comment]
Are you using `gopkg.in`?

**Comment by clusc** [comment]
We use bazel to track dependencies, and generally prefer published tag instead of individual commit. We can make exception if the fix is critical and not yet released.
