### ISSUE TITLE
equal filter - wrong result

### ISSUE THREAD

**Issue by oltdaniel** [aerospike/aerospike-client-go#231]
My go client does not return a result, although my command line client returns me some results. If I comment out one of the two equal filter I get a result, but two filters kill the query. Maybe this error hasn't been found before since the test script only contains a single equal filter check ([`query_test.go`](https://github.com/aerospike/aerospike-client-go/blob/master/query_test.go#L255))

Go code:
```go
// Create statement
stm := as.NewStatement("test", "rows", "author", "name")

// Add filters
stm.Addfilter(as.NewEqualFilter("author", "1234"))
stm.Addfilter(as.NewEqualFilter("id", "xyz"))

// Get results
recordset, err := DB.Query(QUERY, stm)

// Error check
if err != nil {
  panic(err)
}

// This prints <nil>
fmt.Println(<-recordset.Records)
```

Command line input:
```shell
$ aql
> SELECT * FROM test.rows WHERE author="123" AND id="xyz"
# Prints results
# ...
```

**Comment by khaf** [comment]
Aerospike server does not support multiple filters on indexes. You need to use predicates.

You can take a look at [predexp_test.go](https://github.com/aerospike/aerospike-client-go/blob/master/predexp_test.go) for examples of use.
