### ISSUE TITLE
Provide a new tag for compatibility with Aerospike 4.2.0.2.

### ISSUE THREAD

**Issue by bmcstdio** [aerospike/aerospike-client-go#234]
The `migrate_progress_send` stat used in the `MigrationInProgress` function seems to have been removed in Aerospike 4.2.0.2. The most recent tag in this repo, `v1.32.0`, still relies on this old stat, while latest `master` relies on `migrate_partitions_remaining`. It would be great to have an updated tag in order to provider better pinning to downstream projects.

**Comment by khaf** [comment]
Thanks for your report. The client release took care of using the new stat name.
