### ISSUE TITLE
Inconsistent embedding of inner policies

### ISSUE THREAD

**Issue by tchiam** [aerospike/aerospike-client-go#238]
Different policies embeds inner policies differently:

As structs:
https://github.com/aerospike/aerospike-client-go/blob/master/batch_policy.go#L20
https://github.com/aerospike/aerospike-client-go/blob/master/write_policy.go#L31

As pointers:
https://github.com/aerospike/aerospike-client-go/blob/master/multi_policy.go#L22
https://github.com/aerospike/aerospike-client-go/blob/master/scan_policy.go#L21

This can be potentially misleading when working with multiple policies that share the same set up.

**Comment by tchiam** [comment]
Also wondering why ScanPolicy has an explicit ServerSocketTimeout (https://github.com/aerospike/aerospike-client-go/blob/master/scan_policy.go#L31) but QueryPolicy doesn't (https://github.com/aerospike/aerospike-client-go/blob/master/query_policy.go#L25)?
Since they are both streaming interfaces, wouldn't query also benefit from setting this timeout?

**Comment by khaf** [comment]
Regarding the policies, you're right, although I don't know if it's worth fixing since it may be a breaking change for some.

Regarding the scan socket timeout, it is only available on the server for scans (since they may be very long running), hence support for them on the client.

**Comment by khaf** [comment]
After checking with our server team, it seems that the `ServerSocketTimeout` is only supported for scans at the moment, since they are designed to take much longer and work differently than the queries.
