### ISSUE TITLE
Error while trying to connect to node

### ISSUE THREAD

**Issue by speedwheel** [aerospike/aerospike-client-go#239]
I get this error while trying to connect to my aersopike server, I am using VirtualBox on Windows using `client, err := NewClient("172.28.128.3", 3000) // I also tried 127.0.0.1`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x40138b]

goroutine 10 [running]:
sync/atomic.LoadUint64(0x122d2cbc, 0x120200c5, 0x12240385)
        C:/Go/src/sync/atomic/asm_386.s:159 +0xb
github.com/aerospike/aerospike-client-go/types/atomic.(*AtomicInt).Get(0x122d2cbc, 0x1)
        C:/Work/go/src/github.com/aerospike/aerospike-client-go/types/atomic/int.go:53 +0x23
github.com/aerospike/aerospike-client-go.(*Node).verifyPeersGeneration(0x122d2c40, 0x11fb6f40, 0x122447c0, 0x0, 0x11fb6f40)
        C:/Work/go/src/github.com/aerospike/aerospike-client-go/node.go:192 +0x111
github.com/aerospike/aerospike-client-go.(*Node).Refresh(0x122d2c40, 0x122447c0, 0x0, 0x0)
        C:/Work/go/src/github.com/aerospike/aerospike-client-go/node.go:125 +0x418
github.com/aerospike/aerospike-client-go.(*Cluster).tend.func1(0x11eb3270, 0x122447c0, 0x122d2c40)
        C:/Work/go/src/github.com/aerospike/aerospike-client-go/cluster.go:253 +0x53
created by github.com/aerospike/aerospike-client-go.(*Cluster).tend
        C:/Work/go/src/github.com/aerospike/aerospike-client-go/cluster.go:251 +0x21a
```
Any thought? I can see the node just fine when I go to:
`http://172.28.128.3:8081/#dashboard/172.28.128.3:3000/60/172.28.128.3:3000`

**Comment by khaf** [comment]
It's not the node that is being reported as `nil`, but `peersGeneration`. The problem is that it is impossible for that pointer to be `nil`.

What is the version of the Go, Go client, Aerospike Server (+ edition) and your environment?

Can you run the go tests via the following command and report the output?
```bash
ginkgo -v -race -- -h <host>
```

**Comment by speedwheel** [comment]
go version go1.11 windows/amd64
Windows 10 Pro Version	10.0.17134 Build 17134
aerospike-client-go (latest version)
Aerospike Server Community Edition 4.3.0.2 (installed using this tutorial https://www.aerospike.com/docs/operations/install/vagrant/win/)

And this is the result of the race test:
```
C:\Work\go\src\github.com\aerospike\aerospike-client-go>ginkgo -v -race -- -h 172.28.128.3:3000
Failed to compile aerospike-client-go:

# github.com/aerospike/aerospike-client-go_test
.\truncate_test.go:41:7: rec declared but not used
vet: typecheck failures

Ginkgo ran 1 suite in 16.5843623s
Test Suite Failed
```

**Comment by khaf** [comment]
This seems to be a Go problem. Can you revert to Go 1.10 and try again?

**Comment by speedwheel** [comment]
@khaf I tried, but it didn't make any difference.

**Comment by khaf** [comment]
Sorry I missed the windows part, I thought everything was on the VM. The part that is throwing the error is using some CPU based atomic operations. Over the time there have been a lot of problems with these on the Go compiler.
While I can't be totally sure, there seems to be another of those issues on the Go compiler for windows. Are you going to use windows for your production machines, or is it just for testing?

**Comment by speedwheel** [comment]
@khaf I am using Windows for development purpose, but it's ok I will just connect remotely to the linux aerospike database.
