### ISSUE TITLE
Should reuse the most active connection in pool to reduce the active num while not busy

### ISSUE THREAD

**Issue by absolute8511** [aerospike/aerospike-client-go#240]
Currently, the connection pool will put the connection back to the end of the queue and reuse the connection from the head of the queue. In this case, if we just reached a sudden high QPS, we will create many new connections to the pool. However, after the QPS became lower, the connections created cannot be dropped because it will be reused period. But actually, we do not need the same connections for the lower QPS after the peak.

To make sure we can drop some unnecessary connections after a sudden high QPS we should always reuse the most active connections.

**Comment by khaf** [comment]
Idle connections are automatically removed from the connection pool. The current design makes it easy to purge the idles.

You can control this behavior by tweaking the `ClientPolicy.IdleTimeout` value.

**Comment by absolute8511** [comment]
`ClientPolicy.IdleTimeout` cannot recycle the connection unnecessary but not idle. Example as below:
If there are 100 connections in the pool and the `ClientPolicy.IdleTimeout` is 10 seconds, and we read a key every 50ms and each read cost only 1ms. In this case, we will always make the 100 connections not idle every 5s (because the queue pool will always reuse connections by FIFO). However, we just need 1 connection in the pool to achieve the TPS.

@khaf

**Comment by khaf** [comment]
Released in v1.35.2
