### ISSUE TITLE
Changes For Version 2.0

### ISSUE THREAD

**Issue by khaf** [aerospike/aerospike-client-go#246]
It's been more than 4 years since we released the Aerospike Go Client. Over the years some inconsistencies have found their way into the client API, and we have learned new tricks to speed things up and make the client work better. Some of these tricks would break the client, either semantically or syntactically, so we've been postponing these changes over time for the future.

In this document we'll keep a list of those changes for the version 2. We invite the community to weigh in on these issues, and provide feedback.

Please keep in mind that there is still no plans for a version 2 release. This ticket is mostly a document to keep track of the issues for the future.

One of the goals for this exercise is to keep the changes as simple as possible, so that updating the code would only take a simple Find/Replace All or a Macro.

- [x] . Rename `Statement.Addfilter` to `SetFilter`.
- [x] . Return an error if a record does not exists. Currently only `nil` is returned. #232
- [x] 3. Some policiy embeddings are inconsistent: #238 
- [ ] 4. 32 bit support #33 
- [ ] 5. Change BinMap from `map[string]interface{}` to `map[string]BinValue` to allow for specialized API to be called on the fields, eg `rec.Bins["bin_name"].AsInteger()` or `rec.Bins["bin_name"].TryInteger()`

**Comment by Halfi** [comment]
Please create v2 branch for 2.0 version https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by khaf** [comment]
Sorry too late, we released it yesterday.

**Comment by Halfi** [comment]
I know and it have broke all projects with go modules (vgo).

**Comment by khaf** [comment]
While support for Go modules are not officially released yet, you are right that v2 broke them for whoever was using it. The problem is that their solution breaks Go's long standing tradition of keeping the latest version in master. Letting master go stale is a total deal breaker for me.

I think the practical approach to do this would be to have branches for each major release (v1, v2, v3) and let the master follow the latest version, while having the ability to still use Go modules as intended.

Any feedback from the community would be appreciated.
