### ISSUE TITLE
Reading a single value from a map cdt via Operate()

### ISSUE THREAD

**Issue by tchiam** [aerospike/aerospike-client-go#247]
It seems that an Operate() call with a single MapGetByX() operation returns "Parameter error". If the Operate includes some sort of write, both operations work as expected. Does Operate() require a write operation for some reason and does not allow reading only?

Also, is there a simpler way of reading a single or multiple values from a map cdt without requiring Operate()?

**Comment by khaf** [comment]
Reading should work without write. Can you paste your Operate command so that I can try that exact command to reproduce?

Regarding your second question: No. CDTs are supported only through operations.

**Comment by tchiam** [comment]
I'm calling it through a thin wrapper library but basically I'm making the simplest calls possible.
This writes as expected:
` as.Operate(ctx,nil, testset, "k1", aerospike.MapPutOp(as.MapPolicy(), bin, "mk1", "value1"))`
However this returns "Parameter error":
`as.Operate(ctx,nil, testset, "k1", aerospike.MapGetOp(bin, "mk1"))`
Putting some other write in the operation results in the read returning as expected:
`as.Operate(ctx,nil, testset, "k1", aerospike.MapPutOp(as.MapPolicy(), bin, "mk2", "value2"), aerospike.MapGetOp(bin, "mk1"))`

**Comment by khaf** [comment]
There is no `MapGetOp()` in the library. What is the variant you are calling (e.g MapGetByKeyOp), and with what input (some have policies and return types which matter in this case)

**Comment by tchiam** [comment]
Thanks khaf, after playing with your code for a bit I got it to work on my end. The failure on our end is due to us auto passing in a WritePolicy, which somehow causes it to return parameter error. Setting a nil WritePolicy for the read only Operate() works. Will dig a little deeper to figure out the exact root case. Thanks for helping confirm it works!

**Comment by khaf** [comment]
No problem. Let me know about your findings in case we need to improve something on our end.

**Comment by khaf** [comment]
Yes, this would certainly be a minor bug. Thanks for your help.

**Comment by khaf** [comment]
This should be fixed in the latest master now.
