### ISSUE TITLE
Question: setValue when value in aerospike is int but target is float returns

### ISSUE THREAD

**Issue by mikarios** [aerospike/aerospike-client-go#248]
On read_command_reflect.go line 172 there is the following code:
```
case reflect.Float64, reflect.Float32:
	// if value has returned as a float
	if fv, ok := value.(float64); ok {
		f.SetFloat(fv)
	} else {
		// otherwise it is an old float64<->int64 marshalling type cast which needs to be set as int
		f.SetFloat(math.Float64frombits(uint64(value.(int))))
	}
```
My problem is on `f.SetFloat(math.Float64frombits(uint64(value.(int))))`. Is there a reason why `f.SetFloat(float64(value.(int)))` is not used?

**Comment by khaf** [comment]
The values were practically encoded, and not just type-cast when putting in the database. Here we convert them back. Type casting back would result in truncation, and not decoding.

**Comment by mikarios** [comment]
When I use this it does not return the correct float64 value.
My case is the following:

I have a udf which updates the values on a record. For example
```
rec['budgetSpent'] = (rec['budget']  or 0.0) + price
```
In the beginning everything works fine until I get to an integer number in my database.
Let's say price is 0.1, when it reaches 1 aerospike reports back that this is an int, I'm trying to read float and the result that I get is 5e-324.
If I change the above mentioned line to f.SetFloat(float64(value.(int))) I get the result that I expect.

Could you please help me if I'm doing something wrong?

**Comment by mikarios** [comment]
I just saw your edit "Floats are now put as floats in the database, so you should never reach this code."
The problem is that some of the values in the database are put there using a udf where the client has no control.
Here's an example code showing of the case:
https://play.golang.org/p/Dx6e1QygTQr

And the output is:
```
1 1.000000000000001
2 2.000000000000001
3 3.000000000000001
4 4.000000000000001
5 5.000000000000001
6 6.000000000000001
7 7.000000000000001
8 4e-323
9 4.4e-323
10 5e-323
11 5.4e-323
12 6e-323
13 6.4e-323
14 7e-323
15 7.4e-323
16 8e-323
17 8.4e-323
18 9e-323
19 9.4e-323
...
```

Thanks in advance for your help

**Comment by khaf** [comment]
I see. Another lua corner case. Let me see how I can support this use case on the client side.

**Comment by mikarios** [comment]
Yes exactly :D
Though I guess that since the client was never supposed to enter this specific case I guess you can simply use the float64(value.(int)) solution and you are fine, no?
Thanks a lot.

**Comment by khaf** [comment]
Depends on what people already have in their databases. I don't think this will be an important change, but still needs enough reflection.

**Comment by khaf** [comment]
This should be fixed in the latest master now.

**Comment by mikarios** [comment]
Perfect, thanks a lot!
