### ISSUE TITLE
Unclear documentation on Operate

### ISSUE THREAD

**Issue by tchiam** [aerospike/aerospike-client-go#250]
On https://godoc.org/github.com/aerospike/aerospike-client-go#Client.Operate it states that all write operations happen before reads, so for an operate that looks like:

Write key X with value V1,
Read key X,
Write key X with value V2,
Read key X,

It seems to imply that both reads will return V2, but it seems that the operations actually do happen in the specified order and V1 is returned first and then V2.

**Comment by khaf** [comment]
It appears the documentation is out of date since server v3.6.0, in which the behavior described in the docs changed. Will fix in the next version.
