### ISSUE TITLE
Reading first value in a Map

### ISSUE THREAD

**Issue by gabrielerzinger** [aerospike/aerospike-client-go#251]
First of all, thank you for the amazing work. Also, in advance, sorry for my bad english

Using MapGetByKeyOp with return type 3 or 4 always returns one value  (the rank associated with the given key), right? Although, calling it on a map bin with only one key/value returns a `[]interface{}` (with size 1, where [0] is the desired rank). Is this intentional ? 

Steps:

1. Insert an element using MapPutOp on an empty/inexistent map with key=x value=y
2. Fetch it using MapGetByKeyOp using `x` as the map key and 4 as map return type
```golang
rec, er := client.operate(nil, key, operation)
```
3. rec.Bins["set"], where `set` is the **set** used to generate **key** is type []interface{}, where I think it should be type interface{} ( as it is if the map has more than one element )

I've made a workaround on my application using reflection, but I think this isn't the desired output or, if it is, is it documented?

**Comment by khaf** [comment]
No problem, we're here to help. Sorry for the late reply, I was busy with other work.

I'll get back to you as soon as I'm able to reproduce the issue.

**Comment by khaf** [comment]
This has taken a long while, sorry for some reason it flew under my radar. The reason for this is that you can pass multiple `MapGetByKeyOp` ops to the same call, and the results will be bunched together for each bin, which would end up being a slice, hence the `[]interface{}`.

This behavior is demonstrated in the tests here: [cdt_map_test.go](https://github.com/aerospike/aerospike-client-go/blob/master/cdt_map_test.go#L171)
