### ISSUE TITLE
Latency spikes after updating v1.31.0 -> 1.36.0

### ISSUE THREAD

**Issue by un000** [aerospike/aerospike-client-go#252]
I observe for unexpected spikes in 0.95/0.99 near 100ms after updating the client to the version above:
![spikes](https://i.imgur.com/awq7ZoH.png)

What you suggest to configure or watch for?

##
- Go: 1.11.1
- Client: 1.36.0
- Aerospike: 3.15.0.2 < 10 nodes
- ClientPolicy: 
 ```
 	clientPolicy := aerospike.NewClientPolicy()
 	clientPolicy.IdleTimeout = 15 * time.Second
 	clientPolicy.ConnectionQueueSize = 768
 ```
- Read/WritePolicy are set to the default one.

##
Also I want to say thank you for the awesome v1.35.2 release which reduces client connections!

**Comment by un000** [comment]
Seems it was socket timeouts. But I don't know why they didn't appear on old releases.

**Comment by khaf** [comment]
It's very important to not allow many connections to time out. Feel free to close the ticket.
