### ISSUE TITLE
Get Objects and metadata

### ISSUE THREAD

**Issue by Hamper** [aerospike/aerospike-client-go#254]
Functions like GetObject and ScanAllObjects are very helpful but this methods don't return any metadata like Generation (may be useful for safe updating) and Expiration. Сould be better to return Record with object without BinMap or add marshalling function from BinMap to object and vice versa?

**Comment by khaf** [comment]
you can use tags for metadata:

```go
type Object struct {
	TTL uint32 `asm:"ttl"`
	GEN uint32 `asm:"gen"`
}
```

**Comment by Hamper** [comment]
Does it work for writes with generation policy too?

**Comment by khaf** [comment]
That is controlled by `WritePolicy`.
