### ISSUE TITLE
Golang Client Node not found for partition in partition table

### ISSUE THREAD

**Issue by abdelkarim-uniris** [aerospike/aerospike-client-go#262]
Hello,

I am using the golang driver version "2.2.0" with an aerposike "4.5.3.3.

In a fresh installed single instance when i try to put 100 of txn (using a script)

sometime all works fine, and sometime i get this error:

%{ “Error” => “command execution timed out on client: Exceeded number of retries. See Policy.MaxRetries. (last error: Node not found for partition on-disk-db:1889 in partition table.)” }

on the same instance, and using the python client, all is working fine without issue.

health of the instance is green, disk is not full, server load is normal, only 30% of the ram is used.

what's wrong ?

Kind Regards.

**Comment by khaf** [comment]
Thank you for your report. I cannot reproduce this issue. Can you provide a code snippet that reproduces the problem on your side? Also preferably your server config?

**Comment by abdelkarim-uniris** [comment]
main.go:

`	s := randStringRunes(5)
	fmt.Println(s)
	i := 0
	var request string
	for i < 1000 {
		hasher := sha1.New()
		hasher.Write([]byte(s + string(i)))
		dst := make([]byte, hex.EncodedLen(len(hasher.Sum(nil))))
		hex.Encode(dst, hasher.Sum(nil))
		i++
		request = fmt.Sprintf(`{"ID" : "123", "Data": { "Type" : "put", "Namespace" : "on-disk-db", "Set" : "test", "Key" : "%s", "Bins" : [{ "BinName" : "addr", "BinValue" :"7157762ecb437e34e5770667d086887532a304d9152b171a974d100f2fcfb687"}, {"BinName" : "data","BinValue" :"JUbqK5m6c7I4zOKZiox4uLfmyJ5Qrj6Fbm4OZQeJdMNOFRZOVBr00EHCQ7ld0l7edTVSl0Bw6OfK7jV5eltq7nnyVXHIsK5pjyEs4W42kUQ6yIlNdjIF9GDxhQTuuO5Mn3MDEOtO6XnNqj2GXmt2NgNWD2JIBWxbdzhw5qD4ifQQrnNYQ3UG63eITM8AQD1lHONimYqI41tAZoFWHafqORaGpfO94rO1FKt3pRYnH9Nv9J0YG5wCm9wN2cXfdSbgibRGK4AlK7MmurMopnewDjNdGx0ecZHPxFQdpb6G0v8w1pCEZzZhDI5SltZPVippLfPXGsKA03vNoMEtKldObcEZE5bbXVaovi63doHzxpx9taJ3NY8km2kCRaXte8FBiONrIwNMcXRfto08nRcEICmFuHUTb9mG7GqwCmbBMc8EP3GJG5vUXgJnHF2uLpcuA4BiRNYPeuHJUXGQIxRY3CNQj5ew4fDqsHnNo2lfeUA0Qgxobks8ElDb9RnC1FcqpwsYcAGxpnB0EeQxuqzAOaiWR2pnzpreQXAlaroF8Sdkc25vIGtNaeHyOv7Q62P2IHrjLXMiFYGBtpA0ahiB1BJru7KmgEgwJ5vHseTjw7gN5szETSj2iPlv0SjgFSjlH5zUETlZQw0EFJVQOuqbg89BZAFYv8sbDnyw1aoP3R66o0hTvzIuGiSW6c5m4CSFyc8doeN91u7FYzWttSRY56Hdf53QDF5ax2KaBgk396Ni45WHXqh0yWODAPTOq27uAbdWwAFjiYYigCAn5OGwOyakHu7Xc93fLHVc" }]}}`, string(dst))
		dq, err := query.NewDatabaseQuery(request)
		if err != nil {
			fmt.Println(query.NewError("0", err.Error()).ToString())
		} else {
			err := dq.CheckValues()
			if err != nil {
				fmt.Println(query.NewError(dq.ID, err.Error()).ToString())
			} else {
				if dq.Data.Type == "get" {

					b, err := dq.ExecuteGetQuery()
					if err != nil {
						fmt.Println(query.NewError(dq.ID, err.Error()).ToString())
					}
					fmt.Println(b)
				}

				if dq.Data.Type == "put" {
					k, err := dq.ExecutePutQuery()
					if err != nil {
						fmt.Println(query.NewError(dq.ID, err.Error()).ToString())
					}
					fmt.Println(k)
				}
			}
		}
	}`

query.go:

`
//DatabaseQuery describe a database query
type DatabaseQuery struct {
	ID   string
	Data Data
}

//Data describe the data structure of a query
type Data struct {
	Type      string
	Namespace string
	Set       string
	Key       string
	Bins      []Bin
}

//DatabaseGetReply describe a database reply for a get request
type DatabaseGetReply struct {
	ID   string
	Data []Bin
}

//DatabasePutReply describe a database reply for a put request
type DatabasePutReply struct {
	ID   string
	Data string
}

//Bin describe a bin
type Bin struct {
	BinName  string
	BinValue string
}

//NewDatabaseQuery create a new database query
func NewDatabaseQuery(queryJSON string) (DatabaseQuery, error) {

	dq := DatabaseQuery{}
	err := json.Unmarshal([]byte(queryJSON), &dq)
	if err != nil {
		return dq, err
	}
	return dq, nil
}

//ExecuteGetQuery execute the get query on the db
func (dq DatabaseQuery) ExecuteGetQuery() (string, error) {
	var bin Bin
	var dgr DatabaseGetReply
	var bins []Bin

	client, err := aero.NewClient("127.0.0.1", 3000)
	if err != nil {
		return "", err
	}

	key, err := aero.NewKey(dq.Data.Namespace, dq.Data.Set, dq.Data.Key)
	if err != nil {
		return "", err
	}

	policy := aero.NewPolicy()
	policy.SocketTimeout = 50 * time.Millisecond

	rec, err := client.Get(policy, key)
	if err != nil {
		return "", err
	}

	for k, b := range rec.Bins {
		bin.BinName = k
		bin.BinValue = b.(string)
		bins = append(bins, bin)
	}

	dgr = DatabaseGetReply{
		ID:   dq.ID,
		Data: bins,
	}

	res, err := json.Marshal(dgr)
	if err != nil {
		return "", err
	}

	return string(res), nil
}

//ExecutePutQuery execute the put query on the db
func (dq DatabaseQuery) ExecutePutQuery() (string, error) {

	client, err := aero.NewClient("127.0.0.1", 3000)
	if err != nil {
		return "", err
	}

	key, err := aero.NewKey(dq.Data.Namespace, dq.Data.Set, dq.Data.Key)
	if err != nil {
		return "", err
	}

	policy := aero.NewWritePolicy(0, 0)
	policy.SocketTimeout = 5000 * time.Millisecond
	policy.MaxRetries = 3
	policy.SleepBetweenRetries = 10 * time.Millisecond

	var bins = make(aero.BinMap, len(dq.Data.Bins))

	for _, b := range dq.Data.Bins {
		bins[b.BinName] = b.BinValue
	}

	err = client.Put(policy, key, bins)
	if err != nil {
		panic(err)
	}

	dpr := DatabasePutReply{
		ID:   dq.ID,
		Data: key.String(),
	}

	res, err := json.Marshal(dpr)
	if err != nil {
		return "", err
	}
	return string(res), nil

}`


conf of aerospike:

`# Aerospike database configuration file for use with systemd.

service {
	paxos-single-replica-limit 1
	proto-fd-max 15000
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address 127.0.0.1
		port 3000
	}

	heartbeat {
		mode multicast
		multicast-group 239.1.99.222
		port 9918
		interval 150
		timeout 10
	}

	fabric {
		port 3001
	}

	info {
		port 3003
	}
}

namespace in-memory-db {
	replication-factor 1
	memory-size 1G
	default-ttl 0
	storage-engine memory
}

namespace on-disk-db {
	replication-factor 1
        memory-size 1G
	default-ttl 0
	storage-engine device {
		file /DATA/aerospike/data/uniris.dat
		filesize 5G
		data-in-memory false # Not Store data in memory in addition to file.
	}
}
`

**Comment by abdelkarim-uniris** [comment]
Please note that i manipulated a little the policy by increasing timeout to 5s, adding some retry on the put and adding delay between retry like you can see on the code:

```
policy.SocketTimeout = 5000 * time.Millisecond
policy.MaxRetries = 3
policy.SleepBetweenRetries = 10 * time.Millisecond
```
.
result is the same with using only a default policy with only 50ms timeout and 0 retry

**Comment by khaf** [comment]
Sorry for the late reply. It seems that you are creating a new client object every time you try to run a transaction. That is unnecessary, slow and is what is causing the issue. Just create one client object, and pass it to the methods that need it. You app will be MUCH faster and you won't be going through reconnecting and resetting the partition map on EACH transaction.

**Comment by abdelkarim-uniris** [comment]
thanks for the update, I understand,even if i close the client after each transaction,

**Comment by khaf** [comment]
The Go client has far more concurrency inside its core, which could in effect cause this if a tend fails after connection. This is not how our clients are designed to be used. You should always share the connection objects in all the clients.

**Comment by khaf** [comment]
I went ahead and closed the issue. Please feel free to reopen it or file a new issue.
