### ISSUE TITLE
parameter error on put object

### ISSUE THREAD

**Issue by ewanwalk** [aerospike/aerospike-client-go#264]
Hi I have a structure similar to the following:

```
type Record struct {
	TTL uint32    `as:"-" asm:"ttl"`
	Generation uint32    `as:"-" asm:"gen"`
	CID string    `as:"cid,omitempty"`
	Created int64     `as:"created,omitempty"`
	Country int       `as:"country,omitempty"`
	Referrer string    `as:"referrer,omitempty"`
	Latitude float64   `as:"lat,omitempty"`
	Longitude float64   `as:"long,omitempty"`
	Type int       `as:"type,omitempty"` 
	V2 bool      `as:"v2,omitempty"` 
	Rest string `as:"-"`
}
```

And am calling `PutObject` however the server returns `Parameter error` which does not helpe me in the slightest figure out what I should be changing. Is there any way to figure out what causes a parameter error? Are there specific standard types that arent allowed?

Edit:
* Aerospike version 4.6.0.2
* Client version: 2.2.1

**Comment by ewanwalk** [comment]
This was a mistake on my front! Solved

**Comment by khaf** [comment]
Could you please put the cause of your issue here in case someone else hits the same problem in the future?

**Comment by ewanwalk** [comment]
This was a couple things:

* You cannot use `as` tags with `asm` I assumed that you needed to omit the field with an `as` tag
* `omitempty` is seemingly not valid and is appended as part of the bin name, which is unfortunate as I have a bunch of fields which may be `0` and do not have to be serialised however this can be avoided by writing ones own serialisation
* I had a rookie mistake in my wrapper in which I actually forgot to re-assign the data meaning no data was attached to the request

Some feedback for the library:
* There is no clear documentation on the usage of tags (what is available - `asm`, supported - `omitempty`?)
* Errors are very vague

**Comment by khaf** [comment]
Thanks for your feedback. I'll try to add more documentation for the tags.

The server errors are vague since they are just codes sent back from the server. Aerospike have compromised a bit on he clarity to focus on performance as much as possible.
