### ISSUE TITLE
Duplicate objects inserted on same key - 'Insert On Conflict Do Nothing' available?

### ISSUE THREAD

**Issue by cgebe** [aerospike/aerospike-client-go#265]
I have 2 replicas of a service each inserting data into aerospike.

I use the following method for insertion:

```go
func (m *Memory) InsertBookSnapshot(name string, book model.Book) error {
	key, err := aerospike.NewKey(m.Namespace, util.Path(name, bookSubject), util.Path(book.Category, strconv.FormatInt(book.UpdateId, 10)))
	if err != nil {
		return err
	}
	return m.Client.PutObject(aerospike.NewWritePolicy(0, uint32(m.TTL)), key, book)
}
```

Now i retrieve data with a range filter on the timestamp attribute of each book object:

```go
func (m *Memory) GetBooksByTime(name string, from, to int64, order int) ([]model.Book, error) {
	stmt := aerospike.NewStatement(m.Namespace, util.Path(name, bookSubject))
	stmt.SetFilter(aerospike.NewRangeFilter("Timestamp", from, to))
	p := aerospike.NewQueryPolicy()
	p.FailOnClusterChange = false
	rs, err := m.Client.Query(p, stmt)
	if err != nil {
		return []model.Book{}, err
	}
	var books []model.Book
	for res := range rs.Results() {
		if res.Err != nil {
			defer rs.Close()
			return []model.Book{}, res.Err
		} else {
			book := model.Book{
				UpdateId:   int64(res.Record.Bins["UpdateId"].(int)),
				Category:     res.Record.Bins["Category"].(string),
				Timestamp:  int64(res.Record.Bins["Timestamp"].(int)),
			}
			books = append(books, book)
		}
	}
	return books, nil
}
```

When i check the results, i get duplicates which match in `book.Category` and `book.UpdateId`, but not in `book.Timestamp` (since two services are inserting the same data but assign different timestamps). I expected to only retrieve one object from aerospike due to matching keys, since putting an object onto aerospike with the same key will update the existing entry and add additional bins (which is not the case here). 

So i need a solution to only insert the object once, and if possible not update the timestamp on the second PutObject call. Is there a function to only write an object if the key does not exist yet and discard otherwise, similiar to Insert On Conflict Do Nothing?

**Comment by khaf** [comment]
It is impossible to have the same key for two different records in Aerospike Database. So either there is a bug in the server, in the client, or in your code. Can you share the `util.Path` code here?

Also, when getting back the records, you can check the `Key.String()`. Are the hashes the same? If not, the keys are different.

**Comment by cgebe** [comment]
hey @khaf I investigated this error and encountered additional anomalies such, that not all data was inserted or indices missing. The cause for all these anomalies including the one described above was a malfunctioning server instance in my cluster. Unfortunately, i did not turn on logging and there was no error in the log. Deleting local data on the node and rejoining it solved the problem. I hope that something like that does not happen again. The server hardware should be sufficient for a node: DDR4 64GB, Intel® Core i7-8700 Hexa-Core, 2TB NVME SSD

**Comment by cgebe** [comment]
In the process, i also updated the server version to 4.6.0.2 from prior 4.5.3.4.

**Comment by khaf** [comment]
Thanks for your feedback. What you describe is a serious problem if your analysis is correct. Please report the issue on our forums if it happens again.

**Comment by cgebe** [comment]
I will! Thank you very much.
