### ISSUE TITLE
List Index Queries not supported in aerospike-client-go?

### ISSUE THREAD

**Issue by saifat29** [aerospike/aerospike-client-go#266]
Following the examples from here [List Indexing and Querying
](https://www.aerospike.com/docs/guide/cdt-list-index-and-query.html)
I noticed that filtering on secondary indexes of `List` type is not supported in the Go client.
```go
stmt := aerospike.NewStatement("foo", "bar", "id")
if err := stmt.SetFilter(aerospike.NewEqualFilter("baz", "lorem")); err != nil {
	return err
}
```
The `NewEqualFilter()` function returns a `newFilter` with `ICT_DEFAULT` passed as `IndexCollectionType`
https://github.com/aerospike/aerospike-client-go/blob/master/filter.go#L35

For filtering on List it should also handle `ICT_LIST`.

Following is the error that I get by filtering using Secondary Index of type List-
`Index not found`

**Comment by khaf** [comment]
The `Equal` filter only works for secondary indexes. For complex indexes, you are probably looking for `Contains` filter. Take a look at this test file for examples:

https://github.com/aerospike/aerospike-client-go/blob/master/complex_query_test.go#L43

**Comment by saifat29** [comment]
@khaf Yes you are correct, I missed that in the documentation, thank you.
