### ISSUE TITLE
Misleading error type returned by (*bufferedConn) readConn(int) error

### ISSUE THREAD

**Issue by healiha** [aerospike/aerospike-client-go#267]
While working on a piece of code, I found out that when an error occurs (in my case it was a  `timeout`) at the connection level, the returned error is formatted using the `fmt` package instead of returning an `AerospikeError` which I believe should be the standard for all errors returned by the go client.

Here is the specific function –
https://github.com/aerospike/aerospike-client-go/blob/f20d63ae09793eafed462f89e977b11b7c52b5e6/buffered_connection.go#L77-L100

This led us to a case where we checked if the error had the result code `types.TIMEOUT` on an error which was not an `AerospikeError` thus breaking part of our implementation.

I do not believe that this should be labelled as a bug but maybe as an improvement which should not break any implementation since the `AerospikeError` implements the `error` interface.

**Comment by khaf** [comment]
This makes sense. We have had plans to do this for a long time, but we need a breaking release to do so. Luckily, one is coming along. Hopefully we'll take care of this in the v3 release.

**Comment by healiha** [comment]
Good to hear that. I'll keep taking a look at this tread and see if I can give a hand on this specific subject.

**Comment by khaf** [comment]
This was fixed in v3.0.0. Thanks for your patience.
