### ISSUE TITLE
PutObject(): Parameter Error (4)

### ISSUE THREAD

**Issue by phasetri** [aerospike/aerospike-client-go#268]
I'm running some simple tests to get started with the Golang client. I can do a simple bin write:

```
	pk, _ := asp.NewKey("test", "user", "testKey")
	bin0 := asp.NewBin("myBin", "myValue")
	as.Conn.PutBins(nil, pk, bin0)
```
This works fine, and I can query the bin using the AQL console.

If I try PutObject():

```
	type Car struct {
		engine string `as:"engine"`
		hp     int    `as:"hp"`
	}

	car := &Car{"vtec", 900}

	pk, _ = asp.NewKey("test", "user", "anotherTestKey")
	err = as.Conn.PutObject(nil, pk, car)
```
The err returned is "PARAMETER_ERROR (4)". Any idea what's going wrong? I tried removing the structtags but it didn't help resolve the issue.

Aerospike version: 4.7.0.2 (windows)
Golang version: 1.13.3

**Comment by khaf** [comment]
Your struct fields are not exported (Do not begin with upper case).

```go
	type Car struct {
		Engine string `as:"engine"`
		HP     int    `as:"hp"`
	}
```

**Comment by phasetri** [comment]
Thank you. That was the problem.
