### ISSUE TITLE
Very high latency and high number of connections at 12K QPS

### ISSUE THREAD

**Issue by saifat29** [aerospike/aerospike-client-go#271]
I've three high end bare metal servers. Aerospike runs on one of them and the other two servers with Golang performs almost 90% reads on the Aerospike server.

For a single request on the Go server there are exactly two reads to Aerospike-
1st Read:
```go
func (repo *ABCRepository) Get(id int) (*model.ABC, error) {
	key, err := aerospike.NewKey(repo.as.Namespace, "abc", id)
	if err != nil {
		return nil, err
	}
	abc := &model.ABC{}
	err = repo.as.AsClient().GetObject(aerospike.NewPolicy(), key, abc)
	return abc, err
}
```
The result of the above contains total 7 fields of primitive data types (string, int and bool) .

2nd Read:
```go
func (repo *DSPRepository) GetLinkedXYZs(pm model.RequestParameters) ([]model.XYZ, error) {
	stmt := aerospike.NewStatement(
		repo.as.Namespace, "seta",
		"name",
		"job",
		"lang",
		"country",
		"interest",
	)
	if err := stmt.SetFilter(
		aerospike.NewContainsFilter("my_bin", aerospike.ICT_LIST, pm.ID),
	); err != nil {
		return nil, err
	}
	if err := stmt.SetPredExp(
		aerospike.NewPredExpStringValue("Michael"),
		aerospike.NewPredExpStringVar("name_list"),
		aerospike.NewPredExpStringEqual(),
		aerospike.NewPredExpListBin("name"),
		aerospike.NewPredExpListIterateOr("name_list"),

		aerospike.NewPredExpStringValue("Developer"),
		aerospike.NewPredExpStringVar("job_list"),
		aerospike.NewPredExpStringEqual(),
		aerospike.NewPredExpListBin("job"),
		aerospike.NewPredExpListIterateOr("job_list"),

		aerospike.NewPredExpStringValue("Golang"),
		aerospike.NewPredExpStringVar("lang_list"),
		aerospike.NewPredExpStringEqual(),
		aerospike.NewPredExpListBin("lang"),
		aerospike.NewPredExpListIterateOr("lang_list"),

		aerospike.NewPredExpStringValue("Scranton"),
		aerospike.NewPredExpStringVar("ctr_list"),
		aerospike.NewPredExpStringEqual(),
		aerospike.NewPredExpListBin("country"),
		aerospike.NewPredExpListIterateAnd("ctr_list"),

		aerospike.NewPredExpStringValue("Backend"),
		aerospike.NewPredExpStringVar("intrst_list"),
		aerospike.NewPredExpStringEqual(),
		aerospike.NewPredExpListBin("interest"),
		aerospike.NewPredExpListIterateAnd("intrst_list"),
		aerospike.NewPredExpAnd(5),
	); err != nil {
		return nil, err
	}

	rs, err := repo.as.AsClient().Query(aerospike.NewQueryPolicy(), stmt)
	if err != nil {
		return nil, err
	}

	var xyzList []model.XYZ
	for res := range rs.Results() {
		if res.Err != nil {
			return nil, res.Err
		}
		dsp := model.DSP{
			Name:      res.Record.Bins["name"].(string),
			Job:          res.Record.Bins["job"].(string),
			Lang:        res.Record.Bins["lang"].(string),
			Country:   res.Record.Bins["country"].(string),
			Interest:    res.Record.Bins["interest"].(string),
		}
	}
	if err := rs.Close(); err != nil {
		return nil, err
	}
	return xyzList, nil
}
```
The above second read performs filtering on a secondary index and then predicate filtering.
The result contains five fields each a slice of string.

Above 12K TPS on the Aerospike server, latency increases considerably and the number of connections max out to the set value. The latency goes as high as 1s. Below 12K TPS everything runs very smoothly.

I ran pprof and noticed high syscalls originating from [func (*Client) Query](https://godoc.org/github.com/aerospike/aerospike-client-go#Client.Query). I use the `client.Query` function to perform the 2nd read (filtering and predicate expression) as shown above. I disabled just the predicate filtering but the problem still persisted.

However when I disabled the 2nd read entirely and hardcoded the results I was able to scale above 12K QPS.

I found a [blog](https://hackernoon.com/trying-aerospike-as-data-store-in-kurio-99c82b9a7180) and a [presentation](https://www.slideshare.net/brian-aerospike/go-meetup-nov142) where the authors faced the exact same problem, however they are not clear with the steps taken to solve the problem.

The Golang servers connect to Aerospike on private network of 1Gbps.

My aerospike.conf
```conf
service {
	user root
	group root
	paxos-single-replica-limit 1 # Number of nodes where the replica count is automatically reduced to 1.
	pidfile /var/run/aerospike/asd.pid
	proto-fd-max 15000
}

logging {
	file /var/log/aerospike/aerospike.log {
		context any warning
	}

	console {
		context any warning 
	}
}

network {
	service {
		address eth0
		port 3000
	}

	heartbeat {
		address eth0
		mode mesh
		port 3002
		interval 150
		timeout 10
	}

	fabric {
		address eth0
		port 3001
	}

	info {
		port 3003
	}
}

namespace test {
	replication-factor 1
	memory-size 1G
	default-ttl 5d # 5 days, use 0 to never expire/evict.

	# storage-engine memory

	storage-engine device {
		file /opt/aerospike/data/test.dat
		filesize 5G
		write-block-size 128K
		data-in-memory true
	}
}

namespace my_namespace {
	replication-factor 1
	memory-size 4G
	default-ttl 0 # 5 days, use 0 to never expire/evict.

	# storage-engine memory

	storage-engine device {
		file /opt/aerospike/data/my_namespace.dat
		filesize 5G
		write-block-size 128K
		data-in-memory true
	}
}
```

No matter how much connections you have, when latency increases it maxes out.

**Comment by khaf** [comment]
From a cursory reading, I don't see anything that catches the eye. Can you also mention the version of the Go Client (make sure your `vendor` version is also updated to that commit) and the server version?

I suspect in this case that queries are using up all the connections and are not allowing simple reads to use them. This happens because: 1. Queries use one connection per node, so a query to a 4 node cluster uses 4 connections and 2. They take longer to finish, so they end up blocking the simple reads.

To check if this is true, please rate limit the number of queries that can run per second and see if the number of TPS on the simple read increases significantly.

**Comment by saifat29** [comment]
I am using Go modules to manage dependencies
Go - v1.13
Aerospike Go client - v2.5.0
Aerospike Server - v4.7.0.2

I have a single node Aerospike server and two Golang nodes (each Go node with a single client).

When TPS is up to 12K reads (combined from both the Go clients on a single node Aerospike server) the number of aerospike client connections is in the range of 400-700 which is excellent.
As soon as read TPS increases above 12K the client connections max out to whatever high number I set. 
So I can guarantee you from my side that up to 12K read TPS everything works fine.

I benchmarked the aerospike server using the Aerospike Go client benchmark tool and saw that for 99% reads (which is my requirement) I can achieve read TPS of more than 100K.

**Comment by khaf** [comment]
What I meant is that your second read (query) is much slower than the first (Simple Get). As a result, at some point you end up using most of the time utilizing your connections for that slow read. What you see as syscall on the pprof is the client waiting on the pool, which will be empty a significant amount of time.

I suspect 12K is the max TPS you can achieve with the second read, even if you disable the first read. Have you timed that particular `Query` call until `rs.Close()`? How long does it take?

**Comment by saifat29** [comment]
I suspected that the second query is what takes more time, it consists of two parts-
1: Filter on a secondary index of type List
2: Predicate Expression on the result of the filter.
so I commented the Predicate Expression part, still no improvement.

I then changed the second read query entirely and instead of using a filter I used `client.BatchGet` but still same problem.

**Comment by saifat29** [comment]
My requirement is to get a large number of records (max. 50) out of Aerospike.

I also tried running simple `client.GetObject`  in a loop but it was worse.

**Comment by khaf** [comment]
You still didn't answer my question: How long does it take to run the query and read all the records back when latencies are low? How long does the `BatchGet` take?

**Comment by saifat29** [comment]
Sorry for not understanding, I'm not in front of my computer. I'll put the results ASAP.

Thank you for your help so far.

**Comment by khaf** [comment]
No problem. It would be useful to also find the average size of your response to see how much bandwidth is being used. For example, if your returned 50 records exceed 104 KiB in total size, 12K QPS will saturate a 10Gb interface.

**Comment by khaf** [comment]
Did you make any progress?

**Comment by saifat29** [comment]
Give me some time, I'm actually stuck in a more serious issue than this. I'll get back soon with reports.

**Comment by saifat29** [comment]
@khaf Average record size that I am fetching is around 2KB and I fetch 50 or so records at a time, I am running my servers on 1GB network interface.

You were right it is the 1Gb interface that is getting saturated.

When I fetch fewer fields in the records as compared to before the record size decreases considerably and I can scale further.

Thank you for help, this issue can be closed.
