### ISSUE TITLE
Goroutine stack exceed on udf parameters unwrapping

### ISSUE THREAD

**Issue by small-egg** [aerospike/aerospike-client-go#272]
When I send types like `as.MapValue` or `as.ListValue` to `QueryAggregate`, I get such error because `GetObject` method returns object without type conversion to the specific type. 
So there is infinity recursion [there](https://github.com/aerospike/aerospike-client-go/blob/master/value.go#L1135).

Would you like to fix it?

**Comment by khaf** [comment]
Thanks for your PR. Merged in the latest release (v2.7.0)
