### ISSUE TITLE
Why the SortDescending is missing in the ListOrderFlags

### ISSUE THREAD

**Issue by cheung-chifung** [aerospike/aerospike-client-go#274]
Just curious that why `aerospike-client-go` doesn't support sorting a list in descending order.

https://github.com/aerospike/aerospike-client-go/blob/a670995419d924805fad5ad5601a484a6bd13d1f/cdt_list.go#L163

I checked the server-side's code, and it should support it (Anyway, I haven't tried it):

https://github.com/aerospike/aerospike-server/blob/6c8c7e96ab83b51a9d96c9c52ea13f6d51ab6ec6/as/include/base/proto.h#L456

https://github.com/aerospike/aerospike-server/blob/6c8c7e96ab83b51a9d96c9c52ea13f6d51ab6ec6/as/src/base/particle_list.c#L4121

I also checked the client API for Java, and the SortDescending disappeared as well.

https://www.aerospike.com/apidocs/java/index.html?com/aerospike/client/cdt/ListSortFlags.html

Is it any reason to remove it from the client-side code?

**Comment by khaf** [comment]
Thanks for your report and sorry for the late reply, we needed to double check.
It seems that we have overlooked this feature. Will land in the next few days.

**Comment by khaf** [comment]
Support added in v2.7.0.
