### ISSUE TITLE
What is the proper way to pass array as a parameter to UDF?

### ISSUE THREAD

**Issue by qw4n7y** [aerospike/aerospike-client-go#275]
Good day! I have confusions about the right way to pass array to UDF. I've not found any info about that in docs.
Goal: pass array of integers to filter records. So i've wrote UDF with filter / map pipeline and made calls with `QueryAggregate`
My first approach: pass slice wrapped with `aerospike.NewValueArray` / `aerospike.NewListValue`. That worked and in UDF i've got this argument seeing as `userdata`. But! after that memory leak had always occur:
<img width="200" alt="Screen Shot 2019-12-18 at 12 09 20" src="https://user-images.githubusercontent.com/1701687/71072292-3b784880-218f-11ea-9721-12f221bcbd43.png">
<img width="200" alt="Screen Shot 2019-12-18 at 12 10 00" src="https://user-images.githubusercontent.com/1701687/71072332-534fcc80-218f-11ea-8a20-00d02158a35b.png">
After all i've come with solution to pass array as a string (what a shame on me) and use `loadstring("return "..str)()` to parse the string into lua's `table` object.
What is the proper way for doing that? Thanks in advance

**Comment by khaf** [comment]
What do you mean by Memory leak? Does the memory utilization of your process (resident memory) increase over time? Memory utilization is different from memory leak.
Keep in mind that `QueryAggregate` fetches a lot of records back from the server and processes the final reduction on the client side. That would potentially use a lot of memory.

For filtering records on the server side, you could potentially use [`Predicates` ](https://github.com/aerospike/aerospike-client-go/blob/master/predexp_test.go#L149)

**Comment by qw4n7y** [comment]
By memory leak i meant explosive memory allocation which exceeded 1gb per go-routine constraint. Predicates are not the case since i can not filter records which has bins with value included in my set, only exact value or number range. There were only 3 records in my dev environment so there could not be many data there.
I came to the understanding that the most proper way is to keep all the data in the key, generate the keys of records of interest and make `client.BatchGet(policy, keys)`.

**Comment by khaf** [comment]
I don't know how much data you may have, but all that data is serialized for a lua engine to process for the final reduction. That lua engine MAY also not free that data fast enough.
If you could provide a gist, I may be able to help.

**Comment by khaf** [comment]
Did you make any progress?

**Comment by qw4n7y** [comment]
https://github.com/qw4n7y/golang-aerospike-client-issue-reproduction. Please have a look at code which reproduces my issue

**Comment by khaf** [comment]
Good news! This issue was related to #272, which is fixed in the latest release (v2.7.0)
