### ISSUE TITLE
Where to execute AQL?

### ISSUE THREAD

**Issue by kokizzu** [aerospike/aerospike-client-go#277]
for example i want to query like this when using aql command line: 
```
RECORD_PRINT_METADATA = true;
SELECT * FROM devices WHERE user_id = 3;
```
How to do this using the library?

**Comment by khaf** [comment]
If there is a secondary index on the `user_id`, you can do this:
```go
		stm := as.NewStatement(ns, set)
		stm.SetFilter(as.NewEqualFilter("user_id", id))

                qp := as.NewQueryPolicy()
		recordset, err := client.Query(qp, stm)
                // handle error here

		for res := range recordset.Results() {
                        if res.Err != nil {
                        // handle error here
                        } else {
			// use res.Record
                        }
		}
```

**Comment by khaf** [comment]
keep in mind that Aerospike is a NOSQL, key-value store, and does not directly support SQL.
AQL translates SQL to Aerospike API for quick and dirty data access. You need to use the API directly to access your data.

You can familiarize yourself with Aerospike, its capabilities and client API here: https://www.aerospike.com/docs/architecture/data-management.html
