### ISSUE TITLE
Need 'omitempty' functionality with 'as' struct tag.

### ISSUE THREAD

**Issue by kartavya-ramnani** [aerospike/aerospike-client-go#278]
The issue I am facing is : 

```
type Category struct {
	Code string `as:"code"`
	Description string `as:"description"`
}
```
I write a record and populate category Code and Description :

```
cat := Category{Code:"NB", Description:"NB is the best"}
policy := as.NewWritePolicy(0,0)
err = client.PutObject(policy, someKey, cat)
```

Now, if I just wish to update Description field of the struct, I donot enter Code value and update the document ( call PutObject with WritePolicy having RecordExistsAction = as.UPDATE)

But, obviously, my code gets rewritten to empty string.
Something like omitempty (like in json struct tag) will fix this. 

Is there a better solution at the moment  ?

**Comment by khaf** [comment]
At the moment there is no better solution. I will try to schedule this new feature for the next few releases.

**Comment by kartavya-ramnani** [comment]
Please do.
Also, I know everything is schema-less here, but a tag like binding:required which gin-gonic provides can also prove to be really helpful.
So, you can mention if a field should be omitted when there is omitempty tag and binding required can be used for compulsory fields.

**Comment by kartavya-ramnani** [comment]
Any updates on this @khaf  ?

**Comment by khaf** [comment]
It is coming in the next release in a couple of weeks.

**Comment by mariaefi29** [comment]
Dear @khaf,
 
I am subscribing to this thread to get any updates on the issue. Thank you!

**Comment by khaf** [comment]
All, I never knew so many people were using the reflection API, and needed the `omitempty`.
This feature was released today in v2.8.0.
Kindly give it a spin and let me know if I should close this ticket.

**Comment by mariaefi29** [comment]
Dear @khaf,

Just tested new feature on my application and everything works as expected. Thank you very much!

However, on the field in a struct with type `map[string]SomeStruct`:

```
type SomeStruct struct {
	ID      string                `as:"id"`
	Info      map[string]SomeStruct `as:"info,omitempty"`
	UpdatedAt int64                 `as:"updated_at,omitempty"`
}
```

`omitempty` tag works on nil case as I though it would be, but what if I would like to update that map only on one particular key and other map items to leave just the way they are? Is there any functionality to solve my problem? Functions `MapPutOp` and `MapPutItemsOp` don't work with custom struct types as values.

Would appreciate any ideas. Thank you!

**Comment by kartavya-ramnani** [comment]
Works as expected.
Will do a detailed testing and get back to you tomorrow.

**Comment by kartavya-ramnani** [comment]
@khaf  : Can you share the corresponding PR request as well ?

**Comment by khaf** [comment]
@kartavya-ramnani Here is the commit: https://github.com/aerospike/aerospike-client-go/commit/716f86aca5d8f1c53ffa7eac01dae19f90114544

**Comment by khaf** [comment]
@mariaefi29 I don't think there is an easy way of doing it. The `Put*` API does not support structs because it would need major reflection. The way to go in my opinion is to have your own struct -> map marshaller, and then use `Operate` command with `MapPutOp` or `MapPutItemsOp` API with proper policy to update only the key you want.

**Comment by mariaefi29** [comment]
@khaf  do I understand that by `map marshaller` you mean that I should put not a struct as a value on a map but encoded json as string for example?

**Comment by khaf** [comment]
@mariaefi29 Correct. A `map[string]interface{}`.

**Comment by mariaefi29** [comment]
@khaf Thank you very much! 

The solution of getting the struct with a map field from the database with client.GetObject, adding some items to a map and then do client.PutObject seems better then. What do you think? :)

**Comment by khaf** [comment]
@mariaefi29 Sure, if it fits your acceptable performance envelope.

**Comment by mariaefi29** [comment]
@khaf Thank you for your help!

**Comment by kartavya-ramnani** [comment]
Works as expected.
Closing this. 
Thank you for your help.
