### ISSUE TITLE
Put vs PutBins vs PutObject : Which has a better performance ? Which should be used ? 

### ISSUE THREAD

**Issue by kartavya-ramnani** [aerospike/aerospike-client-go#279]
I am confused whether to use client.Put or client.PutBins or client.PutObject to write records. 

I wish to know which func will have better performance and should be preferred. 

Will appreciate any help on this.

**Comment by khaf** [comment]
`Put` requires a `BinMap` as input (which is a `map[string]interface{}` under the hood). This can be fast and economic if your original data is in json form.
`PutBins` requires a slice of bins. It can be marginally faster and more memory friendly, but only if the data is coming from an struct or the like, especially if you already wrap the data in its appropriate `Value` form.
`PutObject` accepts an object and uses reflection to decide what to do with it. It is actually sometimes faster than the other two methods, but incurs more allocations in general. That will cause more GC cycles and can lead to more latency.

**Comment by kartavya-ramnani** [comment]
@khaf  : Got it. Thanks. :)
