### ISSUE TITLE
Panic in v2.7.0 with client compression enabled

### ISSUE THREAD

**Issue by tchiam** [aerospike/aerospike-client-go#280]
After updating to v2.7.0 and enabling client-server compression, my instances are panic-ing with the message:

panic: runtime error: index out of range

goroutine 42686 [running]:
encoding/binary.binary.bigEndian.Uint64(...)
	GOROOT/src/encoding/binary/binary.go:124
github.com/aerospike/aerospike-client-go/utils/buffer.BytesToInt64(0x0, 0x0, 0x0, 0x0, 0x0)
	external/com_github_aerospike_client_go/utils/buffer/buffer.go:78 +0x71
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xc9457a7900, 0x2d22b80, 0xc9457a7900, 0xc708d92fa0, 0x0, 0x0)
	external/com_github_aerospike_client_go/multi_command.go:146 +0x1c9
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc9457a7900, 0x2d22b80, 0xc9457a7900, 0x449201, 0x4fa70c0, 0xc8885fe638)
	external/com_github_aerospike_client_go/command.go:1894 +0x777
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).execute(0xc9457a7900, 0x2d22b80, 0xc9457a7900, 0xc42087ad01, 0xc42099ff90, 0xc42099ff58)
	external/com_github_aerospike_client_go/multi_command.go:351 +0x148
github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute(0xc9457a7900, 0x2b8aa48, 0xc949f2c890)
	external/com_github_aerospike_client_go/batch_command_get.go:247 +0x43
github.com/aerospike/aerospike-client-go.(*Client).batchExecute.func1(0xc949f2c890, 0xc949f2c8a0, 0xc452425920, 0xc949f2c888, 0x2d22b80, 0xc9457a7900)
	external/com_github_aerospike_client_go/client.go:1299 +0x65
created by github.com/aerospike/aerospike-client-go.(*Client).batchExecute
	external/com_github_aerospike_client_go/client.go:1297 +0x259

**Comment by khaf** [comment]
Do you know how big your records are?

**Comment by tchiam** [comment]
Here's a hist dump if that's helpful:
units=bytes:[128-256)=18244202:[256-512)=5015675:[512-1K)=1618314:[1K-2K)=7117450:[2K-4K)=4633586:[4K-8K)=2721101:[8K-16K)=1300978:[16K-32K)=510150:[32K-64K)=164309:[64K-128K)=45954:[128K-256K)=11783:[256K-512K)=2871:[512K-1M)=648:[1M-2M)=166:[2M-4M)=30:[4M-8M)=8

**Comment by khaf** [comment]
After hours of trying, I was unable to reproduce the issue. I noticed that there is a read call near the panic site that may be causing this issue in case of network errors.

I have released a minor version that corrects that issue. Can you check and see if this fix resolves your issue?

**Comment by tchiam** [comment]
Thanks Khosrow! The panics are gone now, and compression is working as expected. Thanks for the quick fix!

**Comment by khaf** [comment]
My pleasure. Sorry for the inconvenience.

**Comment by tchiam** [comment]
Another panic popped up after upgrading to v2.7.1, but happens a lot less frequent that the first one. Seems like a similar issue? Logs:

Requested to read 8 bytes, but 0 was read. (command execution timed out on client: See `Policy.Timeout`)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a9349d]
goroutine 7889702 [running]:
github.com/aerospike/aerospike-client-go.(*Connection).Read(0xc715624c80, 0xd51d822000, 0x9fbac, 0x9fbac, 0x8, 0xc7124f3100, 0x0, 0x0)
    external/com_github_aerospike_client_go/connection.go:188 +0xad
github.com/aerospike/aerospike-client-go.(*bufferedConn).readConn(0xc636a12848, 0x8, 0x0, 0x0)
    external/com_github_aerospike_client_go/buffered_connection.go:91 +0x1ca
github.com/aerospike/aerospike-client-go.(*bufferedConn).read(0xc636a12848, 0x8, 0xcc14008730, 0xcc98853c68, 0x1a94581, 0x2de42a0, 0xc7124f3100)
    external/com_github_aerospike_client_go/buffered_connection.go:104 +0xaa
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).readBytes(0xc636a12780, 0x8, 0x11815, 0x2de44a0)
    external/com_github_aerospike_client_go/multi_command.go:215 +0x134
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xc636a12780, 0x2e295c0, 0xc636a12780, 0xc715624c80, 0x0, 0x0)
    external/com_github_aerospike_client_go/multi_command.go:142 +0x3c3
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc636a12780, 0x2e295c0, 0xc636a12780, 0xc5c8545301, 0x2b02540, 0xc9a9e2adc0)
    external/com_github_aerospike_client_go/command.go:1894 +0x777
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).execute(0xc636a12780, 0x2e295c0, 0xc636a12780, 0xcdcc026801, 0xc715cd4fa8, 0xc715cd4f58)
    external/com_github_aerospike_client_go/multi_command.go:353 +0x148
github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute(0xc636a12780, 0x2c8fa88, 0xcdc72cdba0)
    external/com_github_aerospike_client_go/batch_command_get.go:247 +0x43
github.com/aerospike/aerospike-client-go.(*Client).batchExecute.func1(0xcdc72cdba0, 0xcdc72cdbb0, 0xcb8ea24a20, 0xcdc72cdb98, 0x2e295c0, 0xc636a12780)
    external/com_github_aerospike_client_go/client.go:1299 +0x65
created by github.com/aerospike/aerospike-client-go.(*Client).batchExecute
    external/com_github_aerospike_client_go/client.go:1297 +0x259

**Comment by khaf** [comment]
Unfortunately it's not the same issue. I'll have to dig deep for this one.

**Comment by khaf** [comment]
Just for curiosity, what is the frequency of this panic? per hour, day?

**Comment by clusc** [comment]
No it happens a lot more often than that. For our high scale application I can see around ~100 panics last hour.

**Comment by khaf** [comment]
It looks like you have quite a bit of network issues. I had not anticipated some of the network errors that could happen and their frequncy.

The latest release should take care of the panics. Feel free to close the ticket, or open new ones.

**Comment by tchiam** [comment]
Issue seems to be resolved now, thanks! Yeah we've been seeing these network issue talking to AS servers since the beginning, but that's another long term issue to chase. Thanks for the quick fix as always!
