### ISSUE TITLE
Need History-Enabled or Audit feature with the client.

### ISSUE THREAD

**Issue by kartavya-ramnani** [aerospike/aerospike-client-go#281]
Hey, 
I wish to maintain an audit or history feature enabled and I am not able to find that feature in the client. 
An audit feature is extremely necessary for production code bases so that we can track any changes done in the DB. This helps in debugging and ensures sanity of the system.

Please help.

**Comment by khaf** [comment]
Hi, I'm not sure I understand your request well. Can you expand on your request a bit and provide some examples of what you intend to achieve?

**Comment by kartavya-ramnani** [comment]
Hey,
So, say there is a set : moviegenres 
And I have multiple records with key : "suspense" or key : "rom-com" and bins : genre_description, genre_rules etc

Now, If someone adds or edits suspense record, I want to have a history or audit of all the changes done to that record or to any record to that set. 
Like, this was the change which was done to this set at this time. 

````
// historyModel
type historyModel struct {
	operation string
	request string
	time string

	username string
}
````

Something like this : operation can be UPDATE, DELETE, CREATE
Request can be whatever bins have been updated or a record has been deleted or a new record has been created. 
time will be the time when this took place

and username can be something to identify which user or an external service which performed this operation.

**Comment by khaf** [comment]
This is not in the scope of what a database driver is supposed to do, especially since the audit differs from user to user.

To do it yourself, you should wrap the database driver, and then provide the API required to provide the audit for you. Very simplified example:

```go
type AuditedClient *aero.Client

func (ac AuditedClient) Put(...) {
   // make and validate the audit
   auditValue := MakeAudit(...)
   
   // apply the transaction
   err := ac.Put(...)
   if err != nil {
      // handle the error
   }

   // publish the audit (to network agent, logs, etc.)
   if err := publishAudit(auditValue); err != nil {
        // handle the error
   }
}
```

**Comment by kartavya-ramnani** [comment]
Got it.
Thanks.
