### ISSUE TITLE
How to test without running real Aerospike servers.

### ISSUE THREAD

**Issue by grossjo** [aerospike/aerospike-client-go#283]
Is there a way to write tests without having real Aerospike servers running?

**Comment by khaf** [comment]
No, not at the moment.

**Comment by grossjo** [comment]
Any plans for this? Or is the recommended practice to run a real Aerospike server.
And how would this work with an enterprise license, where you don't want to distribute the license wildly outside of production but need the multiple namespace support?

**Comment by khaf** [comment]
We test the client against real databases to ensure maximum compatibility. I'm not really qualified to answer queries about licensing. 

I recommend you ask this question directly from our support, or on our forums. Let me know in case you don't get your answer right away, and I'll try the shortcut route.

**Comment by grossjo** [comment]
I'll track down our support contact. Thanks!
