### ISSUE TITLE
Lots of "Node not found for partition" during migration

### ISSUE THREAD

**Issue by fillest** [aerospike/aerospike-client-go#291]
We have a loaded two-node Aerospike cluster (replication-factor 3, one node disabled currently). For example, after some hiccup it begins to migrate. The migration takes many many hours (DB size is many hundreds of Gbs at ~500M records and I can't speed migrations up because Aerospike begins to periodically restart rebalancing indefinitely with no apparent resource-wise reason). During the migration each client gets a ```command execution timed out on client: Exceeded number of retries. See `Policy.MaxRetries`. (last error: Node not found for partition some_name:N in partition table.)``` about once a minute at average. Minimizing `TendInterval` doesn't seem to help.

I was thinking: let's imagine a client refreshes partition info in the background. And during migrations a lot of partitions change its masters periodically. So probably some operations hit the stale master or something like this. Is this the case? Shouldn't it be handled by the library transparently? The error rate is quite high when there are lots of client machines and the migration takes many hours or even days.

aerospike-client-go 2.7.2, aerospike C-4.5.0.10

Client setup currently looks like this:
```go
cliPolicy := as.NewClientPolicy()
cliPolicy.Timeout = 10 * time.Second
cliPolicy.IdleTimeout = 30 * time.Second
cliPolicy.ConnectionQueueSize = 256 * 2 * 2 * 2
//cliPolicy.TendInterval = 10 * time.Millisecond
Client, err = as.NewClientWithPolicyAndHost(cliPolicy, ahosts...)
defReadPolicy := as.NewPolicy()
defReadPolicy.SocketTimeout = 250 * time.Millisecond
Client.DefaultPolicy = defReadPolicy
wcnum, err := Client.WarmUp(500) 
```
Server-side migration parameters are currently: migrate-threads 1, migrate-max-num-incoming 4, migrate-sleep 1

**Comment by fillest** [comment]
After some more googling, according to https://discuss.aerospike.com/t/understanding-aerospike-server-proxies/3246 it seems that requests to the "wrong" partition's master are expected to be tranparently server-side-redirected to the proper master. If that is the case then what can these "Node not found for partition" during migrations mean at all?

**Comment by khaf** [comment]
It means the client does not know the master node for that Key (if it is a write), or any node for that partition.
I'm not sure what are the conditions this could happen (if any), but I'll investigate and get back to you.

**Comment by fillest** [comment]
client stats on one of machines:
```
map[
host1:map[closed-connections:22642 connections-attempts:22678 connections-failed:22595 connections-pool-empty:591 connections-successful:22678 node-added-count:1 node-removed-count:0 open-connections:35 partition-map-updates:1 tends-failed:0 tends-successful:6306 tends-total:6306]

host2:map[closed-connections:23775 connections-attempts:23801 connections-failed:23727 connections-pool-empty:0 connections-successful:23801 node-added-count:2 node-removed-count:1 open-connections:26 partition-map-updates:1 tends-failed:0 tends-successful:6304 tends-total:6304]

cluster-aggregated-stats:map[closed-connections:46417 connections-attempts:46479 connections-failed:46322 connections-pool-empty:591 connections-successful:46479 node-added-count:3 node-removed-count:1 open-connections:61 partition-map-updates:2 tends-failed:0 tends-successful:12610 tends-total:12610]

open-connections:61]
```

**Comment by khaf** [comment]
How long has that app server been up, and how much traffic does it get? For a busy server, that's a rather high number of failed connections, either due to network disruptions, or low timeout settings.

**Comment by fillest** [comment]
Hard to say about life time, because at the moment (migrations were triggered again) app periodically fully crashes due to aforementioned error in some background goroutines (no recovery code yet). I think, in the order of tens of minutes.
What is this number's semantic? Are these just failures during pool "resize", or connections get closed on operation/io timeouts (Policy.SocketTimeout?) too (or something like that)?

**Comment by khaf** [comment]
Connections are closed on timeouts or other network errors. 22.5K connection failures in tens of mins, and constant migrations are caused by outrageously bad network connections.
I think you should first investigate what causes this situation.

**Comment by fillest** [comment]
Migrations seem to be triggered by particularly nasty "hot key" bursts, I think - I've figured out this correlation recently.

Regarding network problems - I monitor latencies of all requests (via parsing nginx access log), including `max` stat - it normally rarely exceeds couple of hundreds of ms. Shouldn't it be quite spiky if we had a lot of timeouts? Or could it be resets... masked by client transparently reconnecting. Hmm.. Would be great to trace these failures in the client but I don't see any logging in the code in these places. Or is it there?
We run these machines on baremetal in Hetzner in one DC. Existence of persistent networking problems seems unlikely... But I will try to investigate. The only clear suspicious thing that I'm observing is some small stream of 499 nginx errors (we run haproxy->nginx->app). But - again - probably it should show itself on latency graphs, otherwise it can just haproxy misbehaving..

**Comment by khaf** [comment]
Have you made any progress on this issue? I'm interested to know if you managed to resolve this issue and whether the problem is related to the client and needs more attention.

**Comment by khaf** [comment]
Closing the issue due to inactivity. Feel free to reopen or file a new issue.
