### ISSUE TITLE
Read from connection in putBins

### ISSUE THREAD

**Issue by SlavaNovikov** [aerospike/aerospike-client-go#293]
Hey.
When I execute putBins, then parseResult is executed, the inserted object is inside. nettop shows that the byte is returned more than it is sent, which is strange, I don’t need this object back and the time it takes to read it from the connection increases the operation time. Can i avoid this?

**Comment by khaf** [comment]
The returned result is the server response to ensure your your command was executed successfully. You are not getting the object back.

How big is your object?

**Comment by SlavaNovikov** [comment]
my object size 2662 Byte
in request send 2999byte, return 3256byte
dump buffer show my object

**Comment by khaf** [comment]
Can you share a simple gist of your code?

**Comment by khaf** [comment]
You are making a mistake somewhere. I checked via the following code and `PutBins` returns 22 bytes as it should. You can check the code yourself here: `func (cmd *writeCommand) parseResult`

It reads only `_MSG_TOTAL_HEADER_SIZE` bytes, which is 30; 8 bytes are the message header.

Here is the code I tested with:

```go
package main

import (
	"log"
	"strings"

	as "github.com/aerospike/aerospike-client-go"
)

const (
	host = "vmu1604"
	port = 3000

	ns  = "test"
	set = "test"

	payloadLen = 300
)

func main() {
	policy := as.NewClientPolicy()
	policy.User = ""
	policy.Password = ""

	client, err := as.NewClientWithPolicyAndHost(policy, as.NewHost(host, port))
	if err != nil {
		log.Fatalln("failed to connect:", err)
	}

	wp := as.NewWritePolicy(0, 0)

	key, _ := as.NewKey("test", "test", 1)
	ok, err := client.Delete(wp, key)
	log.Println("del err:", err, ok)

	b := as.NewBin("bin", strings.Repeat("a", payloadLen))
	err = client.PutBins(wp, key, b)
	log.Println("put err:", err)

	rec, err := client.Get(nil, key)
	log.Println("get err:", err)
	log.Println("get results:", rec.Bins)
}
```

**Comment by SlavaNovikov** [comment]
Thank you, you're right. The cycle of requests showed that at first it was not my object, but an exchange of service information.

**Comment by khaf** [comment]
Keep in mind that if MongoDB is faster, it's either because you are using MongoDB in single server mode and Aerospike in cluster mode, or MongoDB is not configured to replicate to other nodes synchronously.
