### ISSUE TITLE
Export estimateSize method for different Datastructures

### ISSUE THREAD

**Issue by sainadh-d** [aerospike/aerospike-client-go#298]
The **estimateSize** method on different Data structures like _MapValue_, _ListValue_ etc is unexported in the go client, where as the same is Public in Java Client.

Is there any reason for keeping this unexported ? It would be useful thing to get approximate estimates of record sizes.

**Comment by khaf** [comment]
No specific reason, I can expose them later. Although keep in mind that these are expensive methods for lists and maps.

**Comment by sainadh-d** [comment]
@khaf Thanks for the response. I did the changes in my fork a while back for testing something. 
Pls check https://github.com/aerospike/aerospike-client-go/pull/299
True that these are expensive. I was just using it for estimation purposes and not in the critical paths of the application.

**Comment by khaf** [comment]
Resolved in v2.11.0.
