### ISSUE TITLE
BatchGet returns nil after idleTimeout since v3.0.0

### ISSUE THREAD

**Issue by chorin1** [aerospike/aerospike-client-go#305]
Sending a BatchGet after idleTimeout returns nil with no error even though the records exist.
To reproduce:
1. Set a low idleTimeout or wait the default 55 seconds.
2. Send a batchGet for a single (or more) keys.

### client configuration:
```
    "clientConfig": {
      "connectionQueueSize": 128,
      "openingConnectionThreshold": 0,
      "limitConnectionsToQueueSize": true,
      "tendInterval": "10s",
      "idleTimeout": "25s"
    },
    "batchConfig": {
      "totalTimeout": "2s",
      "allowPartialResults": true,
      "concurrentNodes": 42
    }
```

### Aerospike server:
checked with versions 4.5.1 & 4.2.0.5
`proto-fd-idle-ms` = 60k

### More info:
* Does **not** reproduce on aerospike-client-go client 2.12.0 and below.
* Sending consequent requests below the idle timeout returns the records as expected.
* Changing TendInterval to the default value does not help.
* newBatchNodeList returns the same node on both occasions (nil records and records with data)

**Comment by khaf** [comment]
Thanks you for your report, the `IdleTimeout` observation was a time saver. Should be fixed in v3.0.3.
