### ISSUE TITLE
Connect fails: domain lookups on IP fail

### ISSUE THREAD

**Issue by hopkinsth** [aerospike/aerospike-client-go#31]
If I try to connect to an aerospike cluster by IP, I get output like this when I enable debug output.

```
2014/11/17 21:28:04 No connections available; seeding...
2014/11/17 21:28:04 Seeding the cluster. Seeds count: 1
2014/11/17 21:28:04 Seed 127.0.0.1:3000 failed: lookup 127.0.0.1: invalid domain name
2014/11/17 21:28:04 Tend finished. Live node count: 0
2014/11/17 21:28:04 No connections available; seeding...
2014/11/17 21:28:04 Seeding the cluster. Seeds count: 1
2014/11/17 21:28:04 Seed 127.0.0.1:3000 failed: lookup 127.0.0.1: invalid domain name
2014/11/17 21:28:04 Tend finished. Live node count: 0
2014/11/17 21:28:04 Failed to connect to host(s): [127.0.0.1:3000]
```

When I change the IP address to a valid hostname, I get output like this...
```
2014/11/17 21:23:51 No connections available; seeding...
2014/11/17 21:23:51 Seeding the cluster. Seeds count: 1
2014/11/17 21:23:51 Node Validator has 1 nodes.
2014/11/17 21:23:51 Seed ip-10-10-200-210.ec2.internal:3000 failed: lookup 10.10.200.210: invalid domain name
2014/11/17 21:23:51 Tend finished. Live node count: 0
2014/11/17 21:23:51 No connections available; seeding...
2014/11/17 21:23:51 Seeding the cluster. Seeds count: 1
2014/11/17 21:23:51 Node Validator has 1 nodes.
2014/11/17 21:23:51 Seed ip-10-10-200-210.ec2.internal:3000 failed: lookup 10.10.200.210: invalid domain name
2014/11/17 21:23:51 Tend finished. Live node count: 0
2014/11/17 21:23:51 Failed to connect to host(s): [ip-10-10-200-210.ec2.internal:3000]
```

You can see the program I'm using to test this issue here: https://gist.github.com/hopkinsth/2b2c68b1a116ff3f40c1

I'm running this on an EC2 instance; `uname -r` is 3.10.40-50.136.amzn1.x86_64.

The host I'm trying to connect to definitely runs the Aerospike server on that port. I'm separately using the aerospike Java library to connect to it.

**Comment by quexer** [comment]
@hopkinsth is there any workaround for this issue ? we're adopting aerospike and we love cross compile

**Comment by hopkinsth** [comment]
@quexer Not really, I'm sad to say!

The easiest solution is to compile your program on linux rather than whatever you're doing now. Even if you force cgo (something like `CGO_ENABLED=1 go build`), the linker might link against a library file that doesn't exist on linux. I can't even get my old test program to build now (with `CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build`) because the OSX (i.e. BSD) linker has different command line options, or, specifically, it spits this out:

```
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So, I would say build this on linux! You may need to work your program architecture around that need. Or convince the authors of this library or the Go DNS fallback code to behave differently. 

You could always mess around with your local environment, but you would probably need – and someone should correct me, because I'm not 100% sure if this would work on, e.g. OSX – glibc and the GNU linker installed and functional on your machine. This *might* be a little easier if you're building on Windows, but really, just build in Linux. 

You could set up a VM with Vagrant (or by hand, even) to take care of that. It's a pain, but it's the easiest option.

**Comment by quexer** [comment]
@hopkinsth 
We've been using mgo ( golang driver of mongodb )  for some time and  it doesn't have this issue.
So I guess it can be fixed by the author of this library although I haven't dug into the code.
Maybe you can re-open this issue, let the author know.

**Comment by quexer** [comment]
@khaf I know aerospike is optimized for Linux, it will be great if cross compilation support could be added

**Comment by hopkinsth** [comment]
@quexer That mgo works doesn't really have any bearing on this library, though. mgo probably doesn't do DNS lookups on IP addresses or whatever aerospike-client-go is actually doing—calling some DNS function ( the `net` package's `LookupHost`, I think) with an IP address where the fallback DNS code only expects to operate on hostnames.

aerospike-client-go is relying on the fact that some DNS function is OK with being passed an IP address instead of a hostname when it's compiled with underlying C headers. The Go DNS fallback – which is what you're going to be using when compiling for another architecture – fails because it doesn't operate on an IP address... or something like that! It's been a while since I've looked into it.

So, yes, either this library *or* the Go DNS code needs to change if this library would work in compilation for different architectures. There's a good case for either and neither. Aerospike only runs on Linux, so it is reasonable for this client library to ultimately rely on linking against a library available on linux, even though the way it does this lookup strikes me as a little weird—why run a DNS function for an IP address when you don't need to?

On the other hand, that the Go DNS fallback seems to be inconsistent with behavior in shared libraries on at least two target platforms: OSX and Linux. Maybe it should be more consistent with those platforms.

It was easy enough for my team to build this program on Linux – either through a local VM or on a remote server – when deploying production code, so that's what we chose to do at the time. Unfortunately we're not using that service (or the aerospike DB) anymore.

I would be glad to compile more information about what the call stack looks like when the code hits this condition, but I'm several months and versions of Go removed from it.

**Comment by khaf** [comment]
Thank you @quexer  and @hopkinsth for the very educating discussion.

It is correct that the issue here that Go's LookupHost on Mac doesn't like an IP to be passed to it (or rather what it does is undefined). 

We had another user in our forums who came up with a solution.

I've been experimenting with that solution, and will publish it in a branch tomorrow for experimentation.

Thoughts?

**Comment by ariane6** [comment]
@quexer and @hopkinsth: the post referenced by @khaf on our forums is here: https://discuss.aerospike.com/t/failing-to-connect-to-cluster/1006/3

**Comment by quexer** [comment]
Thanks, I'm ready to try and test this fix

**Comment by khaf** [comment]
In Master now; Please give it a try and let me know.

**Comment by quexer** [comment]
It works in my environment:   cross compile on mac, deploy to 64bit Linux.
Thanks!

**Comment by khaf** [comment]
Cool! Thank you everyone for the productive discussion.

Closing the ticket for good :)
