### ISSUE TITLE
Feature Request: Add tls support for benchmark tool

### ISSUE THREAD

**Issue by chanchal1987** [aerospike/aerospike-client-go#313]
Aerospike [Java Benchmark utility](https://www.aerospike.com/docs/client/java/benchmarks.html) already has option to enable TLS. Please add support for tls in [go benchmark tool](https://www.aerospike.com/docs/client/go/benchmarks.html) also.

**Comment by khaf** [comment]
Of course, will see if I can include it in the next release.

**Comment by khaf** [comment]
Added in v5.2.0. Thanks for your feedback. Feel free to open new issues.
