### ISSUE TITLE
What are the minorbreaking changes in v3?

### ISSUE THREAD

**Issue by grossjo** [aerospike/aerospike-client-go#316]
It's mentioned in the changelog, but the docs haven't been updated for years:

> Major feature release. There are a few minor breaking API changes. See Client Policy.
> 
> Note: There has been significant changes to clustering code. We recommend extensive testing before using in production.

**Comment by khaf** [comment]
Which docs do you mean? Release notes are always updated on our website. Your feedback will help us better understand where people look at so we can keep our docs updated.

**Comment by grossjo** [comment]
These notes: https://github.com/aerospike/aerospike-client-go/releases/tag/v3.0.0
I can't find the corresponding breaking changes anywhere.
