### ISSUE TITLE
How to horizontally add cluster nodes and modify configuration files to restart each service in the cluster without being affected

### ISSUE THREAD

**Issue by jclivi** [aerospike/aerospike-client-go#327]
How to restart cluster services without being affected

Configuration before horizontal expansion:
heartbeat {
mode mesh
address 192.168.127.128
port 3002
#all cluster
mesh-seed-address-port 192.168.127.128 3002
mesh-seed-address-port 192.168.127.131 3002

    # aerospike_mesh.conf for alternative.
    interval 150
    timeout 10      
    }
Configuration after horizontal expansion:
heartbeat {
mode mesh
address 192.168.127.132
port 3002
#all cluster
mesh-seed-address-port 192.168.127.132 3002
mesh-seed-address-port 192.168.127.128 3002
mesh-seed-address-port 192.168.127.131 3002

    # aerospike_mesh.conf for alternative.
    interval 150
    timeout 10      
    }

**Comment by realmgic** [comment]
That is not exactly a Go client question - but by adding an additional node and letting it know about the existing nodes, it will automatically join the cluster and start data migrations. Once partitions (shards) are moved to the new node, the clients would automatically start using it without any change in the application side.

For more information about that process: https://aerospike.com/docs/operations/manage/cluster_mng/adding_node/index.html

For Aerospike general questions I recommend joining the forums: https://discuss.aerospike.com.
