### ISSUE TITLE
connection_heap remainder issue

### ISSUE THREAD

**Issue by xqzhang2015** [aerospike/aerospike-client-go#332]
Should it be this?
<pre>
if maxSize-(perHeapSize*heapCount) > 0 {
}
</pre>

https://github.com/aerospike/aerospike-client-go/blob/163beaf5fce2a90b8a7690b5c41aa58347b9f224/connection_heap.go#L195

**Comment by xqzhang2015** [comment]
@khaf Would you like to give any comment?

**Comment by khaf** [comment]
You are right. Seems like at some point I have changed the logic, but haven't changed the calcs everywhere. Will fix on today's release. Thanks for reporting the issue.

**Comment by khaf** [comment]
This was fixed in v4.1.0. I had missed putting the notice in the Changelog. Thanks for the report, and the Changelog will be updated in the next release.
