### ISSUE TITLE
Batch Operations instead of just gets or exists

### ISSUE THREAD

**Issue by JonasHiltl** [aerospike/aerospike-client-go#371]
I just wanted to know if it's possible to batch operations instead of the predefined commands, like `batchGet` or `batchExists`.
I was hoping to be able to batch multiple Operations like `MapPutItemsOp` or `MapRemoveByKeyOp` together to be executed in one network request.

**Comment by khaf** [comment]
The new Aerospike server v6, released a few weeks ago supports this functionality. You can use the `BatchOperate` API in the also new Go client v6 to achieve what you want.

**Comment by JonasHiltl** [comment]
Thanks for your fast response, exactly what I was looking for.

**Comment by khaf** [comment]
No problem. Let me know how it goes and don't hesitate to file other tickets if you encounter any road blocks.
