### ISSUE TITLE
Use Bytes() instead of Interface().([]byte) for reflect.Slice marshalling

### ISSUE THREAD

**Issue by slobodyanyuk** [aerospike/aerospike-client-go#382]
When trying to marshal field with custom type that has bytearray underneath (like datatypes.JSON from GORM) I get this:
`interface conversion: interface {} is datatypes.JSON, not []uint8`

In our mocks I replaced the following line:
[[/marshal.go](../marshal.go#L113)](https://github.com/aerospike/aerospike-client-go/blob/b936c147db0d7ac5f881c3bde9df87e9a6829dfa/marshal.go#L113)

with:
`return f.Bytes()`

And everything seems to work well.

Is this possible to do the same in aerospike-client?
Return bytes without type assertion seems quiet safe because **(reflect.Value).Bytes** says:
`Bytes returns v's underlying value. It panics if v's underlying value is not a slice of bytes.`

**Comment by khaf** [comment]
Thank you for your feedback. This issue was addressed in v6.4.0 released September 16 2022.
