### ISSUE TITLE
increment counter for map 

### ISSUE THREAD

**Issue by artman92** [aerospike/aerospike-client-go#385]
I'd like to implement an incremental counter for map -
Right now I am using
```go
aerospike.PutOp(aerospike.NewBin("binName", map[string]string{
constants.key1:     fmt.Sprintf("%v", a),
constants.key2:    fmt.Sprintf("%v",b),
})
_, err = asClient.Operate(nil, asKey, ops...)
```
  My worry is that with too many concurrent queries I want to lock it so that the values will be correct everytime.

**Comment by khaf** [comment]
You need to use CDT operations:

```go
	op := as.MapIncrementOp(as.DefaultMapPolicy(), "binName", "keyNameInsideMap", 1)
	res, err := client.Operate(nil, key, op)
```

**Comment by khaf** [comment]
Closing the issue. Don't hesitate to open a new ticket for any questions you may have.
