### ISSUE TITLE
v5.9.0 retagged?

### ISSUE THREAD

**Issue by Aneurysm9** [aerospike/aerospike-client-go#386]
I have encountered a checksum mismatch attempting to use `github.com/aerospike/aerospike-client-go/v5@v5.9.0`.  This happens when using `GOPROXY=direct`, which is a requirement for me.  Was the tag for this release modified at some point?  Can a `v5.10.0` be tagged to allow the module resolver to be placated.

```
verifying github.com/aerospike/aerospike-client-go/v5@v5.9.0: checksum mismatch
        downloaded: h1:9YM7hGTKjkNjE/VPa5q4teFcsq9jLBJmifNHoTYH40U=
        go.sum:     h1:x5qdd0jLTPLh8mXIDsMszDoXSJzDo/wSGeo3EOLIdsc=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

**Comment by khaf** [comment]
IIRC I deleted and reissued that release immediately after the initial release. Is it not possible to delete what you have in your Go sum and cache and and download it again?

**Comment by khaf** [comment]
Did you resolve this issue or do you still need a re-release?

**Comment by Aneurysm9** [comment]
We have had multiple reports of this issue, including some reporting that clearing caches was ineffective as an attempted resolution.

**Comment by khaf** [comment]
v5.9.1 released to address this issue.
