### ISSUE TITLE
Question about type checking

### ISSUE THREAD

**Issue by kalloc** [aerospike/aerospike-client-go#39]
I tried to put json struct into aerospike, and I have panic.
JSON decoder, has default rule for integer to decode as float64.

Aerospike doesn't allow float64, it accepts only intxx.

My question: Is it a good idea to gently converting floatxx to intxx?
For example:
var test1 float64 = 10 -> int64(10) 
but
var test2 float64 = 10.1 -> TYPE_NOT_SUPPORTED

I can write pull-request for this case, If you will approve or I can reconvert structure in my code

**Comment by khaf** [comment]
We released a new client which supports automatic marshaling of objects. 

Have a look at [Changelog](https://github.com/aerospike/aerospike-client-go/blob/master/CHANGELOG.md) or [Marshal Test](https://github.com/aerospike/aerospike-client-go/blob/master/client_object_test.go) and let me know.

**Comment by kalloc** [comment]
@khaf thank you :)

**Comment by alexkappa** [comment]
This is an awesome feature, thanks a lot @khaf!
