### ISSUE TITLE
Field Port in type Host is Int

### ISSUE THREAD

**Issue by kennykarnama** [aerospike/aerospike-client-go#390]
## Question

I just want to understand, why in `Host` struct, `Port` is in `int` type not in `string` ?

Because I check you use `net.SplitHostPort` that returns a string and then you need to convert it back and you convert it again to string in here: https://github.com/aerospike/aerospike-client-go/blob/master/connection.go#L119

Also, for the reference: https://stackoverflow.com/questions/47992477/why-is-port-a-string-and-not-an-integer

**Comment by khaf** [comment]
That's to mimic our other clients. You can use the `NewHosts(...string)` utility function for a shortcut if you prefer.
