### ISSUE TITLE
Supporting `QueryPartitions` with non-nil filter (secondary index query)

### ISSUE THREAD

**Issue by chengc-sa** [aerospike/aerospike-client-go#392]
I see the current `v6` version does not support `QueryPartitions` while the filter is non-nil, while the Java library already supports it (I guess?), is there any plan to support it in the near future?

Go library: https://github.com/aerospike/aerospike-client-go/blob/v6/client.go#L1027

Java Library: https://github.com/aerospike/aerospike-client-java/blob/68f41e28ebc8de32c372b366b098579b39b11586/client/src/com/aerospike/client/AerospikeClient.java#L2956

**Comment by khaf** [comment]
Thank you for your report. This seems to be a bug. I'll address it this week.

**Comment by khaf** [comment]
Did you verify that the issue was resolved for you?

**Comment by chengc-sa** [comment]
> Did you verify that the issue was resolved for you?

Yes, it worked, thanks
