### ISSUE TITLE
Difference size of allocated memory between client v4.5 and v6.9.1

### ISSUE THREAD

**Issue by kennykarnama** [aerospike/aerospike-client-go#397]
Hi, I tried to do pprof in my go apps.

I noticed there is difference in size of memory allocation when I use client v4.5 and v6.9.1. IN v6.9.1, the total memory allocated is much better. 

Do you have any ideas what has been changed between v4.5 and v6.9.1?

Both use same parameters.

```
clientPolicy := as.NewClientPolicy()
clientPolicy.ConnectionQueueSize = 512
clientPolicy.LimitConnectionsToQueueSize = true
clientPolicy.Timeout = 5 * time.Second
clientPolicy.MinConnectionsPerNode = 5
```

Here is the profiling heap result.

v4.5

![out2_2](https://user-images.githubusercontent.com/26187880/215710317-231e6789-c81e-4eee-b3c8-bf82fdbd902b.png)

v6.9.1

![out3_3](https://user-images.githubusercontent.com/26187880/215710399-46c2df0c-f326-4dc6-995c-8b083fd7bb54.png)

**Comment by kennykarnama** [comment]
We are considering upgrading for v6. Just needs some justifications regarding this 😄

**Comment by khaf** [comment]
A lot of optimizations went into the v5 (which was the big update), but unfortunately, although I took a cursory glance at the change log, I could not come up with something that would be the sole improvement. Many things, including default values of various pools and buffers could influence this.

**Comment by kennykarnama** [comment]
I see. Thank you
