### ISSUE TITLE
Is there a way to get items in list for a PK?

### ISSUE THREAD

**Issue by sanudatta11** [aerospike/aerospike-client-go#403]
Hello,
is there a way to get the count of items in a list bin for a PK using golang client? Couldn't find a method exposed for same

**Comment by un000** [comment]
ListSizeOp


https://github.com/aerospike/aerospike-client-go/blob/v6/cdt_list_test.go#L555-L557

**Comment by khaf** [comment]
Thanks @un000 for your answer. Closing this. Feel free to reopen or issue a new ticket if you have any further questions in the future.
