### ISSUE TITLE
invalid go.mod on master

### ISSUE THREAD

**Issue by jpicht** [aerospike/aerospike-client-go#411]
The master branch contains a `go.mod` file that declares the package name to be `github.com/aerospike/aerospike-client-go`, but it's tagged with a v4 version.

Go requires that if a branch contains a `go.mod` file, that is tagged with a semver version, to include the major version in the package name:

```bash
$ go get github.com/aerospike/aerospike-client-go@v4.7.0
go: github.com/aerospike/aerospike-client-go@v4.7.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/aerospike/aerospike-client-go/v4")
```

The latest v4 version that can imported is v4.5.2, as that's the last version before the `go.mod` file has been added.

**Comment by khaf** [comment]
We have customers that have used this. I have no idea what compiler incantation you need to pass for it to work though. I have made a new `v4` branch with correct `go.mod` file and import paths. You can use that if you want. Use version `v4.7.1`.

**Comment by jpicht** [comment]
Works for me. Thanks!
