### ISSUE TITLE
Support more integer sizes in the Expressions API.

### ISSUE THREAD

**Issue by LEijsackersCS** [aerospike/aerospike-client-go#415]
In the expressions API it seems the only way to pass an integer value is using `ExpIntVal`:

```golang
// ExpIntVal creates a 64 bit integer value
func ExpIntVal(val int64) *Expression {
	return newFilterExpression(nil, IntegerValue(val), nil, nil, nil, nil)
}
```

However, as the comment states, this creates an int64 value, while it might be preferable to use smaller integer sizes (int32, int8). This would allow users to reduce the size over the wire as well as in the stored Aerospike record.

**Comment by khaf** [comment]
This is a server change request, and out of scope for the Go client. I'll mention it to our product manager though.
