### ISSUE TITLE
LStack range filter

### ISSUE THREAD

**Issue by scorpnode** [aerospike/aerospike-client-go#42]
Hi, I tried using your demo filter 
http://www.aerospike.com/docs/guide/examples/range_filter.html
I then registered the filter as sample_filters.lua and it can be seen in AMC.

tStack.Filter(10,"rangeFilter1",mapC)
gives me  an error
[] /opt/aerospike/sys/udf/lua/ldt/ldt_common.lua:602: 1431:LDT-Read Filter Not Found

Please advise. Thanks

**Comment by scorpnode** [comment]
figured it out thanks

**Comment by khaf** [comment]
To keep the solution in the record if someone else stumbles up on the same problem, was it the following in namespace configuration?

`ldt-enabled true`
