### ISSUE TITLE
How to use aerospike.GetObject with a [][]byte value

### ISSUE THREAD

**Issue by ajeetdsouza** [aerospike/aerospike-client-go#424]
I have a list of bytestrings in a bin that I'd like to fetch from Aerospike:

```go
type Event {
  ID string `as:"id"`
  Payloads [][]byte `as:"payloads"`
}
```

However, when doing a `GetObject` operation using this struct, `aerospike-client-go` treats this as a list of bytes rather than a bytestring:

```go
Invalid value `<VALUE>`  for slice field
```

I could work around it by using a `[]string`, but since these are arbitrary bytes and not UTF-8 strings, it seems to be a suboptimal approach. How can I do this correctly?

**Comment by khaf** [comment]
Sorry for the late reply. I can't repro this issue on the latest Go client. Which version of the client are you using?
Can you provide a gist that reproduces the issue?

**Comment by khaf** [comment]
Closing the issue due to inactivity. Feel free to file new issues or reopen the ticket for further assistance.
