### ISSUE TITLE
ExecuteTask.OnComplete function look weird without any comment for reason.

### ISSUE THREAD

**Issue by namkazt** [aerospike/aerospike-client-go#435]
@khaf  please take a look on this

![image](https://github.com/aerospike/aerospike-client-go/assets/6035916/e1dff491-7f8c-4de8-a6bb-ed6a47b413ab)

that last part look weird and it do not have any comment for a reason why.

**Comment by khaf** [comment]
Thanks for your feedback. This seems to have been the result of a botched merge, although it had no effect on the correctness of the code (they were unreachable code), but I thought I removed it for the v7.3 or v7.4 release.
Which version of the code is this from?

**Comment by namkazt** [comment]
oh, i'm using `v7.1.0`, thanks i will check newer version.
