### ISSUE TITLE
Client doesn't read from preferred rack

### ISSUE THREAD

**Issue by BernhardValenti** [aerospike/aerospike-client-go#455]
I was testing rack-aware reads but the results were always coming from the master node.

Traced this down to here:
https://github.com/aerospike/aerospike-client-go/blob/63370c8927591ab5d4a30e031c6046632be9ea3e/partition.go#L255C4-L255C9

`index` never changes inside the loop, which seems like a bug. changing the line to

```go
index := seq % len(replicas)
```

seems to fix it, but i'm not too familiar with the code so not going to make a PR.

**Comment by khaf** [comment]
Thank you for your report. The issue should be resolved in Go client v7.7.2.

**Comment by BernhardValenti** [comment]
@khaf just tested, and seems to work fine now. thanks for the quick fix!
