### ISSUE TITLE
Question about connection queue

### ISSUE THREAD

**Issue by imkira** [aerospike/aerospike-client-go#49]
I have noticed that the when the number of clients exceeds ClientPolicy.ConnectionQueueSize, all connections go directly to aerospike server.
I believe it would be better to have more control of what happens when the queue is full.
In my case, when all ConnectionQueueSize connections are being used, I would like to wait until one connection is freed, instead of creating one every single time.
This is because if we have a good number of clients sending an unpredictably large number of requests at a given time to the server, either side (but especially the server) may end up hitting the maximum number of TCP sockets/file descriptors available for the process and the connection will be immediately rejected.
The idea I have in mind is to change GetConnection function so that it uses the timeout to wait if no connection is available.
In this line of thought, I also thought it would be good to add another option similar to ConnectionQueueSize but instead calling it WaitingQueueSize (0 to use the current behavior and create a new connection everytime, -1 for unlimited, > 1 to wait up to N requests. after N, it would be immediately rejected)

This would be semantically compatible with the existing version.
What do you think of this?
If you think it's ok I am interested in submitting a PR for that.

**Comment by khaf** [comment]
Not a bad idea, though you should keep in mind that policies should be respected regarding the length of time a poll on the queue can wait. It is rather difficult getting it to perform well, but if you are interested in doing it (and not letting the performance decline), I won't object to it. 

This should be put as an option in the BasePolicy.

If it's done well, I will surely merge it in. Please let me know in case I can provide any help regarding your objective.

**Comment by hollow** [comment]
We've recently been hit by this issue. When aerospike is slow to respond (due to network issues or similar) and all connections in the pool are in use, the process calls connect for every request that comes in and eventuall DDoS'es itself with 100% CPU time spent in the connect syscalls. IT would be good to limit the number of total connections that are to be opened, and simply reject requests if the limit is reached.

**Comment by imkira** [comment]
"Good" to know we are not the only ones who hit this roadblock. We are also in urgent need to see this fixed, so I will try to work on this this week. I'll get back with a PR to tackle this problem.

**Comment by khaf** [comment]
I'll give it a thought as well.

**Comment by khaf** [comment]
Released and in master. Please refer to [CHAGELOG](https://github.com/aerospike/aerospike-client-go/blob/master/CHANGELOG.md) for version 1.5.0.

**Comment by imkira** [comment]
This is very good news. Thank you very very much for the support @khaf !

**Comment by khaf** [comment]
no problem. Any feedback is very welcome.
