### ISSUE TITLE
List secondary indexes

### ISSUE THREAD

**Issue by acasajus** [aerospike/aerospike-client-go#51]
I haven't been able to do get the list of indexes in the namespace. the equivalent to 

```
show indexes <namespace>
```
 
in aql

**Comment by khaf** [comment]
You need to ask for info from server:

```go
node := client.GetNodes()[0]
sindexMap, err := as.RequestNodeInfo(node, "sindex")
if err != nil {
	log.Fatalln(err.Error())
} 

sindexListStr := sindexMap["sindex"]
```
It is trivial to parse the result using `strings.Split` If you need index list in a particular namespace, replace "sindex" with "sindex/<namespace>" in the above code.

For more information, please refer to [Info Documentation](http://www.aerospike.com/docs/reference/info/#sindex)

Let me know in case you need more help.
