### ISSUE TITLE
unpacker.unpackBlob() returns a []byte that points to receiving buffer which is returned to pool

### ISSUE THREAD

**Issue by lming** [aerospike/aerospike-client-go#52]
In unpacker.go:
func (upckr *unpacker) unpackBlob(count int) (interface{}, error) {
...
val = upckr.buffer[upckr.offset : upckr.offset+count] 
...
return val, nil
}

However upckr.buffer is returned to the pool after the command finishes. So the returned blob values points to unclaimed memory buffers.

The symptom is that I ran client.execute() which returns a list of []byte that contains wrong value.

**Comment by khaf** [comment]
Thanks for the report. Fix is now in master.
