### ISSUE TITLE
Support uint64 as key or value

### ISSUE THREAD

**Issue by lming** [aerospike/aerospike-client-go#62]
Right now NewValue() or the like does not support uint64 that is greater than maxInt64.
It's inconvenient that I have to encode uint64 in some way before I can store it in Aerospike.
I think native support of uint64 is necessary.

**Comment by khaf** [comment]
This is a limitation of Aerospike server. Since there is no internal uint64 data type, we cannot store it and read it as a uint64.

You don't need to encode to store it though. Just cast it to `int`:
```go
t := uint64(math.MaxInt64)
v := NewValue(int(t))

r, err := Get(policy, key)
t = uint64(rec.Bins["t"].(int))
```

**Comment by bbulkow** [comment]
People using C put uint64s in and pull them out as uint64s. There is no molestation of the bytes, so it works. Aerospike's type system doesn't have "fine grained" type information like differentiating between uint64 and int64.

**Comment by lming** [comment]
Firstly casting math.MaxUint64 into int64 would cause overflow panic. http://play.golang.org/p/D6unDvRikJ
Secondly, even if the casting works, the ordering is lost. So we cannot put uint64 in a large list and take advantage its range access.

**Comment by khaf** [comment]
You used the constant directly, which raises compiler's suspicions.

This works: https://play.golang.org/p/Nh5f9rexNO

Alas, the ordering is sacrificed with this workaround.

**Comment by lming** [comment]
Good to know that at runtime the casting works.
I'll close this bug since Aerospike's type system doesn't differentiate uint64 and int64 anyways.

**Comment by gdm85** [comment]
@khaf what are your thoughts in adding support with a cast like [this](https://github.com/bookerzzz/aerospike-client-go/commit/d5757afb78850e74702e4098c3052bc5eecd3de1)?

What I am thinking now is: on 32 bit platforms `int` is 32bit (see also: http://stackoverflow.com/a/21491667), however the code there doesn't seem to take this in account? I worked on some open source serialization/deserialization logic and I thought that maybe we could have here some testcases for the corner cases where things could go wrong?

**Comment by khaf** [comment]
@gdm85 I'm against implicit conversions *inside* the library when the exact same type cast can be done by the developer. The implicit conversions are a nightmare to maintain, and cause too much a headache to be worthwhile.

At the moment the library does not support 32 bit platforms, so having this wouldn't help that cause. In case we decide to support 32bit platforms, there are more elegant solutions to explore as well.
