### ISSUE TITLE
Aggregation support for go client

### ISSUE THREAD

**Issue by SkyRocknRoll** [aerospike/aerospike-client-go#65]
http://www.aerospike.com/docs/architecture/clients.html
According to the above documentation go client does not support Aggregation . 
Is this still valid ? 
I would like to know whether Aggregation is implemented in aerospike go client ?

**Comment by wchu-citrusleaf** [comment]
This is correct. Go client current doesn't support Aggregation.

**Comment by GeertJohan** [comment]
@wchu-citrusleaf Are there plans to add it?

**Comment by wchu-citrusleaf** [comment]
Definitely on our radar. See https://github.com/aerospike/aerospike-client-go/issues/29
