### ISSUE TITLE
application crash during temporary network problem

### ISSUE THREAD

**Issue by quexer** [aerospike/aerospike-client-go#67]
We go temporary network problem in our prod env and it lead application crash. 
Here's the log:

     panic: send on closed channel
     goroutine 22366696 [running]:
     github.com/aerospike/aerospike-client-go.func·006(0xc20b83afa0)
        /usr/go/src/github.com/aerospike/aerospike-client-go/client.go:437 +0x145
     created by github.com/aerospike/aerospike-client-go.(*Client).ScanAll
        /usr/go/src/github.com/aerospike/aerospike-client-go/client.go:440 +0x4d4

Protection against this issue already exists,  [client.go#L439](https://github.com/aerospike/aerospike-client-go/blob/master/client.go#L439), but that's not enough.  Since there's still chance to send on closed channel.

```go
    go func(node *Node) {
        if err := clnt.scanNode(&policy, node, res, namespace, setName, binNames...); err != nil {
            if _, ok := <-res.Errors; ok {
                res.Errors <- err //still could crash here
            }
        }
    }(node)
```

In this case  ```recover()``` from application doesn't help because error occurs in separate go routine within aerospike-client-go 

My suggestion is never rely on 

```go
...
if _, ok := <-res.Errors; ok {
...
```

**Comment by khaf** [comment]
Correct, this was a bad idea. Fix is in master now.
