### ISSUE TITLE
panic during query

### ISSUE THREAD

**Issue by quexer** [aerospike/aerospike-client-go#70]
we got error below:

	panic: runtime error: slice bounds out of range

	goroutine 192347 [running]:
	github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseKey(0xc208a118a0, 0x979e, 0x4000, 0x0, 0x0)
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/batch_command.go:100 +0x41a
	github.com/aerospike/aerospike-client-go.(*queryRecordCommand).parseRecordResults(0xc2082d8060, 0x7f8a95f7f628, 0xc2082d8060, 0x1ffc0, 0x20300000001
	ffc0, 0x0, 0x0)
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/query_record_command.go:71 +0x6a4
	github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xc208a118a0, 0x7f8a95f7f628, 0xc2082d8060, 0xc208e6e580, 0x0, 0x0)
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/batch_command.go:66 +0x102
	github.com/aerospike/aerospike-client-go.(*queryCommand).parseResult(0xc208e9ec80, 0x7f8a95f7f628, 0xc2082d8060, 0xc208e6e580, 0x0, 0x0)
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/query_command.go:41 +0x5b
	github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc208cff9b0, 0x7f8a95f7f628, 0xc2082d8060, 0x0, 0x0)
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/command.go:989 +0x754
	github.com/aerospike/aerospike-client-go.(*queryRecordCommand).Execute(0xc2082d8060, 0x0, 0x0)
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/query_record_command.go:128 +0xa1
	github.com/aerospike/aerospike-client-go.func·008()
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/client.go:860 +0x33
	created by github.com/aerospike/aerospike-client-go.(*Client).Query
	/Users/cuixg/go/src/github.com/aerospike/aerospike-client-go/client.go:864 +0x385

We're using the latest version of aerospike-client-go  with aerospike server 3.5.9
our application is a long-running server, doing query every several minutes. Before this crash, it has been serving for a week

**Comment by GeertJohan** [comment]
When `cmd.readBytes(fieldlen)` at line batch_command.go:88 didn't return with an error, then `cmd.dataBuffer` must have a length of at least `fieldlen` bytes. A `slice bounds out of range` panic should not occur on a slicing that is essentially `cmd.dataBuffer[1:fieldlen]`..

So, could this be a race?

**Comment by khaf** [comment]
This is puzzling indeed. `cmd.dataBuffer` is local to the `cmd` and contained in a single goroutine, so it should not have race, unless there's a problem with buffer pool logic.

I'll have to dig deep for this one.

**Comment by GeertJohan** [comment]
I think I might have an idea of what happened.
It seems very unlikely that there is a race, the only place where goroutines are started i the whole chain is directly at `Client.Query()`, and the `BufferPool` is goroutine-safe.

What *could* have happened is  that `Buffer.BytesToInt32(cmd.dataBuffer, 0)` at batch_command.go:87 returned a negative integer. That must have been `-2147483648` to be exact. The call to `readBytes()` at line 88 will return without actually reading any bytes. `size := fieldlen - 1` flips the integer to positive, which then causes the panic at line 100.

I wasn't sure on the behavior of `int(uint32(negativeNumber))`, but apparently in go `int(uint32(-20))` is still `-20`. See: http://play.golang.org/p/UlWa2JjdlN

**Comment by GeertJohan** [comment]
Ah no that wouldn't work, its `[1:size+1]`, so it would be flipped back to `-2147483648` which gives a different panic message.. Sorry :speak_no_evil:

**Comment by khaf** [comment]
I merged Geert's PRs and did a few other suspect fixes to the unpacker.

The new release is pushed to the master. I'd appreciate it if you could give it a try and see if it fixes your issue.

**Comment by quexer** [comment]
I'll give it a try.  But not sure we can re-produce it.
Thanks.

**Comment by ericdmann** [comment]
Just had the same issue with the most recent release.

**Comment by volmarl** [comment]
@ericdmann Would it be possible to also get code snippet to reproduce the bug?

**Comment by ericdmann** [comment]
Just sent code to support :)

**Comment by GeertJohan** [comment]
@ericdmann: can you share the reproducing code publicly? Or not because of security flaw or company restrictions?

**Comment by khaf** [comment]
Look like this has been due to a lack of error checking on network failures in Scan/Query. I pushed a fix yesterday that should have fixed this issue. Please give it a try and let me know if it has fixed the issue.

**Comment by ericdmann** [comment]
Update yesterday seemed to resolve it for us. Nice catch!

**Comment by khaf** [comment]
Thank you everyone for your help and patience.
