### ISSUE TITLE
Any way to get list of sets?

### ISSUE THREAD

**Issue by elgris** [aerospike/aerospike-client-go#73]
Aerospike has nice tool `acl` that I can use to fire `SHOW SETS` query. Just wondering if it's possible to do the same with the Go client.

**Comment by khaf** [comment]
Sure you can! Use `RequestInfo()` method:

```go
client, err := as.NewClientWithPolicy(clientPolicy, host, port)
// handle error

node := client.GetNodes()[0]
conn, err := node.GetConnection(10 * time.Second)
// handle error

// THIS IS THE PART YOU PASS IN YOU INFO COMMAND, IN THIS CASE: sets
infoMap, err := as.RequestInfo(conn, "sets")
// handle error

fmt.Println(infoMap)
```
You can refer to [Info documentation](http://www.aerospike.com/docs/reference/info) too see what other commands are available.

**Comment by elgris** [comment]
thanks! :+1:
