### ISSUE TITLE
Timeout and connection pooling

### ISSUE THREAD

**Issue by frankyin1019** [aerospike/aerospike-client-go#74]
In our production setup, we have several client servers querying the aerospike cluster(Get request). One of the server keeps having massive connection to the cluster in TIME_WAIT state. 

We figured out today that it is because we are setting a timeout in the Get request, and we didn't realize that the timeout is also set as the socket timeout for the underlying connection.
```
readPolicy := aerospike.NewPolicy()
readPolicy.Timeout = 80 * time.Millisecond 
r, err := client.Get(readPolicy, k)
```

That server itself seems to have longer network lag with the cluster, but we still want to enforce the same timeout for the get in our app. In this case, the connection pooling is useless because we close the connections so fast.

Our temporary solution is to run this call in a go routine and enforcing the timeout on the go routine.
Wondering if there is any suggestions, or maybe the driver can choose to not close the socket.

Thanks

**Comment by khaf** [comment]
The client needs to close the socket on timeouts, since the state of the socket after the timeout is unknown and it may have leftover content.

If you want to enforce a restriction on the number of connections, set 
```go
ClientPolicy.LimitConnectionsToQueueSize = true
``` 

to prevent the client to create a new connection for each request in case there are already `ConnectionQueueSize` connections open.

You should then tweak the `ConnectionQueueSize`, since the default may be too low for big production iron.

You may also elect to customize the timeouts per server, and pre-warm and determine the avg latency to the cluster on app startup.

**Comment by frankyin1019** [comment]
Thanks for the reply.

We did have  ```LimitConnectionsToQueueSize = true``` set and the ```ConnectionQueueSize``` is set to 1024. 
But in production, the number of connections from the server to the AS cluster was around 200k. We tweaked the ```ConnectionQueueSize``` various times from default to 8192. The number of connections did not change much. Again 99% of them are in TIME_WAIT state. Thus we are not sure if  the ```ConnectionQueueSize``` is enforced, or it takes TIME_WAIT as "closed".

**Comment by khaf** [comment]
This may be a bug. I'll have a look and come back to you. 

How long does it take for your server to reach such massive waiting connections?
Do you set timeout for all operations (get/put/queries, ...), or just some of them?

**Comment by frankyin1019** [comment]
Thanks.
Currently we only have a Get request, which we use 80ms as the timeout. 
The number of connections would peak at around 3-5 mins after the app starts.

**Comment by khaf** [comment]
@frankyin1019 Are you still experiencing the same issue?

**Comment by khaf** [comment]
I'll go ahead and close this issue since per forum discussion, this issue was not experienced again.
