### ISSUE TITLE
Generation Type Inconsistent

### ISSUE THREAD

**Issue by birkirb** [aerospike/aerospike-client-go#79]
Here it's an int32:

https://github.com/aerospike/aerospike-client-go/blob/master/write_policy.go#L55

Here it's an int:

https://github.com/aerospike/aerospike-client-go/blob/master/record.go#L35

Would be nice if these were consistent.

**Comment by localhots** [comment]
:+1:

**Comment by khaf** [comment]
Fixing this trivial, but this will break many a perfectly working code base. If there are more up votes, I'll do it willingly. Down votes are also welcome.

**Comment by birkirb** [comment]
:+1: I'll happily update my perfectly working code ;)

**Comment by khaf** [comment]
Time to update! Latest release took care of this :)

**Comment by localhots** [comment]
Great, thanks!
