### ISSUE TITLE
implement high-priority scan

### ISSUE THREAD

**Issue by memunix** [aerospike/aerospike-client-go#82]
Regarding Aerospike Server CE Release Notes v3.6.0:
 
(KVS) [AER-2986] Scan improvement.
* Concurrent scan jobs are interlaced, allowing progress on all scans.
* **Add ability to promote a scan to high-priority so it can be processed immediately.**
* Add ability to change number of scan threads during scans.
* Performance improvement.

I can see no way of doing this with the current client - the ScanPolicy type currently has no field for priority. Is there something I'm missing here, or are you working on it? :smile:

**Comment by bbulkow** [comment]
Working on it. We rolled the feature out first in Java, C, C# and the other clients are "catching up". I'm sure when the primary engineer sees this it won't be long until a checkin :smile:

**Comment by khaf** [comment]
I confirm the working on it status :)

**Comment by wchu-citrusleaf** [comment]
It is possible to promote specific scan priority using operational tools such as asinfo -
See http://www.aerospike.com/docs/operations/manage/scans/
