### ISSUE TITLE
Recordset to struct

### ISSUE THREAD

**Issue by ClanStyles** [aerospike/aerospike-client-go#88]
Short of making a FromRecord(as.Recordste) Model type function, is there an easier way to query and convert data frmo a recordset to a model?

Thank you

**Comment by khaf** [comment]
You mean something like `Get/PutObject` methods?

**Comment by ClanStyles** [comment]
Well I want to query based on a statement or a UDF then return the data into an object again.

In my case I have a record ID but I pull based on a token string consistently. It can't be the record ID for other reasons. So I assume a query like filter where equal. Then run a db.Query(nil, statement)

**Comment by khaf** [comment]
If you mean you want `Scan/QueryObjects` methods, then I have good news: That feature is coming this week, or early next week latest :)

**Comment by ClanStyles** [comment]
Ah! I have a direct need for it now. I'll write my cheap wrapper for now and wait for your update! :+1:

**Comment by khaf** [comment]
Released. Please feel free to let me know your thoughts on the API.
