### ISSUE TITLE
[aerospike-server 3.6.3 ] System Shutdown With Panic : runtime error: index out of range

### ISSUE THREAD

**Issue by figoxu** [aerospike/aerospike-client-go#94]
The Panic StackTrace Is As Follow :

------------------------------------------------------------------------------
goroutine 42 [running]:
github.com/aerospike/aerospike-client-go.(*Node).addFriends(0xc8200e3970, 0xc8217071d0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/node.go:155 +0x44e
github.com/aerospike/aerospike-client-go.(*Node).Refresh(0xc8200e3970, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/node.go:102 +0x2b7
github.com/aerospike/aerospike-client-go.(*Cluster).tend(0xc82160a000, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/cluster.go:170 +0x1c7
github.com/aerospike/aerospike-client-go.(*Cluster).clusterBoss(0xc82160a000, 0xc82000a1e0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/cluster.go:115 +0x237
created by github.com/aerospike/aerospike-client-go.NewCluster
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/cluster.go:92 +0x5b6

------------------------------------------------------------------------------
We Using [ aerospike-client-go ] with version 2015-7-17 .
![drive](https://cloud.githubusercontent.com/assets/10055828/11388380/85320dc8-9370-11e5-9246-6c0c014d07dd.png)

That Driver working well with Aerospike-Server 3.5  / 3.6.0  which is without this panic.
On the Aerospike-Server 3.6.3 ,We see that panic each two days in the afternoon .

How do i slove that PANIC ?

**Comment by khaf** [comment]
This particular issue has been resolved in the latest client.

**Comment by figoxu** [comment]
@khaf 

Does the latest client is means V1.7.0 ? If so, It's commit on October 16 2015 .
![drive001](https://cloud.githubusercontent.com/assets/10055828/11393170/0e354900-9399-11e5-8aeb-450753b91735.png)
But we can see the aerospike-server Version: 3.6.3  also release on October 16 2015 .
![server001](https://cloud.githubusercontent.com/assets/10055828/11393247/9783dd48-9399-11e5-9034-3988a3cace4b.png)

I was confused,  Does client driver can fix the bug with the server which release on the same day ?

**Comment by khaf** [comment]
We test the clients with internal releases of the server, so yes, it can :)

**Comment by figoxu** [comment]
How long does this bug exist ? 
Does client driver of  2015-7-17 work with aerospike-server  3.5 / 3.6.0  will cause this problem?
Can you give me an suggest version of client drive and server version ?

**Comment by khaf** [comment]
This was a bug in the client, fixed for the client on [this commit](https://github.com/aerospike/aerospike-client-go/commit/2a16dc4a8459c74564d1db75aafceda9326c75ac)

I suggest you always use the latest version of both client and the server.

**Comment by figoxu** [comment]
Does client driver v1.7 can work well with aerospike-server 3.5 / 3.6.0 ?

**Comment by khaf** [comment]
It does. It is always prudent to test your own app before pushing to production though.

**Comment by figoxu** [comment]
During i upgrade client driver to V1.7.0 , System was panic with the stacktrace as follow:

-------
panic: runtime error: slice bounds out of range

goroutine 4914 [running]:
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseKey(0xc828961d80, 0xd916, 0x0, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/batch_command.go:100 +0x47a
github.com/aerospike/aerospike-client-go.(*queryRecordCommand).parseRecordResults(0xc8226d4a90, 0x7fc21bda8208, 0xc8226d4a90, 0xfffd2, 0x1, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/query_record_command.go:72 +0x8e9
github.com/aerospike/aerospike-client-go.(*baseMultiCommand).parseResult(0xc828961d80, 0x7fc21bda8208, 0xc8226d4a90, 0xc82b426740, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/batch_command.go:66 +0x24e
github.com/aerospike/aerospike-client-go.(*queryCommand).parseResult(0xc82895cf40, 0x7fc21bda8208, 0xc8226d4a90, 0xc82b426740, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/query_command.go:41 +0x4e
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc8281e5da0, 0x7fc21bda8208, 0xc8226d4a90, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/command.go:989 +0x9e7
github.com/aerospike/aerospike-client-go.(*queryRecordCommand).Execute(0xc8226d4a90, 0x0, 0x0)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/query_record_command.go:129 +0xa0
github.com/aerospike/aerospike-client-go.(*Client).Query.func1(0xc8226d4a90, 0xc82b426700)
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/client.go:860 +0x21
created by github.com/aerospike/aerospike-client-go.(*Client).Query
	/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/client.go:864 +0x461
-----

all of the stacktrace are comes from aerospike-client-go
