### ISSUE TITLE
Big int values

### ISSUE THREAD

**Issue by alicebob** [aerospike/aerospike-client-go#95]
I'm trying to put a int64 in Aerospike (a value returned by time.UnixNano()), but I'm silently loosing the last byte of the number:

https://gist.github.com/alicebob/67930e7a66ec8449609a

gives me:
```
$ go run aeint.go 
RegisterUDF done
now: 1448620433513994439
res: 1448620433513994496
oops: have 1448620433513994496, want 1448620433513994439
```

In bits:
```
>>> "{:b}".format(1448620433513994439); "{:b}".format(1448620433513994496)
'1010000011010100010001001101111110001111110010101100011000111'
'1010000011010100010001001101111110001111110010101100100000000'
```

In the logs:
```
Nov 27 2015 10:33:52 GMT: INFO (udf): (udf_cask.c::516) UDF module 'echoint.lua' (/opt/aerospike/usr/udf/lua/echoint.lua) registered
Nov 27 2015 10:33:53 GMT: INFO (udf): ([C]::-1) call echoint with 1448620433513994496
```

**Comment by khaf** [comment]
Unfortunately, this is a limitation of the current version of Lua that we are using on the server. Please see: http://www.aerospike.com/docs/udf/known_limitations.html

At the moment, passing full 64bit integers to Lua is not possible.

**Comment by alicebob** [comment]
Thanks for the answer. We can work around this for timestamps, and wait for the Lua 5.3 improvement.
