### ISSUE TITLE
Client V1.7.0 : panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by figoxu** [aerospike/aerospike-client-go#96]
During i upgrade client driver to V1.7.0 , System was panic with the stacktrace as follow:

--------

panic: runtime error: slice bounds out of range

goroutine 4914 [running]:
github.com/aerospike/aerospike-client-go.(baseMultiCommand).parseKey(0xc828961d80, 0xd916, 0x0, 0x0, 0x0)
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/batch_command.go:100 +0x47a
github.com/aerospike/aerospike-client-go.(queryRecordCommand).parseRecordResults(0xc8226d4a90, 0x7fc21bda8208, 0xc8226d4a90, 0xfffd2, 0x1, 0x0, 0x0)
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/query_record_command.go:72 +0x8e9
github.com/aerospike/aerospike-client-go.(baseMultiCommand).parseResult(0xc828961d80, 0x7fc21bda8208, 0xc8226d4a90, 0xc82b426740, 0x0, 0x0)
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/batch_command.go:66 +0x24e
github.com/aerospike/aerospike-client-go.(queryCommand).parseResult(0xc82895cf40, 0x7fc21bda8208, 0xc8226d4a90, 0xc82b426740, 0x0, 0x0)
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/query_command.go:41 +0x4e
github.com/aerospike/aerospike-client-go.(baseCommand).execute(0xc8281e5da0, 0x7fc21bda8208, 0xc8226d4a90, 0x0, 0x0)
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/command.go:989 +0x9e7
github.com/aerospike/aerospike-client-go.(queryRecordCommand).Execute(0xc8226d4a90, 0x0, 0x0)
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/query_record_command.go:129 +0xa0
github.com/aerospike/aerospike-client-go.(Client).Query.func1(0xc8226d4a90, 0xc82b426700)
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/client.go:860 +0x21
created by github.com/aerospike/aerospike-client-go.(Client).Query
/home/figo/develop/env/GOPATH/src/github.com/aerospike/aerospike-client-go/client.go:864 +0x461

--------

all of the stacktrace are comes from aerospike-client-go. How can i slove that panic ?

**Comment by khaf** [comment]
I can't quite reproduce this problem. Does it happen every time you do a query / scan, or just randomly?

**Comment by khaf** [comment]
Also, what version of Aerospike are you using? And what type of environment? (Cloud? Self Hosted?)

**Comment by khaf** [comment]
The new release includes some improvements in error handling and fault tolerance. Please give it a try and let me know if you still encounter this problem.

**Comment by figoxu** [comment]
The version we use is "aerospike-server-community-3.5.12-ubuntu12.04"
The Linux System Info is 
Linux version 3.13.0-68-generic (buildd@lgw01-46) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) )
The panic was happen When we QUERY the recod with index of one column . 
 
I also see some EOF error：
![aerospike_eof](https://cloud.githubusercontent.com/assets/10055828/11528040/451fa59c-991f-11e5-943b-f0054364ed5a.png)
When i see the EOF,the asmonitor info of aerospike is as follow:
![aerospike_info](https://cloud.githubusercontent.com/assets/10055828/11528056/5e716abc-991f-11e5-8254-5603007ac9cc.png)
It seems lack of memory.

**Comment by khaf** [comment]
hmmm, this is quite an error to reproduce. What I have been able to learn until now is that it seems you are experiencing a random disconnect. The error codes are not available since the wire protocol is interpreted wrongly. Part of the problem should be solved with the v1.8.0 release, since the logic to keep suspected connections have become more conservative. But I still cannot understand why your connection is being dropped with such a rate.

Have you made sure that your networking gear is in perfect working order?

**Comment by figoxu** [comment]
We upgrade the drive to v1.80 , still now ,the error is not reproduce.
