### ISSUE TITLE
panic on Node.GetConnection

### ISSUE THREAD

**Issue by joshk0** [aerospike/aerospike-client-go#97]
This occurs in a special situation (i think): When the Aerospike host you are connecting to is actually a round-robin reverse-proxy to a set of Aerospike hosts (specifically, a [Kubernetes service without a selector](http://kubernetes.io/v1.0/docs/user-guide/services.html#services-without-selectors))

It occurs with client 1.7.0 but not 1.3.1 (old version which we were using.)

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x6f938d]

goroutine 118 [running]:
github.com/aerospike/aerospike-client-go.(*Node).GetConnection(0x0, 0x0, 0xc2087b3030, 0x0, 0x0)
	/opt/build/src/github.com/aerospike/aerospike-client-go/node.go:231 +0x7d
github.com/aerospike/aerospike-client-go.(*baseCommand).execute(0xc208141b30, 0x7fd63b2c8468, 0xc2087b3030, 0x0, 0x0)
	/opt/build/src/github.com/aerospike/aerospike-client-go/command.go:1001 +0x300
github.com/aerospike/aerospike-client-go.(*batchCommandGet).Execute(0xc2087b3030, 0x0, 0x0)
	/opt/build/src/github.com/aerospike/aerospike-client-go/batch_command_get.go:149 +0x71
github.com/aerospike/aerospike-client-go.func·010(0x0, 0xc208141890)
	/opt/build/src/github.com/aerospike/aerospike-client-go/client.go:1191 +0xa3
created by github.com/aerospike/aerospike-client-go.(*Client).batchExecute
	/opt/build/src/github.com/aerospike/aerospike-client-go/client.go:1196 +0x3ca
```

**Comment by khaf** [comment]
The new release includes some improvements in error handling and fault tolerance. Please give it a try and let me know if you still encounter this problem.

**Comment by joshk0** [comment]
It seems better, I'll leave it running for a week and report back here afterwards.

**Comment by khaf** [comment]
Since I haven't heard back about the issue, I'll close the issue. Please feel free to file new tickets.
